### ISSUE TITLE
Better memory management for multipart form-data

### ISSUE THREAD

**Issue by CarlEkerot** [jorisvink/kore#100]
First of all, thanks for this cool project. I've been looking for a small and efficient framework for creating simple REST APIs, and kore fits most of the thinkable criterias.

Now to my main concern; It seems like a buffer of the same size of the `Content-Length` header is allocated for each incoming request. In most situations, this is fine. However, when a file is uploaded using multipart form-data, this potentially results in quite large allocations. This might be an issue if someone constructs requests with spoofed content lengths and use that in a DoS attack.

Perhaps it's possible to process the request body in chunks of some size, thus avoiding the large allocations? In the multipart case, it would make sense to have a `read`-like interface to read the file data.

**Comment by jorisvink** [comment]
> First of all, thanks for this cool project. I've been looking for a small and efficient framework for creating simple REST APIs, and kore fits most of the thinkable criterias.

Awesome :)

> Now to my main concern; It seems like a buffer of the same size of the Content-Length header is allocated for each incoming request.

Correct, for requests that contain a body a kore_buf is allocated to hold the body of the incoming request.

> However, when a file is uploaded using multipart form-data, this potentially results in quite large allocations. This might be an issue if someone constructs requests with spoofed content lengths and use that in a DoS attack.

It would also count in the normal circumstances if the request holds a very large body. Not just for multipart forms. Having said that there is a configuration directive to control this: http_body_max.

If the incoming content-length for a body is larger then this a 413 is returned to the client (before a kore_buf is allocated). This is simply up to you as a developer to tweak in the configuration file while keeping in mind the number of concurrent connections that may send you HTTP bodies.
 
> Perhaps it's possible to process the request body in chunks of some size, thus avoiding the large allocations? In the multipart case, it would make sense to have a read-like interface to read the file data.

Where exactly would you suggest the body data is stored intermediately in such a case?

**Comment by CarlEkerot** [comment]
The `http_body_max` solution is great, but lowering it doesn't quite cut it if I'm intending to use the framework as a backend for a filedump or similar.

I was thinking along the lines of deferring any socket reads of the body contents until it's specifically asked for.

**Comment by jorisvink** [comment]
> I was thinking along the lines of deferring any socket reads of the body contents until it's specifically asked for.

You mean until your page handler asks for it, right?

**Comment by jorisvink** [comment]
Yup after giving it some thought it would be great if a page handler could process the actual request first before any new data comes in.

This would require a new helper function in the likes of http_body_receive() which your handler would call. This could get a callback which is called for every X bytes of body that is available until the incoming body data is exhausted.

If said function takes a user data pointer you could pass it any state data you'd like (like an open fd where your callback would write the data too).

**Comment by CarlEkerot** [comment]
Sounds great, looking forward to the "fix"!

**Comment by jorisvink** [comment]
Right, so I've gone more of the route of having incoming HTTP bodies being written to disk if they pass a certain threshold (configurable). Due to the way multipart bodies are structured we need to have the entire body somewhere in order to parse it properly.

I will be changing the semantics for all the http functions that relate to reading/parsing body bytes so from a higher level (your page handlers) it will not notice if its a body that is held in memory or on disk.

The semantics for http_file_lookup() will also change: it will return to you a data structure describing where the file contents will be found. This should be then passed in to a new function http_file_read(struct http_file *file, void *buf, size_t buflen) which will allow you to read buflen bytes of the file at a time (which in the lower level will either come from the buffer or the file in which data is stored).

Expecting this to hit the tree somewhere tomorrow.

**Comment by jorisvink** [comment]
A bit delayed with this, but still expecting this somewhere this week as I have it working in my tree.

**Comment by jorisvink** [comment]
@CarlEkerot Give the latest code from master a spin. Things should have improved drastically.

Alternatively see the new upload example as well.

**Comment by CarlEkerot** [comment]
That's a huge changeset. Will give it a spin once I get home from work.

Thanks, @jorisvink. Really excited to try this out.

**Comment by jorisvink** [comment]
> Will give it a spin once I get home from work.

Were you able to test this @CarlEkerot? Would love to know if it helped.

**Comment by CarlEkerot** [comment]
@jorisvink: Only tried the generic file upload example so far, which seems to work. Have plans on constructing a personal little filedump in Kore (main reason I started looking at Kore to begin with). Will report any "findings" in this ticket =)

**Comment by jorisvink** [comment]
@CarlEkerot Cool!

**Comment by jorisvink** [comment]
@CarlEkerot ping

**Comment by CarlEkerot** [comment]
@jorisvink: Sorry for not getting back to you. I've experimented with the new code, and it works well for my needs =) The API is much cleaner now that the number of params for `http_populate_multipart_form` and `http_file_lookup` have been reduced.

**Comment by jorisvink** [comment]
@CarlEkerot Very cool to hear! Thanks for the feedback.
