### ISSUE TITLE
assets.h file missing in example.c

### ISSUE THREAD

**Issue by AntonioCS** [jorisvink/kore#104]
I am going through the examples to get a better understanding of kore.io and in

> examples/generic/src/example.c

I can't locate the **assets.h file** which is included in line 20.
Please advise.

**Comment by jorisvink** [comment]
The assets.h file is auto generated when you build using "kore build".

The build process will take all files under assets/ and convert them into byte arrays so they can be referenced as symbols in your code.

.joris

**Comment by AntonioCS** [comment]
Thanks for clearing that up. Is there a reference of that in the documentation, just so that I read a bit more on this?

Thanks again.

**Comment by jorisvink** [comment]
https://kore.io/doc/ should have this.
