### ISSUE TITLE
Possible for kore to use custom makefile in kore build/run

### ISSUE THREAD

**Issue by AntonioCS** [jorisvink/kore#106]
Hey,

I am using mysql and curl in one of my modules and the only way to get this to work is to:
- run make
- run kore -c conf/my_conf.conf -n -r

By doing this I am able to run kore without the module throwing this error:

`fatal error: my_global.h: No such file or directory`

So what I am asking is if it would be possible to specify a makefile either as a parameter or maybe something in the conf file.

**Comment by jorisvink** [comment]
Heya,

Use CFLAGS and LDFLAGS.

The kore build command will pick those up from your environment and use them.

.joris

**Comment by AntonioCS** [comment]
I tried that and still got these errors:

> /usr/include/mysql/my_global.h:528:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
>  typedef void (*sig_return)();/* Returns type from signal */
>  ^
> In file included from /usr/include/mysql/my_global.h:1039:0,
>                  from ./src/kore_file.c:1:
> /usr/include/mysql/my_dbug.h:66:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
>  extern  void _db_flush_();
>  ^
> /usr/include/mysql/my_dbug.h:135:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
>  extern void _db_suicide_();
>  ^
> In file included from /usr/include/mysql/my_sys.h:44:0,
>                  from ./src/kore_file.c:2:
> /usr/include/mysql/my_pthread.h:868:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
>  extern void **my_thread_var_dbug();

At the end I got 

kore_test built successfully!
[parent]: running on https://127.0.0.1:8888
kore: ./kore_test.so: ./kore_test.so: undefined symbol: mysql_query

I tried hitting the kore server by calling curl and it failed so I don't think kore was started.

**Comment by jorisvink** [comment]
Your module wasn't linked with whatever you need to link with for mysql.

```
$ env LDFLAGS="-L/path/to/mysql/lib -lmysqlstuff" kore build
```

**Comment by jorisvink** [comment]
@AntonioCS Did linking against the properly libraries using LDFLAGS solve your issue? =)

**Comment by AntonioCS** [comment]
Not really. It compiles but I still get warnings from mysql headers.
Here is what I tried:


```
$ env LDFLAGS="-lcurl -lmysqlclient" CFLAGS="-Wall -g -std=c11 -shared -fpic -I/usr/include/mysql -Wno-strict-prototypes" kore run

compiling my_file.c
In file included from ./src/my_file.c:1:0:
/usr/include/mysql/my_global.h:528:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 typedef void (*sig_return)();/* Returns type from signal */
 ^
In file included from /usr/include/mysql/my_global.h:1039:0,
                 from ./src/my_file.c:1:
/usr/include/mysql/my_dbug.h:66:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 extern  void _db_flush_();
 ^
/usr/include/mysql/my_dbug.h:135:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 extern void _db_suicide_();
 ^
In file included from /usr/include/mysql/my_sys.h:44:0,
                 from ./src/my_file.c:2:
/usr/include/mysql/my_pthread.h:868:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 extern void **my_thread_var_dbug();
 ^
In file included from ./src/my_file.c:2:0:
/usr/include/mysql/my_sys.h:624:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 extern const char** get_global_errmsgs();
 ^
/usr/include/mysql/my_sys.h:643:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 extern int my_error_register(const char** (*get_errmsgs) (),
 ^
/usr/include/mysql/my_sys.h:853:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 extern ulonglong my_micro_time();
 ^
/usr/include/mysql/my_sys.h:857:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 extern int my_getncpus();
 ^
./src/my_file.c:27:14: warning: 'json_response' defined but not used [-Wunused-variable]
 static char *json_response = "{             \
              ^
kore_mlp built successfully!
[parent]: running on https://127.0.0.1:8888
[parent]: kore is starting up
[wrk 0]: worker 0 started (cpu#0)
[wrk 0]: module loading
```

The last warning I understand and think is valid but I can't get rid of the other warnings because I believe kore simply adds my CFLAGS to its CFLAGS and doesn't realy overwrite it. 

PS: I sent an email to the address in the website don't know if you saw it or not but please give me a reply. I finally manged to get everything to work but I still think my email is worthy of a read and a reply :D

**Comment by jorisvink** [comment]
Yes, those errors are because of sane compiler flags Kore sets by default and any environment CFLAGS are simply added to said sane list.

However your problem of not being able to link are gone.

> PS: I sent an email to the address in the website don't know if you saw it or not but please give me a reply. I finally manged to get everything to work but I still think my email is worthy of a read and a reply :D

I did?

Jan 23 19:12:57 treo postfix/smtp[23637]: EAF2066254: to=youremail, relay=gmail-smtp-in.l.google.com[2a00:1450:4013:c01::1a]:25, delay=0.79, delays=0.06/0.02/0.32/0.39, dsn=2.0.0, status=sent (250 2.0.0 OK 1453572777 v18si16530345wju.157 - gsmtp)

**Comment by AntonioCS** [comment]
Yes the linking issues are gone but I still find it annoying to see the warnings when I compile hence my request for a custom makefile. I am sure you could implement some guidelines on how to create custom makefles and this way I would have better control of how my module was compiled but as long as it works I guess its ok.

Your email went to spam :(

> Why is this message in Spam? It's in violation of Google's recommended email sender guidelines.

Thanks for replying.

**Comment by jorisvink** [comment]
> Yes the linking issues are gone but I still find it annoying to see the warnings

I hear you, I really do. But if you are using kore build/run you are going to be stuck with the sane default compiler flags it sets. If you want more fine grained control: hacking together a Makefile that builds your dynamic library is the way to go.

I do not think I would even give kore build/run the possibility to "use" a custom whatever as this issue describes though, a lot of complications in relation to asset building would show up. One option I may consider is moving user specified CFLAGS towards the end so they can be used to override things if anything.

If warnings from third party code annoy you, you could perhaps poke those maintainers to fix their stuff.

> I am sure you could implement some guidelines on how to create custom makefles and this way I would have better control of how my module was compiled

A guide on writing Makefiles is out of scope of this project to be honest.

> Your email went to spam :(

Turns out I never updated my IPv6 address in my SPF record. Who knew :)

**Comment by AntonioCS** [comment]
> A guide on writing Makefiles is out of scope of this project to be honest.
This is for people that quickly want to create modules with their own makefile. I am not the [first to bring this up](https://github.com/jorisvink/kore/issues/81)

I will close this issue for now as I see reading custom makefiles is not something you want. Thanks for the help.

**Comment by jorisvink** [comment]
> reading custom makefiles is not something you want.

Correct. You already solved your problem in the first post in this issue. You made a Makefile allowing you to build your module with whatever flavours needed. Then you started Kore with the command line options, which is the way to go as kore run might start rebuilding everything.

This is why I fail to see the reasoning behind wanting to integrate this with kore build/run. The two approaches are completely stand apart from one and other.

As for examples on how to build a Makefile for building a normal dynamic library ... if one really wants to do this one should already be familiar enough with the subject matter to figure out how to build a dynamic library and how to reflects on your Makefile rules.

.joris
