### ISSUE TITLE
 2 or more workers, slow

### ISSUE THREAD

**Issue by ariveira** [jorisvink/kore#107]
If I have only one worker, this is the result benchmark:
1 0.025113043
2 0.001367477
3 0.001229754
4 0.001250715
5 0.001200099
6 0.001045847
7 0.001305957
8 0.001171051
9 0.00114078
10 0.001340209
11 0.001190162

If I have two or more workers, this is the result benchmark:

1 0.042119974
2 0.063188356
3 0.433000796
4 0.063587613
5 0.53234354
6 0.063403492
7 0.532451653
8 0.063334959
9 0.53242806
10 0.063391639
11 0.532373902

It is notably slower, what could be wrong?
Tanks !

**Comment by jorisvink** [comment]
Some context may be good.

How are you testing this? What kind of configuration are you using?

Bumping the workers and expecting the "benchmark" results to increase is wrong.

**Comment by ariveira** [comment]
Thanks for your quick reply !

I using examples/generic. Em second test change file configuration add "workers 2".

My test is a ruby file:

require 'open-uri'
1.upto(10) do |i|
  start = Time.now
  open("http://127.0.0.1:8888/")
  puts "#{i} #{(Time.now - start)}"
end

Regards

**Comment by jorisvink** [comment]
I'm not sure running a home grown ruby script to perform benchmark tests on a web framework is a good thing.

Bumping workers in your Kore configuration is really not going to make a difference here as your "test" is not doing things concurrently at all. All your requests are serialised.

**Comment by ariveira** [comment]
My point is not to try to extract high-performance results. But understand why having two workers have answers up to 0.50 seconds.

I would not have to manage the workers to unlock and accept or this is automatically managed by kore?

**Comment by jorisvink** [comment]
And my point is that you are benchmarking things in the wrong way. Your requests happen *one* after the *other* and are always going to end up on a single worker so you don't have 2 workers answering.

Most likely your ruby vm is interfering with the actual results, or your machine was busy with something else the second time around.

How many times have you ran this? Did you take averages or just the straight results? With an incredibly contrived benchmark script can you guarantee that it is not wasting time itself?

**Comment by ariveira** [comment]
I do not understand, please help me, with two workers and the test being done straight he should not give similar results?

**Comment by ariveira** [comment]
I got it, seems to be a problem come ruby, I changed to the next, following the results:

require 'open-uri'
list  = Array.new
mutex = Mutex.new
1.upto(10) do |i|
  list << Thread.new do
    start = Time.now
    open("http://127.0.0.1:8888/")
    mutex.synchronize do
      puts "#{i} #{(Time.now - start)}"
    end
  end
end
list.each{|t| t.join}



1 worker:
2 0.03188118
5 0.031984467
7 0.032115277
10 0.031917393
8 0.03233577
9 0.032218992
1 0.036800411
4 0.031875317
3 0.033812582
6 0.032802474

real	0m0.108s
user	0m0.084s
sys	0m0.024s

2 workers:
3 0.048255244
7 0.060103787
10 0.060184679
6 0.062468972
4 0.061213836
8 0.062330447
5 0.063529813
1 0.066807759
9 0.062278067
2 0.066139739

real	0m0.134s
user	0m0.084s
sys	0m0.028s

Tanks for your help !!!

**Comment by jorisvink** [comment]
> I got it, seems to be a problem come ruby

Well yes and no.

I was mistaken in saying it only uses a single worker.

Obviously the workers multiplex the accept socket between each other.

In your "test" each time it connects and performs an HTTP request the worker that accepted that socket relinquishes the accept socket so another worker can pick it up. There is a delay here, which is going to be the delay you were seeing in your first test case.

Under high volume traffic this becomes much less noticeable as workers accept more then a single connection per time.

**Comment by ariveira** [comment]
These new tests prove the ruby problem come and testify for 2 workers work perfectly.
10 requests:

1 worker 
time curl http://127.0.0.1:8888?[1-10]
real	0m0.017s
user	0m0.008s
sys	0m0.004s

2 workers
time curl http://127.0.0.1:8888?[1-10]
real	0m0.017s
user	0m0.012s
sys	0m0.000s


Thank you for your great help !
