### ISSUE TITLE
[enhancement] avoid memory copy from recv buffer (net buf) to http body(kore buf)

### ISSUE THREAD

**Issue by ansend** [jorisvink/kore#110]
Notice that all http body for post and put request is firstly received and stored in recv buf(net buf), then is copied to http body buf(kore buf) or written to http body file if body size exceeds payload threshold.  This means most of http request bodies will experience a memory copy, It may impact performance for post or put request. I'm thinking about a way to release net buf data to http body kore buf, only pass the  data buffer instead of memroy copy.

**Comment by jorisvink** [comment]
You are right.

It would be possible but it requires a bit of trickery. I'm not sure if it's even worth the trade off but I'm open for this.

**Comment by ansend** [comment]
Hi Joris,

I just new a pull request about this enhacement. It's only for calling for you review and comments. agree with you it's a little bit of trickery.   per performance perspective , I think the memroy copy should be avoided, but there maybe other better way to do that.

**Comment by jorisvink** [comment]
Super, I'll look at it in a bit.

**Comment by XuningNiu** [comment]
ansend is right about the memory copy, but I meet another issue:
I'm using kore in my project, when I upload a large file which is more than 100M, and in the same time ,the system have no more than 100M free memory, the memory is not enough.
I am thinking if we can add one option about store the whole file in memory or disk when uploading? 
It maybe useful when we have a super large file to upload.
I have realized this feature in my project, and it is runing normally by now.
what do you think? thanks.

**Comment by jorisvink** [comment]
@XuningNiu This feature exists. Please try the latest code from github master. Kore will offload HTTP bodies to disk if they reach a certain threshold. You can find an example of how to deal with this new API in the examples/upload directory.

**Comment by jorisvink** [comment]
I'm not going to let this through right now, until this becomes an actual bottleneck that is hindering Kore from performing its duties.

Closing this.
