### ISSUE TITLE
Add lets encrypt support

### ISSUE THREAD

**Issue by geromueller** [jorisvink/kore#111]
It would be great if kore could automaically request and update SSL certificates from lets encrypt, like caddyserver can.

**Comment by jorisvink** [comment]
Hi,

I'm not sure support for this belongs in Kore.

I cannot see the workflow on how this would work nor how this would easily benefit Kore. There are tons of easy ways for getting a Lets Encrypt certificate that you can readily use.

Or am I missing something? What would the benefit of having this in Kore really be?

.joris

**Comment by jorisvink** [comment]
No response, closing.
