### ISSUE TITLE
SPDY and HTTP2.0 server support

### ISSUE THREAD

**Issue by anderflash** [jorisvink/kore#112]
Hi,

I was learning libmicrohttpd and I saw articles talking about SPDY and HTTP 2.0. I started searching libraries which support them. Is there any plan for kore to support them?

Thanks

**Comment by jorisvink** [comment]
Hi,

Kore used to support SPDY/3.1 but I deprecated and removed support for that a few weeks ago.

HTTP 2.0 is on my todo list.

.joris

**Comment by jorisvink** [comment]
Closing as question is answered.

**Comment by anderflash** [comment]
Thanks. It's an interesting and promising trend in web technology. Comparison between Kore HTTP/1.1 and Kore HTTP/2 will be a good performance analysis to promote the library.
