### ISSUE TITLE
kore: ./pgsql.so: ./pgsql.so: undefined symbol: kore_pgsql_ntuples

### ISSUE THREAD

**Issue by STashakkori** [jorisvink/kore#114]
I get the following issue when trying to do kore run in examples/pgsql or examples/pgsql-sync 
I have checked the header file in kore/includes and it has the appropriate prototype. please assist 

kore run
building pgsql (dev)
CFLAGS=-Wall -Wmissing-declarations -Wshadow -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wsign-compare -fPIC -I./src -I./src/includes -I/usr/local/include -DKORE_NO_TLS -g 
LDFLAGS=-shared 
pgsql built successfully!
[parent]: running on http://my_public_ip:8888
**kore: ./pgsql.so: ./pgsql.so: undefined symbol: kore_pgsql_ntuples**

**Comment by jorisvink** [comment]
Did you build Kore with PGSQL set to 1? :-)

**Comment by STashakkori** [comment]
Herp derp. I guess I should have read the docs huh? :)
