### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by wtfuzz** [jorisvink/kore#117]
Hi, I just came across Kore. Looks awesome!

Any plans to add HTTP/2 support? This would be an ideal framework to take advantage of the reduced protocol overhead in HTTP/2 given the performance of C.

**Comment by jorisvink** [comment]
Hi,

Yes, support for HTTP/2 is planned.

.joris

**Comment by jorisvink** [comment]
Closing as it has been answered.
