### ISSUE TITLE
Application context

### ISSUE THREAD

**Issue by wtfuzz** [jorisvink/kore#119]
Hi, I've started experimenting with Kore (love it so far!), but I was wondering if there is any recommended way of having an application context that can be accessed within the route handlers.

I have a service that exposes a control and data streaming API using nanomsg, and I'm trying to come up with a model to integrate a nanomsg endpoint client into a Kore application.

I could create/free sockets on every request, but that will cause a lot of connection overhead to the backend. And I would also like to be able to receive a stream of data from nanomsg, and send it to connected web socket clients.

It would be nice to have some kind of init callback that is called when the app starts so an application context could be initialized, and could then be retreived using an accessor from the http_request pointers, and connection pointers for web sockets.

This could allow app specific code to be called easily from the handlers.

**Comment by wtfuzz** [comment]
I should also ask, are the kore_websocket_*() functions reentrant/thread safe?

One way would be to start a thread per WS client in the connect callback, and pass the thread the struct connection *, receive data in that thread from nanomsg, process the data, and send it to clients with kore_websocket_send().

**Comment by wtfuzz** [comment]
Thanks.

I've been experimenting with nanomsg pub/sub in a thread, and writing the data out to a websocket client. You can get the underlying file descriptors from nanomsg sockets, so I'll look into leveraging the Kore event loop.

Here's the thread that's created per websocket connection.

One thing I had to do was call net_send_flush(), as it seems kore_websocket_send() was just queueing frames when called outside of a websocket callback.

```c
static void * _stream_thread(void *arg)
{
  uint8_t *buf;
  size_t buflen = 1024*1024*32;
  struct connection *c = (struct connection *)arg;
  client_t *client = (client_t *)c->hdlr_extra;
  int sock;

  sock = nn_socket(AF_SP, NN_SUB);
  assert (nn_setsockopt (sock, NN_SUB, NN_SUB_SUBSCRIBE, "", 0) >= 0);
  assert (nn_connect (sock, "tcp://127.0.0.1:9999") >= 0);

  buf = (void *)malloc(buflen);

  while(client->running == 1)
  {
    int bytes = nn_recv(sock, buf, buflen, 0);
    kore_websocket_send(c, WEBSOCKET_OP_BINARY, buf, 8192);
    net_send_flush(c);
  }
  return NULL;
}
```

**Comment by jorisvink** [comment]
I much more suggest doing this using the event loop. Having a thread per websocket connection for this is going to give you headaches.

If nanomsg provides a clean async interface and the socket (which it seems it does) doing this via the event loop is going to make your life a lot easier :-)

**Comment by jorisvink** [comment]
@wtfuzz Poke, did you get anywhere with this?

**Comment by wtfuzz** [comment]
I started to look through the pgsql and kore code at the event mechanism, but haven't had time this past week. I'll find some time in the coming days and keep you posted.

**Comment by jorisvink** [comment]
@wtfuzz Double poke :-)
