### ISSUE TITLE
MySQL support.

### ISSUE THREAD

**Issue by Aglezabad** [jorisvink/kore#120]
Hi Kore developers:

I'm trying to make a MySQL connector for this framework, because I want to use that database in my final project. I'm using the code of pgsql.c as a skeleton for MySQL, but I think that I need some help in this.

Here's my github repo for that. When it is finished, I will make a pull request to kore.
https://github.com/SDAIA/kore-mysql

Note: I'm using some tutorials of libmysqlclient library to make the list of methods for the connector. I think that you know more which functions are needed.

Best regards.

**Comment by jorisvink** [comment]
Hi,

That's cool.

Does the mysql api support both synchronous and asynchronous queries like pgsql?

.joris

**Comment by Aglezabad** [comment]
Hi Joris:
About synchronous and asynchronous queries, I don't know. I need to investigate that.

Regards.

**Comment by Aglezabad** [comment]
Hi:
I've searched about async queries in MySQL and I've found that.
http://jan.kneschke.de/projects/mysql/async-mysql-queries-with-c-api/

The author says that mysql_real_query function is synchronous but, there're two undocumented public functions that can make asynchronous queries. So, he thinks that is possible to do both types of queries.

**Comment by jorisvink** [comment]
Ok.

Please make a PR when your work becomes usable so I can take a closer look at it :-)

Until then I'm closing this issue.

**Comment by heibor** [comment]
I think using Lua to write the outer plugins may be a better choice. A MySQL driver can be wrote without the MySQL client library, such as https://github.com/openresty/lua-resty-mysql having done this. In the kore, only the core function is needed, such as a non-blocking socket connection to MySQL server.
