### ISSUE TITLE
Is there a REST API example available ?

### ISSUE THREAD

**Issue by rhulha** [jorisvink/kore#125]

**Comment by jorisvink** [comment]
Not in the examples directory.

.joris

**Comment by rhulha** [comment]
Would it be terribly difficult to add one please ?
I am currently evaluating C based web app frameworks and an example would go a long way.
Thanks for your great work!

**Comment by KrishnaPG** [comment]
+1 It would be very helpful.

Also, any performance benchmarks and architectural info could add value, especially with many server  platforms coming up with C++14, it is becoming difficult to differentiate the value-adds.

**Comment by jorisvink** [comment]
You can find some external benchmark on https://github.com/nanoant/WebFrameworkBenchmark

As for architectural information, see https://kore.io/doc/#architecture

The last part isn't updated with the newest changes for the upcoming 2.0 release which has introduced a key manager process that holds all your private keys so they are isolated from the worker processes.

**Comment by jorisvink** [comment]
As for the REST example, I will add one with the 2.0 release.

**Comment by KrishnaPG** [comment]
Thanks much for the benchmarks link. It makes things now more clear. I am indeed surprised (positively) to see Kore to be the one with highest throughput in that list. Good job.

My primary concern about Architecture is - the concurrency. 

- For example, does Kore address the C10K problem and what is its thread-to-client ratio?
- I see some _locks_ in the diagram. Recent high performance frameworks (such as, SeaStar and Wangle etc.) all rely on lock-free methods (and use thread message passing techniques)

But Lock-free methods do not perform well for low-load systems, while lock-based mechanisms do not scale well for high-load systems. How feasible Kore is in terms of replacing its locks with 'adaptive locking' (which is a lock-free mechanism by default, but as the load goes down it turns itself into a lock-based mechanism).

I am evaluating different REST sdks and here are few issues I found,
with CPPRest SDK: https://github.com/Microsoft/cpprestsdk/issues/174 
with CROW: https://github.com/ipkn/crow/issues/138

[CROW ](https://github.com/ipkn/crow) has this nice REST api syntax that is very tidy and nice - but concurrency wise it cannot scale.

[Served](https://github.com/datasift/served) also has nice REST api syntax (did not try it though)

**Comment by jorisvink** [comment]
> My primary concern about Architecture is - the concurrency.

The architecture speaks for itself regarding concurrency. Each worker takes turns on accepting new connections using an accept lock. This lock is in place to prevent a thundering herd problem when dealing with tons of worker processes. Each worker has a max number of connections it will accept before relinquishing the lock for others.

> For example, does Kore address the C10K problem and what is its thread-to-client ratio?

Yes it does. Kore does not have threads per client, you are thinking about the worker processes and those are configurable using workers, worker_max_connections and the worker_accept_threshold configuration options (see conf/kore.io.example for more detail).

Each worker multiplexes the sockets over either epoll() on Linux or kqueue() on the BSD's.

> I see some locks in the diagram

The lock is only used for serialising accepts across all workers as explained earlier. This lock is not going away as you *need* it to prevent a thundering herd problem which is going to cause you a lot of delay when your kernel is waking up tons of processes for nothing.

Your code you write in your Kore application effectively runs per worker. These processes can be tied to CPU's (which is done by default) or you can turn off affinity all together.

.joris

**Comment by jorisvink** [comment]
To continue, in effect the Kore workers are not going to block and keep performing I/O unless they reach their maximum configured number of connections, or your own application code starts blocking.

Properly scaling out means doing the required heavy lifting of figuring out the optimal configuration options for your application yourself. Kore will not stand in your way.

**Comment by jorisvink** [comment]
Note that there is also an http_request_limit option which limits the number of HTTP requests a worker process will perform before going back to dealing with I/O (even if other HTTP requests are still pending).

Hope I got all my bases covered now in this long and spread out answer.

**Comment by KrishnaPG** [comment]
Thank you for the detailed response. It is helpful. 

This worker "process" architecture is kind of interesting. I did not see anyone using this 'forked' architecture in the recent years. The last time I saw it was about 18+ years ago, in plain unix systems. 

But they were single core machines in those days, and mixing with 'affinity' is good technique for modern multi-core machines. I guess this is how you are achieving 'hot loading' the modules (since you have complete control over the process termination and restart with that module loaded inside it) - correct?

I have two questions on this:

-  How easy / difficult it is to make this multi-machine distributed? For example, can the worker processes be spawned on a cluster of machines (rather than on the same machine)? Achieves "Elasticity" / dynamic scaling of the servers
-  How much control we have over the modules? For example, for the REST API, can we have one worker take care of path "/api1" and other module (worker process) deal with "/api2" path?

**Comment by jaromil** [comment]
clusterization for serving assets is better achieved using shardcached https://github.com/Shardcached/shardcached

for computation I'm not sure what would be the best strategy, perhaps a sort of roundrobin at front which has information on the current load of each node.

different paths are assigned across dso modules, not workers.

**Comment by jorisvink** [comment]
> The last time I saw it was about 18+ years ago, in plain unix systems.

And several modern http servers including nginx.

> How easy / difficult it is to make this multi-machine distributed?

That won't happen by Kore as this is beyond its scope.

> How much control we have over the modules?

Tons as your module is loaded into the address space of the Kore binary you can have full control over the worker if you like.

> For example, for the REST API, can we have one worker take care of path "/api1" and other module (worker process) deal with "/api2" path?

Not easily as the workers simply accept a socket, read the request and then process it. However if you really want nothing is stopping you from passing the client sockets between worker processes using a unix socket. You'd have to teardown the connection on one worker and setup it up on the other one properly but it's totally doable.

**Comment by KrishnaPG** [comment]
Thanks. 

BTW, nginx is not modern :) It is from _pre-multicore_ era around 2002 / 2004, more than 12+ years old.

The first (widely available) commercial general purpose multi-cores from [Intel](https://en.wikipedia.org/wiki/Pentium_D) and [AMD](https://en.wikipedia.org/wiki/Athlon_64_X2) are in 2005

Anyway, I will try to look into the Kore source code to get better understanding of how things are happening.

**Comment by jorisvink** [comment]
Closing this as parts of the discussion no longer pertain to the original issue and the original author hasn't responded in > 14 days.

Note that an example like this will be included in the 2.0 release.
