### ISSUE TITLE
kore.io website certificate expired

### ISSUE THREAD

**Issue by ker2x** [jorisvink/kore#126]
This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox only connect to it securely. As a result, it is not possible to add an exception for this certificate.

kore.io uses an invalid security certificate. 
The certificate expired on 06/06/2016 01:59. The current time is 07/06/2016 11:01. 
Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by jorisvink** [comment]
Fixed, cheers for reminding me.
