### ISSUE TITLE
Question : how to debug

### ISSUE THREAD

**Issue by thibautd** [jorisvink/kore#129]
Hello,

I have a simple question, how do you debug (with a gdb for example) a kore application ? Do you know some IDE which support debugging kore application using gdb for example ?

Thanks.

**Comment by jaromil** [comment]
gdb works as usual ok `dlopen` shared libs which are visible by the command `info shared` so the usual workflow should apply here on your IDE of choice.

**Comment by thibautd** [comment]
Ok, for example if I want to use it in CLion, I will need to make my application a CMake project (and so, not using kore build). Is there some doc/README somewhere about this ?

Thanks for your help,

**Comment by jorisvink** [comment]
Just hook up gdb to the worker process you are trying to debug. If you build with debug symbols it'll just work.

> Is there some doc/README somewhere about this ?

I'm sure CMake has its own documentation on how to build linux shared libraries (which is what Kore modules are).

**Comment by thibautd** [comment]
> I'm sure CMake has its own documentation on how to build linux shared libraries (which is what Kore modules are).

My question was more related to the kore-related stuff, like generated assets, and how to integrate this in the build process.

**Comment by jorisvink** [comment]
> My question was more related to the kore-related stuff, like generated assets, and how to integrate this in the build process

The same way Kore does it, you'll want to read the file, create a new .c file containing an array of bytes for the file you've just read and include that generated .c file into your build process.

There's not really any shortcuts here unless Kore gets a genassets command or something that just converts those files in assets to their matching .c files. However this is easily done in a shell script or similar for other projects or build systems.

.joris

**Comment by jorisvink** [comment]
Closing, it's been 7 days since author reverted back.
