### ISSUE TITLE
Use of sys/param.h in assets generated file is not portable

### ISSUE THREAD

**Issue by thibautd** [jorisvink/kore#130]
Hello,

I'm trying to build the Generic example on Alpine Linux, and I got the following error:

```
alpine:~/kore/examples/generic# ../../kore run
building generic (dev)
CFLAGS=-Wall -Wmissing-declarations -Wshadow -Wstrict-prototypes -Wmissing-proto                                                               types -Wpointer-arith -Wcast-qual -Wsign-compare -fPIC -I./src -I./src/includes                                                                -I/media/sdcard/kore-bin/include -g
LDFLAGS=-shared
building asset params.html
building asset private.html
building asset style.css
building asset upload.html
building asset intro.jpg
building asset index.html
building asset private_test.html
compiling params.html
./.objs/params_html.c:4:1: error: unknown type name 'u_int8_t'
 u_int8_t asset_params_html[] = {
 ^
```

I don't understand why you are using types like `u_int8_t` insead of the standard types from `stdint.h` (`uint8_t`) ? Is there any reason ?

EDIT: I'm using Alpine Linux on a Raspberry Pi 3 (ARMHF).

**Comment by jorisvink** [comment]
What kind of libc is Alpine using?

**Comment by thibautd** [comment]
musl libc: https://www.musl-libc.org/

**Comment by jorisvink** [comment]
Well there you have it, musl libc its sys/param.h does not include sys/types.h which defines those types if _GNU_SOURCE or _BSD_SOURCE are defined.

I'll make sure this works for the upcoming release.

**Comment by thibautd** [comment]
Just curious, why do you want to use `sys/param.h` instead of `stdint.h` which seems to be more portable.

**Comment by jorisvink** [comment]
sys/param.h contains several useful macros, system defines and the likes for POSIX platforms while your stdint.h is a C99 header.

**Comment by jorisvink** [comment]
@thibautd This has been changed to use sys/types.h directly, which should define the correct types.

Please give it a go.

**Comment by thibautd** [comment]
Thank you, I will test this weekend !

**Comment by jaromil** [comment]
I hope it works, I was also wondering why not sys/types.h. And I'm also using libc-musl with kore, had to hack this myself a month ago and it created no problems in production.

**Comment by thibautd** [comment]
Thanks ;)
