### ISSUE TITLE
kore projects with C++ fail to run

### ISSUE THREAD

**Issue by nibroc** [jorisvink/kore#131]
It appears that a commit a while back changed it so that both C and C++ are compiled with the gcc front end. This is problematic since it means that C++ is not being linked against the C++ runtime. In other words, kore programs that use anything from libstdc++ (or libc++, etc) are likely to compile but not run.

As an example, you can modify the example to have a simple `std::cout` usage and then see that it will compile fine but fail to run:

> corbin@dev:~/kore/kore/examples/cpp$ kore build
> building cpp (dev)
> CFLAGS=-Wall -Wmissing-declarations -Wshadow -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wsign-compare -fPIC -I./src -I./src/includes -I/usr/local/include -g 
> LDFLAGS=-shared 
> compiling cpp.cpp
> cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
> cc1plus: warning: command line option ‘-Wmissing-prototypes’ is valid for C/ObjC but not for C++
> compiling example_class.cpp
> cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
> cc1plus: warning: command line option ‘-Wmissing-prototypes’ is valid for C/ObjC but not for C++
> cpp built successfully!
> corbin@dev:~/kore/kore/examples/cpp$ kore run
> building cpp (dev)
> CFLAGS=-Wall -Wmissing-declarations -Wshadow -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wsign-compare -fPIC -I./src -I./src/includes -I/usr/local/include -g 
> LDFLAGS=-shared 
> nothing to be done!
> [parent]: running on https://127.0.0.1:8888
> kore: ./cpp.so: ./cpp.so: undefined symbol: _ZSt4cout

Note also that CFLAGS is being used for both C and C++. This means that people are going to struggle to use different standards (i.e. `-std=c11` vs `-std=c++11`), and, as can be seen from the warnings, lots of options are not compatible across the two.

Anyway, I think that C++ needs to be compiled with a C++ compiler instead of a C compiler, and it would be awesome if the `cflags` configuration could have a corresponding `cppflags` option.

**Comment by jorisvink** [comment]
Great catch, I will poke at your PR immediately in the morning! Zzz now however :-)

**Comment by jorisvink** [comment]
I've gone ahead and merged your PR, excellent work thank you.
