### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by PauloMelo** [jorisvink/kore#137]
Hi Joris,

I don't really know if this is an issue on your side or mine, but It seems that the File Upload is not working. Using your example I get:
kore[5042]: [wrk 0]: failed to read from file
kore[5042]: [wrk 0]: kore_free(): magic boundary not found

there is a file uploaded to tmp_files with permissions 600 with the correct size.

Can you suggest any way to solve this?

Regards,
Paulo Melo

**Comment by PauloMelo** [comment]
Hi Joris,

some more info to help.

I've found that file->offset was not set to 0, so using http_file_rewind() solved partially the problem. Now the file is put in place, but the tmp_file is not unlinked and there is still an error that forces the worker to reset
kore[5712]: [wrk 0]: kore_free(): magic boundary not found
kore[5711]: [parent]: worker 0 (5712)-> status 256
kore[5711]: [parent]: worker 0 (pid: 5712) (hdlr: none) gone

Regards,
Paulo Melo
kore[5711]: [parent]: restarting worker 0

**Comment by jorisvink** [comment]
On what platform is this? Is this with the latest code?

**Comment by PauloMelo** [comment]
Yes it is with the latest code. I always to a git pull origin master on my mac.

**Comment by jorisvink** [comment]
I cannot reproduce this on my mac.

I've fixed offset not being correctly set to 0 but that was probably not related since you are still getting the kore_free() fatal.

If you do a kore run and attach lldb to the worker process and set a breakpoint for fatal and upload a new file, what is the backtrace that you get?

**Comment by jaromil** [comment]
I recommend using Vagrant. It greatly reduces the possibility for fuzzy behavior. That may help reproduce. And a test suite would be real good, see PR #27 currently stuck. ok sorry for intrusion :^)

**Comment by PauloMelo** [comment]
Hi Joris,

the backtrace is:
    frame #0: 0x00000001001b8ae6 kore`kore_free(ptr=0x000000010083a248) + 70 at mem.c:145
   142 	
   143 		mem = KORE_MEMINFO(ptr);
   144 		if (mem->magic != KORE_MEM_MAGIC)
-> 145 			fatal("kore_free(): magic boundary not found");
   146 	
   147 		len = KORE_MEMSIZE(ptr);
   148 		addr = (u_int8_t *)ptr - sizeof(size_t);
(lldb) bt
* thread #1: tid = 0x608cd, 0x00000001001b8ae6 kore`kore_free(ptr=0x000000010083a248) + 70 at mem.c:145, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
  * frame #0: 0x00000001001b8ae6 kore`kore_free(ptr=0x000000010083a248) + 70 at mem.c:145
    frame #1: 0x00000001001c07c3 kore`http_request_free(req=0x00000001003fda60) + 1251 at http.c:456
    frame #2: 0x00000001001c0275 kore`http_process + 101 at http.c:282
    frame #3: 0x00000001001be00b kore`kore_worker_entry(kw=0x00000001003cf008) + 763 at worker.c:388
    frame #4: 0x00000001001bdd05 kore`kore_worker_spawn(id=0, cpu=0) + 325 at worker.c:152
    frame #5: 0x00000001001bdb81 kore`kore_worker_init + 529 at worker.c:122
    frame #6: 0x00000001001b08cf kore`kore_server_start + 191 at kore.c:424
    frame #7: 0x00000001001b05bd kore`main(argc=0, argv=0x00007fff5fa50ca8) + 797 at kore.c:217
    frame #8: 0x00007fff918655ad libdyld.dylib`start + 1

**Comment by jorisvink** [comment]
That's odd.

Is this the exact code from the upload example? Have you rebuilt everything from scratch and tested if the problem then still persists?

What is the size of the file you are uploading? I am trying to reproduce this but am failing.

The backtrace you posted indicates that the filename member somehow got mangled.

**Comment by PauloMelo** [comment]
It's a 6Mb file that is being uploaded. I had to rebuild everything to the latest version and use the dsymutil in order to be able to attach the lldb and put a breakpoint. The sample code that I am using is an exact copy of the example, but integrated on my latest app development.
The only diference is the filename is being changed by the app.

I've solved it by kore_free(file->filename) and file->filename = kore_strdup(new_name)

Thanks for the help.

**Comment by jorisvink** [comment]
Can you help me understand what you were trying to do in your app? Where you changing the filename pointer to something manually allocated via malloc()?

.joris

**Comment by PauloMelo** [comment]
Yes, that was the case. 
I'm building a mobile app where the user upload some photos related to some data. On the server, kore takes that information, and disregards the name supplied by the mobile app and attributes according to a special naming convention. 
The error was being created by an overflow disrupting your kore_malloc. I solved it by correctly freeing what was supplied in the POST call and recreating it with my new_name.

Paulo

**Comment by jorisvink** [comment]
Ok, that makes perfect sense now by kore_free() was complaining about why the magic value was thrashed :-)
