### ISSUE TITLE
implementing "infinite" loop

### ISSUE THREAD

**Issue by petrw** [jorisvink/kore#138]
Hello, 

thanks for really neat framework. I would like to use it for implementing simple mjpeg streamer but as far i know, there is no way to do it. There is example of "infinite" loop in python used for serving "multipart/x-mixed-replace" responses:

<pre>
self.send_response(200)
self.send_header('Content-type','multipart/x-mixed-replace; boundary=--jpgboundary')
self.end_headers()

while True:
	try:
		global frameno
		print frameno
		frameno += 1

		jpg = Image.open("1.jpg" if frameno % 2 else "2.jpg")

		tmpFile = StringIO.StringIO()
		jpg.save(tmpFile,'JPEG')
		self.wfile.write("--jpgboundary")

		self.send_header('Content-type','image/jpeg')
		self.send_header('Content-length',str(tmpFile.len))
		self.end_headers()
		jpg.save(self.wfile,'JPEG')

		time.sleep(1)
	except KeyboardInterrupt:
		break
</pre>

Is currently possible to implement such thing with KORE? I was looking on streaming and task example but neither of them looks like way to go. Thank you for your feedback.

**Comment by jorisvink** [comment]
You can do something similar yes. It would require a task to be setup when the normal HTTP request comes in, tie said request to the task and set HTTP_REQUEST_NO_CONTENT_LENGTH in the flags member of the http_request before sending the first 200 response with http_response().

Your task would be doing the looping and sending it over the task channel back to the page handler which is scheduled to run everytime there is new data on the task channel.

See the sse (server side events) example for HTTP_REQUEST_NO_CONTENT_LENGTH.

**Comment by petrw** [comment]
Thanks for response, will look into that.
