### ISSUE TITLE
Digest Authentication in Kore

### ISSUE THREAD

**Issue by mankash** [jorisvink/kore#139]
Hello - 

Does kore support digest authentication? If so, what APIs are used for the same.

Thanks

**Comment by jorisvink** [comment]
Hey,

No it does not. However if you really want this you can use authentication blocks to implement this yourself:

```
validator v_digest_auth function your_digest_checker

authentication digest_auth {
        authentication_type request
        authentication_validator v_digest_auth
}

domain * {
        ....
        page / serve_index digest_auth
}
```

```
int your_digest_checker(struct http_request *req, void *unused);

Return KORE_RESULT_OK if auth was OK, or KORE_RESULT_ERROR if it failed.
```

That'll call your_digest_checker() callback when the **/** page is hit and before its callback is called.

From there you can grab the header you want with *http_request_header* and do the required magic to validate it.

Hope this helps.

.joris

**Comment by jorisvink** [comment]
Closing issue, no more comments from author.
