### ISSUE TITLE
error: 'MAP_ANONYMOUS' undeclared on macOS <= 10.9

### ISSUE THREAD

**Issue by ilovezfs** [jorisvink/kore#140]
I'm upgrading the Homebrew formula for kore from 1.2.3 to 2.0.0 (https://github.com/Homebrew/homebrew-core/pull/3503). The build currently fails on macOS <= 10.9 (Mavericks), with the error
```
src/pool.c:151:6: error: use of undeclared identifier 'MAP_ANONYMOUS'
            MAP_ANONYMOUS | MAP_PRIVATE, -1, 0);
            ^
1 error generated.
make: *** [obj/pool.o] Error 1
make: *** Waiting for unfinished jobs....

```

Full log: https://gist.github.com/ilovezfs/c7cf3a3da96fc33f6cc48fb53efffe3b

Is support for <= Mavericks intentionally being dropped?

**Comment by jorisvink** [comment]
Thanks for taking your time to upgrade the homebrew formula!

Yeah I do not expect this to run on those versions anymore, perhaps I should've made that more clear in the changelog.

.joris

**Comment by ilovezfs** [comment]
@jorisvink No problem. I've shipped it with the Mavericks bottle dropped, and the formula restricted to >= Yosemite. Just wanted to make sure that was consistent with upstream intentions.

**Comment by gromgit** [comment]
That's a pity, since AFAIK `MAP_ANONYMOUS` post-Mavericks is just a renaming of `MAP_ANON`.

Patch for pre-Yosemite machines, for those who're still using them: https://gist.github.com/gromgit/2a9f210a2975631bc34c0a2557c9cb84
