### ISSUE TITLE
SSL_CTX_use_certificate_chain_file((null)): error:0200100E:system library:fopen:Bad address

### ISSUE THREAD

**Issue by bi4o4ek** [jorisvink/kore#141]
Hello!
I made kore with NO_TLS ("make NOTLS=1"), ran "make install" and "kore create hello"

Then I added this to conf/build.conf to build single_binary:
single_binary=yes
kore_source=/home/bi4o4ek/kore

I tried "kore build", but it ask me to add "ldflags=-lssl -lcrypto" to conf/build.conf. Ok, I did it.
"kore build" successfuly finished.

Now command "./hello" returns the error to me.
"hello: SSL_CTX_use_certificate_chain_file((null)): error:0200100E:system library:fopen:Bad address"

I guess, binary tries to open certificate-file with name "null".

Tell me please, how to build single_binary without TLS?

**Comment by jorisvink** [comment]
You are missing two things:

1) add a kore_flavor = NOTLS=1 right before your kore_source
2) to cflags add -DKORE_NO_TLS

That should give you the desired result.

.joris

**Comment by bi4o4ek** [comment]
Same error(

My conf/build:
`bi4o4ek@ppl-bykanov-0401420:~/kore/hello$ cat conf/build.conf | grep -v '\#'

single_binary=yes
kore_source=/home/bi4o4ek/kore
kore_flavor = NOTLS=1

cflags=-DKORE_NO_TLS
cflags=-Wall -Wmissing-declarations -Wshadow
cflags=-Wstrict-prototypes -Wmissing-prototypes
cflags=-Wpointer-arith -Wcast-qual -Wsign-compare

cxxflags=-Wall -Wmissing-declarations -Wshadow
cxxflags=-Wpointer-arith -Wcast-qual -Wsign-compare
ldflags=-lssl -lcrypto

dev {
	cflags=-g
	cxxflags=-g
}
`

run output:
`bi4o4ek@ppl-bykanov-0401420:~/kore/hello$ kore run
building kore (/home/bi4o4ek/kore)
using flavor NOTLS=1
building hello (dev)
CFLAGS=-DKORE_NO_TLS -Wall -Wmissing-declarations -Wshadow -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wsign-compare -fPIC -I./src -I./src/includes -I/usr/local/include -DKORE_NO_TLS -g -DKORE_SINGLE_BINARY
LDFLAGS=-lssl -lcrypto 
adding config ./conf/hello.conf
hello built successfully!
[parent]: running on https://127.0.0.1:10080
ignoring "load" on line 4
hello: SSL_CTX_use_certificate_chain_file((null)): error:0200100E:system library:fopen:Bad address
`

**Comment by jorisvink** [comment]
Do a kore clean first. Switching flavors requires a full rebuild and judging from your output it didn't do that.

**Comment by bi4o4ek** [comment]
Success!
Thank you very much!

Could you add this info to documentation?
Becouse common task is building http-only single binary as backend for some balancer (nginx).

**Comment by jorisvink** [comment]
Glad to see its fixed :-)

Yeah I'll add this under the documentation soon enough.
