### ISSUE TITLE
http_argument_get_string not found key

### ISSUE THREAD

**Issue by joseluis8906** [jorisvink/kore#145]
http_argument_get_string function doesn't find the text form fields, only work with upload files form-data, but doesn't work with text form-data.

**Comment by jorisvink** [comment]
Did you call http_populate_post() before using http_argument_get_string()?

.joris

**Comment by joseluis8906** [comment]
Data is a multipart form data, I need upload a file with custom name based on user document type and document, the http_body request is like this:

-------"boundary"
Content-Disposition: form-data; name="document_type"

c.c
-------"boundary"
Content-Disposition: form-data; name="document"

1098671330
-------"boundary"
Content-Disposition: form-data; name="userfile"; filename="(name of file)"

$file data
-------"boundary"--

In my kore code I have:
http_populate_multipart_form (req);
file_look_up (....
still here all ok but:

char *document_type;
http_argument_get_string (req, "document_type", &document_type); --> error not found key "document_type" and with "document" key same story.

my english is basic medium, I hope I explained, google traductor help me

**Comment by jorisvink** [comment]
Have you created a param {} block for that handler? Check the example configuration for how to do this.

Basically you need validators for those kind of fields, and if the value given doesn't match those kore strips them away.

**Comment by joseluis8906** [comment]
Yes I do, in my app config file I have like this:

static /backend/upload_file/  upload_file

params post /backend/upload_file/ {
    validate    document_type    v_func_params
    validate    document ....... etc
}

but error persist.

**Comment by jorisvink** [comment]
Hey @joseluis8906 sorry for the delay, I'll look into this today.

**Comment by jorisvink** [comment]
I can't reproduce this.

Are you sure your param validators for document_type are actually correct and the argument isn't being stripped out? :-)

(PS: Sorry for me being slow)

**Comment by jorisvink** [comment]
No response from author, closing.
