### ISSUE TITLE
websockets break build when NOTLS=1

### ISSUE THREAD

**Issue by jaromil** [jorisvink/kore#147]
In websockets.c:L94 some functions provided by OpenSSL are called, but when kore is compiled with `NOTLS=1` they bail to error as the library is not linked.

There is an ambiguity in `NOTLS` since that flag is used to deactivate the requirement of TLS certificates for https, but that is ortogonal to websockets support.

**Comment by jaromil** [comment]
Nevermind this one. Adding `-lssl` and `-lcrypto` explicitly to cflags in build.conf fixes it.
It was enough to read twice the commit message documenting this change.
There should be however some mention in the documentation about this single_file function....

**Comment by jorisvink** [comment]
Agreed. That part is somewhat missing.

I will update the documentation.

**Comment by jorisvink** [comment]
Closing this issue as the main principle problem has been resolved.
