### ISSUE TITLE
How to build single statically linked binary

### ISSUE THREAD

**Issue by bi4o4ek** [jorisvink/kore#148]
How to build single statically linked binary

**Comment by jorisvink** [comment]
You don't, can't and shouldn't :-)

**Comment by jaromil** [comment]
w0t? I think he means the new `single_binary` option. I'll provide a new example for it as PR

**Comment by jorisvink** [comment]
Yes. He does.

But that does not produce a **static** binary.

**Comment by jaromil** [comment]
Oh yes, true, its not fully static

**Comment by jaromil** [comment]
I've anyway packed together the PR #149 and renamed accordingly 'single binary build example'.

**Comment by bi4o4ek** [comment]
Why I don't, can't and shouldn't?
We are always use single static binaries in production.
This is better then docker images.
We build binary and deploy it to testing, then prestable and production. So it is no needed to install any extra packages to servers.

**Comment by jorisvink** [comment]
Besides missing ASLR in static binaries Kore requires dlopen() even when building as a single binary.

I get you when you say static binaries are easier, but I disagree they are better then dynamic ones.

Officially I will never support building static binaries with Kore, but I guess nothing stops you from fiddling with ldflags in the build.conf file.

**Comment by jaromil** [comment]
> Kore requires dlopen() even when building as a single binary
Why is that? would be useful to know.
I also use musl-libc in some situations, but not yet with Kore.

**Comment by jorisvink** [comment]
> Why is that? would be useful to know.

Kore originally loaded DSO files that were driven by a configuration file with names of functions to map to URI's.

When I introduced single binary support I did not want to rewrite most of the core functionality so instead opted for Kore to dlopen() on itself in order for the existing config code (that uses dlsym() to find the symbols for the functions) to work.

**Comment by jaromil** [comment]
thanks for the explanation, makes sense to me.
