### ISSUE TITLE
Debugging hdrl - best practices

### ISSUE THREAD

**Issue by novcn** [jorisvink/kore#150]
When there's a runtime error I see it thrown in the form of:
```hdlr foo has caused 1 error(s)```
Is there a best practice for dealing with such errors? In other words, is there a way to print out a stack trace of the runtime error?
I attempted gdb but my breakpoint of `foo` was not honored.

**Comment by jorisvink** [comment]
No Kore does not print out stack traces at runtime.

Attaching with gdb shouldn't be hard though: Start your application (using 1 worker process helps in this case) and attach to the worker process that will get the next connection (gdb -p).

Then break on your hdlr function and throw a connection towards it.

**Comment by jorisvink** [comment]
@novcn Saw your comments on IRC but wasn't online last night so happy you made an issue asking!

**Comment by novcn** [comment]
Thanks @jorisvink I'm sure this will save me in the future!

Initially I ran into
```ptrace: Operation not permitted``` 
In gdb, my fix, incase any one else runs into this was to
```echo "0" | sudo tee /proc/sys/kernel/yama/ptrace_scope```
which worked running Arch Linux.
