### ISSUE TITLE
Invoke platform alternatives

### ISSUE THREAD

**Issue by yorickdewid** [jorisvink/kore#158]
Most UNIX like systems use platform alternatives for C/C++ compilers and related tools. This allows for other compilers as well without having to change the code. For example BSD variants may not always default to GCC.

```c
static char			*compiler_c = "gcc";
static char			*compiler_cpp = "g++";
static char			*compiler_ld = "gcc";
```

Should be

```c
static char			*compiler_c = "cc";
static char			*compiler_cpp = "c++";
static char			*compiler_ld = "ld";
```

**Comment by jorisvink** [comment]
Absolutely, feel free to make a PR for this.
