### ISSUE TITLE
for NOTLS=1 needed -lcrypto in ldflags

### ISSUE THREAD

**Issue by ramok** [jorisvink/kore#161]
kore use SHA1_init() and related function in case of NOTLS=1 for building single_binary

> $ kore create test
created test/src/test.c
created test/conf/test.conf
created test/conf/build.conf
created test/.gitignore
created test/dh2048.pem
test created successfully!
note: do NOT use the created DH parameters/certificates in production
> $ cd test
> $ echo 'single_binary=yes' >> conf/build.conf
> $ echo 'kore_source = ../kore' >> conf/build.conf
> $ echo 'kore_flavor=NOTLS=1' >> conf/build.conf
> $ kore build
> building kore (../kore)
> using flavor NOTLS=1
> building test (dev)
> CFLAGS=-Wall -Wmissing-declarations -Wshadow -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wsign-compare -fPIC -I./src -I./src/includes -I/usr/include -I/usr/include/postgresql -g -DKORE_SINGLE_BINARY
> LDFLAGS=
> adding config ./conf/test.conf
> building asset builtin_kore.conf
> compiling test.c
> compiling builtin_kore.conf
> ./.objs/cli.o: In function `cli_build_asset':
> cli.c:(.text+0x1c4c): undefined reference to `SHA1_Init'
> cli.c:(.text+0x1c60): undefined reference to `SHA1_Update'
> cli.c:(.text+0x1c70): undefined reference to `SHA1_Final'
> ./.objs/websocket.o: In function `kore_websocket_handshake':
> websocket.c:(.text+0x244): undefined reference to `SHA1_Init'
> websocket.c:(.text+0x255): undefined reference to `SHA1_Update'
> websocket.c:(.text+0x260): undefined reference to `SHA1_Final'
> collect2: error: ld returned 1 exit status
> kore build: subprocess trouble, check output

this will fix problem
> $ echo 'ldflags=-lcrypto' >> conf/build.conf
> $ kore build
> building kore (../kore)
> using flavor NOTLS=1
> building test (dev)
> CFLAGS=-Wall -Wmissing-declarations -Wshadow -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wsign-compare -fPIC -I./src -I./src/includes -I/usr/include -I/usr/include/postgresql -g -DKORE_SINGLE_BINARY
> LDFLAGS=-lcrypto
> adding config ./conf/test.conf
> test built successfully!

but i think -lcrypto must be added by default

**Comment by ramok** [comment]
Ok, at least it's must be in documentation that single builds need to ldflags=-lcrypto. Or in build.conf in commented example for single build.

**Comment by jorisvink** [comment]
Yes, I will need to add it there I'm aware :)

**Comment by No9** [comment]
@ramok Thanks for this had me stuck for a while too I also found you need to add 
```
chroot  /folder/location
runas username
```
to the project.conf too

@jorisvink Would you take a PR to update the build.conf and the project.conf with commented out config as suggested?

**Comment by jaromil** [comment]
how about removing the dependency from libcrypto alltogether? is it only about the SHA1 function?

**Comment by jorisvink** [comment]
@No9 Only required when you want to launch something into production, for testing purposes you can get away with running kore run or start the process with -frn.

**Comment by jorisvink** [comment]
Closing, I'll include this in the documentation.
