### ISSUE TITLE
JSON Responses. 

### ISSUE THREAD

**Issue by whitebook** [jorisvink/kore#162]
Hello. 

I was wondering what you would suggest to return json responses?

And if you have any examples how to do it...

Thanks.

**Comment by jorisvink** [comment]
```

struct kore_buf response;

kore_buf_init(&response, 128);
kore_buf_appendf(&response, "{\”status\": 200}");
http_response(req, HTTP_STATUS_OK, response.data, response.offset);

kore_buf_cleanup(&response);
```

comes to mind.

**Comment by whitebook** [comment]
Thanks for the simple example. 
I was hoping to learn how to serialize a Postgres resultset to a JSON response?
Is it a matter of just constructing the result set into a JSON formatted string?

I was hoping there would be some library that would be able to help with that?

**Comment by jorisvink** [comment]
Use row_to_json() or similar in your query.

see https://www.postgresql.org/docs/9.5/static/functions-json.html

**Comment by whitebook** [comment]
Thanks I will try it. 

Appreciate your assistance.
