### ISSUE TITLE
Incorrect host on IPv6

### ISSUE THREAD

**Issue by yorickdewid** [jorisvink/kore#164]
When bound to `::` and some port, the application can be accessed in the browser via `http://[::]:<port>/` but then the host member of the `struct http_request` only reports a single `[` char. Somehow the host is wrongly sub-stringed when the application is accessed this way.

Most likely is the problem caused by `htttp.c:204`

**Comment by jorisvink** [comment]
Actually this is caused by http.c:618 and the way the host header is split using kore_split_string.

I'll fix it.

**Comment by jorisvink** [comment]
Give the latest a spin and let me know if it helps you out.

**Comment by yorickdewid** [comment]
Done & Gone!
