### ISSUE TITLE
Feature request: connection hook

### ISSUE THREAD

**Issue by yorickdewid** [jorisvink/kore#165]
Right now the application I am using needs a hack to setup some primitives in order to process the request. This hack makes sure some setup routines in the application are initialized and cleaned up just before the response is sent.

A much better solution would be to have a connection hook. This hook can be set via the config or application itself. But on every new connection the function is called, and an equivalent function is called when the connection is removed from the pool.

**Comment by jorisvink** [comment]
You can actually do this using the bind directive.

```
bind ip host callback
```

This would call the callback function for every new connection, but requires you to mark the connection as established yourself, set the proto yourself and queue up a read request yourself.

For example - having a callback for a normal connection that you'd still be serving HTTP towards:

```
void
callback(struct connection *c)
{
        c->proto = CONN_PROTO_HTTP;
        c->state = CONN_STATE_ESTABLISHED;
        net_recv_queue(c, http_header_max,
            NETBUF_CALL_CB_ALWAYS, http_header_recv);
}
```

**Comment by jorisvink** [comment]
Additionally you can set c->disconnect to point to a function that is called when the connection is being removed from kore.

**Comment by yorickdewid** [comment]
Yes very well, tough I ran into an issue. The `&modules` in module is empty and thus `kore_module_getsym` returns `NULL` causing an config parsing error. The reason why is not too hard to find since the module list is loaded after the `load` command. Moving `bind ..` below the load solves the problem, but none of the example configurations reflect this :)

**Comment by jorisvink** [comment]
Ah yes I forgot to mention that. I'll make sure its reflection next release somewhere.

**Comment by yorickdewid** [comment]
Case closed
