### ISSUE TITLE
Proposal: Signal parent process

### ISSUE THREAD

**Issue by yorickdewid** [jorisvink/kore#167]
At this moment, you can only send signals to the current process. It be a great idea if you could send signals to the parent process as well. Of course you can seek the parent PID, and then send a signal. What I propose is an interface like `void kore_parent_signal(int sig)`.

The reason for this proposal is the lack of worker-to-parent communication. I would like to send SIGQUIT to the parent in order to stop the current instance. I can create a pull request featuring this idea.

**Comment by jorisvink** [comment]
You could always use the built-in messaging framework to allow workers to send messages to the parent.

see src/msg.c.

**Comment by yorickdewid** [comment]
But I don't see how the parent is going to act on that.

**Comment by jorisvink** [comment]
The parent needs a callback to be installed for a specific channel. I do this for the accesslog.

If you are simply going to signal the parent to die then yes the message framework won't help you unless you add the glue for it. If you want the parent to do things based on the workers sending it something avoid signals all together and just use the message framework.

**Comment by jorisvink** [comment]
Also the parent and workers may run as different users so sending a signal won't actually help you.

**Comment by yorickdewid** [comment]
Simple usecase: unittest. A script runs some of the URI's on the kore framework and asserts its output. Eventually it would request a URI causing the worker to SIGQUIT the parent. Now I know there are many ways to accomplish that, but quitting the process from inside has a better chance of immediate termination in a Docker environment.

**Comment by jorisvink** [comment]
That makes sense.

What you are really looking for then is a way for the workers to signal the parent to exit. I wouldn't mind a message callback from the workers to the parent that tells the parent to shutdown and thus take everything with it.

This way we can avoid signals and have a clear defined path of sending commands over the msg framework.

**Comment by yorickdewid** [comment]
See #168 

Better solution would be to have a `kore test` framework builtin. I guess thats no short term solution :)

**Comment by yorickdewid** [comment]
Fixed in #168
