### ISSUE TITLE
Invalid IPv6 host

### ISSUE THREAD

**Issue by yorickdewid** [jorisvink/kore#169]
When accessing the application via IPv6 address, the host reports only part of the IPv6 address, while including a `[`. For example:

On `https://[2a00:7c8:ff:fe07:cccc]/myapp` the host shows: `[2a00:7c8:ff:fe07`, note the missing last 16bit field.

**Comment by jorisvink** [comment]
Yeah the parsing isn't optimal in the http_request_new() function.

It's basically explicitly cutting off everything after the last ':' under the assumption it is the port if present.

I'm aware of this and this will be fixed soon.

**Comment by yorickdewid** [comment]
I had a good idea of what went wrong. It is not that big of a problem since apps will always run over a domain name instead of an address on production.

**Comment by jorisvink** [comment]
Yup, but it will be fixed anyway.

**Comment by yorickdewid** [comment]
Workin
