### ISSUE TITLE
Params parser delete '=' from body request

### ISSUE THREAD

**Issue by joseluis8906** [jorisvink/kore#174]
Hi, I have to send "SELECT \"Name\" FROM \"Account\" WHERE \"Code\"='11'"; to the server but the kore parser deletes '=' from the body of query.

**Comment by jorisvink** [comment]
How are you sending the data? As a plain body or URL encoded?

**Comment by joseluis8906** [comment]
I was able to solve it, just I encoded URL special characters. :)

**Comment by jorisvink** [comment]
Yeah that's what I was wondering. Great.
