### ISSUE TITLE
examples/generic/src/ missing assets.h

### ISSUE THREAD

**Issue by benwills** [jorisvink/kore#175]
https://github.com/jorisvink/kore/blob/master/examples/generic/src/example.c
... attempts to #include "assets.h"

assets.h is not included in the most recent source, or the 2.0.0 release.

**Comment by jorisvink** [comment]
It's not missing, assets.h is auto generated by 'kore build'.


.joris

**Comment by benwills** [comment]
Ah. Thanks. I'd tried 'kore build' with the most recent source, which throws errors. But it looks like it's compiling on the 2.0.0 release.

Thanks.

**Comment by jorisvink** [comment]
What kind of errors did you encounter? And was it with latest master?

**Comment by benwills** [comment]
This is from the latest master, downloaded today.

> $ kore build
building generic (dev)
CFLAGS=-Wall -Wmissing-declarations -Wshadow -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wsign-compare -fPIC -I./src -I./src/includes -I/usr/local/include -g 
LDFLAGS=-shared 
building asset intro.jpg
building asset private.html
building asset style.css
building asset upload.html
building asset private_test.html
building asset params.html
building asset index.html
compiling example.c
./src/example.c: In function ‘serve_style_css’:
./src/example.c:88:31: error: ‘asset_mtime_style_css’ undeclared (first use in this function)
  if (tstamp != 0 && tstamp <= asset_mtime_style_css) {
                               ^
./src/example.c:88:31: note: each undeclared identifier is reported only once for each function it appears in
./src/example.c:96:27: error: ‘asset_style_css’ undeclared (first use in this function)
   http_response(req, 200, asset_style_css, asset_len_style_css);
                           ^
./src/example.c:96:44: error: ‘asset_len_style_css’ undeclared (first use in this function)
   http_response(req, 200, asset_style_css, asset_len_style_css);
                                            ^
./src/example.c: In function ‘serve_index’:
./src/example.c:106:26: error: ‘asset_index_html’ undeclared (first use in this function)
  http_response(req, 200, asset_index_html, asset_len_index_html);
                          ^
./src/example.c:106:44: error: ‘asset_len_index_html’ undeclared (first use in this function)
  http_response(req, 200, asset_index_html, asset_len_index_html);
                                            ^
./src/example.c: In function ‘serve_intro’:
./src/example.c:115:26: error: ‘asset_intro_jpg’ undeclared (first use in this function)
  http_response(req, 200, asset_intro_jpg, asset_len_intro_jpg);
                          ^
./src/example.c:115:43: error: ‘asset_len_intro_jpg’ undeclared (first use in this function)
  http_response(req, 200, asset_intro_jpg, asset_len_intro_jpg);
                                           ^
./src/example.c: In function ‘serve_file_upload’:
./src/example.c:150:21: error: ‘asset_len_upload_html’ undeclared (first use in this function)
  b = kore_buf_alloc(asset_len_upload_html);
                     ^
./src/example.c:151:21: error: ‘asset_upload_html’ undeclared (first use in this function)
  kore_buf_append(b, asset_upload_html, asset_len_upload_html);
                     ^
./src/example.c: In function ‘serve_params_test’:
./src/example.c:253:21: error: ‘asset_len_params_html’ undeclared (first use in this function)
  b = kore_buf_alloc(asset_len_params_html);
                     ^
./src/example.c:254:21: error: ‘asset_params_html’ undeclared (first use in this function)
  kore_buf_append(b, asset_params_html, asset_len_params_html);
                     ^
./src/example.c: In function ‘serve_private’:
./src/example.c:313:26: error: ‘asset_private_html’ undeclared (first use in this function)
  http_response(req, 200, asset_private_html, asset_len_private_html);
                          ^
./src/example.c:313:46: error: ‘asset_len_private_html’ undeclared (first use in this function)
  http_response(req, 200, asset_private_html, asset_len_private_html);
                                              ^
./src/example.c: In function ‘serve_private_test’:
./src/example.c:323:26: error: ‘asset_private_test_html’ undeclared (first use in this function)
  http_response(req, 200, asset_private_test_html,
                          ^
./src/example.c:324:6: error: ‘asset_len_private_test_html’ undeclared (first use in this function)
      asset_len_private_test_html);
      ^
kore build: subprocess trouble, check output

**Comment by jorisvink** [comment]
Well that's no good. Can you try another example that has assets? Does that build on your system?

If so I broke the generic one with a commit and run before I left for travels which means I'll fix it when I get back from traveling next week.

**Comment by benwills** [comment]
I just ran `kore build` on each of the example applications on the most recent master. I didn't run it on the json or postgres applications. Below is the output of any of the applications that threw a warning or error.

Let me know if there's anything else you think I can do to help.


##############################################################################
Not run:
* jsonrpc
* json_yajl
* pgsql
* pgsql-sync
* python-pgsql


##############################################################################
kore-master/examples/generic$ kore build
building generic (dev)
CFLAGS=-Wall -Wmissing-declarations -Wshadow -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wsign-compare -fPIC -I./src -I./src/includes -I/usr/local/include -g 
LDFLAGS=-shared 
building asset intro.jpg
building asset private.html
building asset style.css
building asset upload.html
building asset private_test.html
building asset params.html
building asset index.html
compiling example.c
./src/example.c: In function ‘serve_style_css’:
./src/example.c:88:31: error: ‘asset_mtime_style_css’ undeclared (first use in this function)
  if (tstamp != 0 && tstamp <= asset_mtime_style_css) {
                               ^
./src/example.c:88:31: note: each undeclared identifier is reported only once for each function it appears in
./src/example.c:96:27: error: ‘asset_style_css’ undeclared (first use in this function)
   http_response(req, 200, asset_style_css, asset_len_style_css);
                           ^
./src/example.c:96:44: error: ‘asset_len_style_css’ undeclared (first use in this function)
   http_response(req, 200, asset_style_css, asset_len_style_css);
                                            ^
./src/example.c: In function ‘serve_index’:
./src/example.c:106:26: error: ‘asset_index_html’ undeclared (first use in this function)
  http_response(req, 200, asset_index_html, asset_len_index_html);
                          ^
./src/example.c:106:44: error: ‘asset_len_index_html’ undeclared (first use in this function)
  http_response(req, 200, asset_index_html, asset_len_index_html);
                                            ^
./src/example.c: In function ‘serve_intro’:
./src/example.c:115:26: error: ‘asset_intro_jpg’ undeclared (first use in this function)
  http_response(req, 200, asset_intro_jpg, asset_len_intro_jpg);
                          ^
./src/example.c:115:43: error: ‘asset_len_intro_jpg’ undeclared (first use in this function)
  http_response(req, 200, asset_intro_jpg, asset_len_intro_jpg);
                                           ^
./src/example.c: In function ‘serve_file_upload’:
./src/example.c:150:21: error: ‘asset_len_upload_html’ undeclared (first use in this function)
  b = kore_buf_alloc(asset_len_upload_html);
                     ^
./src/example.c:151:21: error: ‘asset_upload_html’ undeclared (first use in this function)
  kore_buf_append(b, asset_upload_html, asset_len_upload_html);
                     ^
./src/example.c: In function ‘serve_params_test’:
./src/example.c:253:21: error: ‘asset_len_params_html’ undeclared (first use in this function)
  b = kore_buf_alloc(asset_len_params_html);
                     ^
./src/example.c:254:21: error: ‘asset_params_html’ undeclared (first use in this function)
  kore_buf_append(b, asset_params_html, asset_len_params_html);
                     ^
./src/example.c: In function ‘serve_private’:
./src/example.c:313:26: error: ‘asset_private_html’ undeclared (first use in this function)
  http_response(req, 200, asset_private_html, asset_len_private_html);
                          ^
./src/example.c:313:46: error: ‘asset_len_private_html’ undeclared (first use in this function)
  http_response(req, 200, asset_private_html, asset_len_private_html);
                                              ^
./src/example.c: In function ‘serve_private_test’:
./src/example.c:323:26: error: ‘asset_private_test_html’ undeclared (first use in this function)
  http_response(req, 200, asset_private_test_html,
                          ^
./src/example.c:324:6: error: ‘asset_len_private_test_html’ undeclared (first use in this function)
      asset_len_private_test_html);
      ^
kore build: subprocess trouble, check output


##############################################################################
kore-master/examples/nohttp$ kore build
building nohttp (dev)
CFLAGS=-Wall -Wmissing-declarations -Wshadow -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wsign-compare -fPIC -I./src -I./src/includes -I/usr/local/include -g 
LDFLAGS=-shared 
compiling nohttp.c
./src/nohttp.c: In function ‘connection_recv_data’:
./src/nohttp.c:81:23: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
  kore_log(LOG_NOTICE, "%p: received %u bytes", c, nb->s_off);
                       ^
created ./dh2048.pem
nohttp built successfully!


##############################################################################
kore-master/examples/pipe_task$ kore build
building pipe_task (dev)
CFLAGS=-Wall -Wmissing-declarations -Wshadow -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wsign-compare -fPIC -I./src -I./src/includes -I/usr/local/include -g 
LDFLAGS=-shared 
building asset frontend.html
compiling pipe_task.c
./src/pipe_task.c:50:8: error: variable ‘wscbs’ has initializer but incomplete type
 struct kore_wscbs wscbs = {
        ^
./src/pipe_task.c:51:2: warning: excess elements in struct initializer
  websocket_connect,
  ^
./src/pipe_task.c:51:2: note: (near initialization for ‘wscbs’)
./src/pipe_task.c:52:2: warning: excess elements in struct initializer
  websocket_message,
  ^
./src/pipe_task.c:52:2: note: (near initialization for ‘wscbs’)
./src/pipe_task.c:53:2: warning: excess elements in struct initializer
  websocket_disconnect
  ^
./src/pipe_task.c:53:2: note: (near initialization for ‘wscbs’)
./src/pipe_task.c: In function ‘page_ws_connect’:
./src/pipe_task.c:118:32: warning: passing argument 2 of ‘kore_websocket_handshake’ from incompatible pointer type [-Wincompatible-pointer-types]
  kore_websocket_handshake(req, &wscbs);
                                ^
In file included from ./src/pipe_task.c:28:0:
/usr/local/include/kore/kore.h:584:7: note: expected ‘const char *’ but argument is of type ‘struct kore_wscbs *’
 void  kore_websocket_handshake(struct http_request *,
       ^
./src/pipe_task.c:118:2: error: too few arguments to function ‘kore_websocket_handshake’
  kore_websocket_handshake(req, &wscbs);
  ^
In file included from ./src/pipe_task.c:28:0:
/usr/local/include/kore/kore.h:584:7: note: declared here
 void  kore_websocket_handshake(struct http_request *,
       ^
./src/pipe_task.c: In function ‘pipe_data_available’:
./src/pipe_task.c:199:23: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
  kore_log(LOG_NOTICE, "got %d bytes from task", len);
                       ^
kore build: subprocess trouble, check output


##############################################################################
kore-master/examples/tasks$ kore build
building tasks (dev)
CFLAGS=-Wall -Wmissing-declarations -Wshadow -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wsign-compare -fPIC -I./src -I./src/includes -I/usr/local/include -g 
LDFLAGS=-shared -lcurl 
compiling tasks.c
./src/tasks.c: In function ‘run_curl’:
./src/tasks.c:223:29: warning: passing argument 2 of ‘kore_buf_release’ from incompatible pointer type [-Wincompatible-pointer-types]
  data = kore_buf_release(b, &len);
                             ^
In file included from ./src/tasks.c:32:0:
/usr/local/include/kore/kore.h:686:11: note: expected ‘size_t * {aka long unsigned int *}’ but argument is of type ‘u_int32_t * {aka unsigned int *}’
 u_int8_t *kore_buf_release(struct kore_buf *, size_t *);
           ^
created ./dh2048.pem
tasks built successfully!


##############################################################################
kore-master/examples/video_stream$ kore build
building video_stream (dev)
CFLAGS=-Wall -Wmissing-declarations -Wshadow -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wsign-compare -fPIC -I./src -I./src/includes -I/usr/local/include -g 
LDFLAGS=-shared 
building asset video.html
compiling stream.c
./src/stream.c: In function ‘video_stream_finish’:
./src/stream.c:264:23: warning: format ‘%d’ expects argument of type ‘int’, but argument 5 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
  kore_log(LOG_NOTICE, "%p: video stream %s done (%d/%d ref:%d)",
                       ^
./src/stream.c:264:23: warning: format ‘%d’ expects argument of type ‘int’, but argument 6 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
compiling video.html
created ./dh2048.pem
video_stream built successfully!

**Comment by jorisvink** [comment]
Yup I recently changed a few internals and haven't gotten around fixing the examples yet as it's not ready for release.

But I feel master should always build regardless.

Thanks for pointing this out and I'll get it fixed as soon as I can.

**Comment by benwills** [comment]
Sounds good. I've told several people how much I love Kore. I really appreciate your work on this.

**Comment by jorisvink** [comment]
:-)

**Comment by PauloMelo** [comment]
Joris,
I'm trying to build some tests for my code and the assets.h file is deleted...

Why do you (void)unlink(assets_header); at line 571 on cli.c? 
unlinking at line 525 I understand, you delete before creating the file and populating it, but deleting it after is not helping for outside testing or code coverage tools.

**Comment by jorisvink** [comment]
Yeah maybe the generated assets.h file should stick around for these purposes.

.joris

**Comment by jkalmar** [comment]
Keeping assets.h is a good idea. It helps also some IDE to index the names and make autocomplete work out of the box. So personally I like the idea of keeping it.

**Comment by jorisvink** [comment]
@benwills Can you pull and try again on the examples? I've pushed certain changes to bring them inline with recent other changes.

**Comment by jorisvink** [comment]
poke poke

**Comment by benwills** [comment]
Thanks for this. I'll be able to test this weekend and will update when I do.

**Comment by benwills** [comment]
Just got a chance to test this and it does build successfully with my existing kore install. Thank you!

**Comment by jorisvink** [comment]
Lovely, closing this issue then.
