### ISSUE TITLE
kore.pid on kodev is not read from conf

### ISSUE THREAD

**Issue by PauloMelo** [jorisvink/kore#176]
Hi Joris,

I like your new kodev / kore separation but I've found that kodev does not use the kore.pid defined at the conf file.

Regards,
Paulo Melo

**Comment by jorisvink** [comment]
That is as expected, it runs under the current working directory just like kodev build, kodev run.

I'm aware it misses the use case there the pidfile has been moved to somewhere but I'm not going to let kodev read the configuration for now. It's only reload that has this "problem".

**Comment by jorisvink** [comment]
I'll be closing this as it's not really an issue.

**Comment by PauloMelo** [comment]
I understand that it runs under the current working directory. But if kodev run calls kore with the configuration file and the pid is set to another centralized directory we cannot reload, and that is a petty. I am using atom as my editor, and I've created a Kore Start/Stop plugin for my personal developments, so I use a centralized pid for all my developments. That way I could reload what I wanted, when I wanted. 

I hope that someday you may put the same logic to the kodev reload.

Regards,
Paulo Melo

**Comment by jorisvink** [comment]
> On Mar 7, 2017, at 17:25, PauloMelo <notifications@github.com> wrote:
> 
> I understand that it runs under the current working directory. But if kodev run calls kore with the configuration file and the pid is set to another centralized directory we cannot reload, and that is a petty. I am using atom as my editor, and I've created a Kore Start/Stop plugin for my personal developments, so I use a centralized pid for all my developments. That way I could reload what I wanted, when I wanted.
> 
> I hope that someday you may put the same logic to the kodev reload.
> 

Yes that is the plan, just not right now :-)
