### ISSUE TITLE
I can't run the hello with ubuntu14.04

### ISSUE THREAD

**Issue by zonshi** [jorisvink/kore#177]
$ kore run
building hello (dev)
CFLAGS=-Wall -Wmissing-declarations -Wshadow -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wsign-compare -fPIC -I./src -I./src/includes -I/usr/local/include -g
LDFLAGS=-shared
nothing to be done!
[parent]: running on https://127.0.0.1:8888
[parent]: kore is starting up
kore: kore_worker_init(): shmget() Function not implemented

**Comment by jorisvink** [comment]
For some reason your kernel doesn't implement shmget().

This can't possibly be a stock Ubuntu 14.04 machine?

**Comment by jorisvink** [comment]
poke, any more information on your setup here?

**Comment by jorisvink** [comment]
poke, one more day before I close this. Any more information?

**Comment by jorisvink** [comment]
closing, timeout.
