### ISSUE TITLE
Example for single_binary=yes

### ISSUE THREAD

**Issue by PauloMelo** [jorisvink/kore#178]
Hi Joris,

I cannot find any documentation or examples for the usage of single_binary=yes in the build.conf

I've tried it, but I get:
make: *** No rule to make target `objects'.  Stop.
kore build: subprocess trouble, check output

Regards,
Paulo Melo

**Comment by jorisvink** [comment]
It's in the documentation on gitbook.

https://jorisvink.gitbooks.io/kore-doc/content/applications/building.html

.joris

**Comment by PauloMelo** [comment]
These are the parameters that I've set:
single_binary=yes
kore_source=/usr/local/kore/src
kore_flavor=dev

and the return code is 
kore build: invalid flavor dev

looking at the code I've set the parameters as the ones I've used to compile kore
kore_flavor=NOTLS=1 DEBUG=1 TASKS=1 PGSQL=1
that expand internally to -DKORE_DEBUG -DKORE_NO_TLS -DKORE_USE_PGSQL -DKORE_USE_TASKS

But then I get the error I've mentioned before: 
building kore (/usr/local/kore/src)
using flavor NOTLS=1
using flavor DEBUG=1
using flavor TASKS=1
using flavor PGSQL=1
make: *** No rule to make target `objects'.  Stop.
kore build: subprocess trouble, check output

Regards,
Paulo Melo

**Comment by PauloMelo** [comment]
Solved the kore src should be just /usr/local/kore.

Thanks.

**Comment by PauloMelo** [comment]
Hi Joris,

just one last question. How do I define an "onload" function for a single_binary?

**Comment by jorisvink** [comment]
You implement the kore_worker_configure() function in your code which is called when workers startup.

In the same way you have kore_parent_configure() which is called when the parent starts up.

**Comment by jorisvink** [comment]
The prototype for those are

void kore_worker_configure(void);
void kore_parent_configure(void);

**Comment by PauloMelo** [comment]
Many thanks.

Works perfectly.
