### ISSUE TITLE
"if-modified-since" header doesn't work in Chrome

### ISSUE THREAD

**Issue by ouadev** [jorisvink/kore#179]
Hi,

in the examples, at least in 'generic' one, the use of "if-modified-since" to cache css file, is not working for Chrome, I used instead "Cache-Control":"max-age:60" for example.

**Comment by jorisvink** [comment]
Hi,

Yeah that stuff needs to be deprecated in favor of the new asset_serve_* functionally which provides automatic etags and what not.

I'll fix this later today!

.joris
