### ISSUE TITLE
Serving static files

### ISSUE THREAD

**Issue by joseluis8906** [jorisvink/kore#180]
Hi, how can I serve static files with kore?

**Comment by jorisvink** [comment]
Place them under assets/ directory. Then add them to your configuration + add mime type to build.conf.

Example: assets/style.css

if available under /css/style.css add to your config:

static /css/style.css asset_serve_style_css

Add to build.conf:

mime_add=css:text/css

Kore automatically generates the asset_serve_* functions for all static assets at build time, and resolves mine types based on what's configured in your build.conf.

**Comment by jorisvink** [comment]
Little note, Doing it this way gives you automatic ETags and if-none-match handling.

**Comment by joseluis8906** [comment]
Jorisvink, it works but it is possible to serve static content without having to add the url to the configuration file ?. Something similar to how nginx does, just assigning a root directory, which when adding a file to that directory is automatically available. 

Look, I will be uploading files to a directory and I need them as soon as they upload are available to be served, I do not know how to add their respective url to the configuration file while kore is running.

**Comment by jorisvink** [comment]
You will need to implement that functionally.

Kore does not know how to how to do this out of the box.

**Comment by joseluis8906** [comment]
ok thaks! :)

**Comment by jorisvink** [comment]
Closing this.

**Comment by Globik** [comment]
Ach sooo, I see, I see. Kore is more suitable for embedded systems. Not perfect as a standalone webserver.
