### ISSUE TITLE
Perfomance of horizontal scalability 

### ISSUE THREAD

**Issue by AlexanderSheety** [jorisvink/kore#182]
Hello jorisvink!
I have 3 servers:
Frontend - connections and files
Backend - logic 
Db server - database

1. What is better for perfomance, to create one main connection between frontend and backend or more connections ?
2. Is it possible to create one connection between frontend and backend and how to synchronizing that?

**Comment by jorisvink** [comment]
Hi,

I can't answer this as this highly depends on your setup and what your machines are doing.

.joris

**Comment by AlexanderSheety** [comment]
I will use kore like parse.com. Frontend server will have only application (android,ios,win10)  connections   by websockets or nohttp. I didn't choose between websockets and nohttp so far.
Dependencies:
app connections-> Frontend server -> connections ->Backend server -> connections -> Database server

**Comment by jorisvink** [comment]
Sorry if I wasn't clear enough but I really cannot answer this. Do tests to figure out what is better for performance, check where your bottlenecks (if any) lie and improve there. Test if multiple db connections are better or if single ones are better, etc.

All I can tell you is that Kore is probably not going to get in your way, but your application code will.

**Comment by AlexanderSheety** [comment]
Ok. Thanks!
Do you use kore in several servers ?
How will you organize work or synchronization between servers in your project?

**Comment by jorisvink** [comment]
I have a kore TLS proxy in front of most of my stuff I run.

The way I share data between worker processes highly depends from application to application, some use the built-in messaging framework others offload it to a message queue, a few others just use a database.

**Comment by AlexanderSheety** [comment]
What messaging framework do you use ?

**Comment by jorisvink** [comment]
Kore has a built-in mechanism to dispatch messages between workers.

There's an example under examples/messages/.

You basically define a channel on which you submit messages, Kore will deliver them to each worker or to individual workers and call a preset callback when messages are received.

I use this to synchronize in-memory ephemeral sessions between all worker processes for example.

**Comment by AlexanderSheety** [comment]
Great! Thanks a lot
