### ISSUE TITLE
No compile with OpenSSL 1.1.0 or later

### ISSUE THREAD

**Issue by Dusan-Krehel** [jorisvink/kore#183]
# No compile with OpenSSL 1.1.0 or later

I compiled unsuccesfully on Debian RC2 with _OpenSSL 1.0.2k_ library.

Because:

>{The only remaining issue are the ECDSA_METHOD tests that are skipped now. Detailed OpenSSL 1.1.0 changelog <https://www.openssl.org/news/cl110.txt> reads:
  
>*) New EC_KEY_METHOD, this replaces the older ECDSA_METHOD and ECDH_METHOD and integrates ECDSA and ECDH functionality into EC. Implementations can now redirect key generation and no longer need to convert to or from ECDSA_SIG format.

> Note: the ecdsa.h and ecdh.h headers are now no longer needed and just include the ec.h header file instead.
}

source: [https://rt.cpan.org/Public/Bug/Display.html?id=118330#txn-1675972](https://rt.cpan.org/Public/Bug/Display.html?id=118330#txn-1675972)

**Comment by jorisvink** [comment]
I'm aware.

Someone is working on supporting this and I expect to see a PR for this sooner than later.

**Comment by jorisvink** [comment]
> I compiled unsuccesfully on Debian RC2 with OpenSSL 1.0.2k library.

I understand it not building with 1.1.0 but it builds successfully here with 1.0.2k. What errors are you getting when attempting to build vs 1.0.2k?

**Comment by Dusan-Krehel** [comment]
Ok. Then come back to Debian 8. Debian 9 RC2 must wait.

> I understand it not building with 1.1.0 but it builds successfully here with 1.0.2k. What errors are you getting when attempting to build vs 1.0.2k?

View [make messages](https://github.com/jorisvink/kore/files/861155/make.txt) with _gcc version 6.3.0 20170205 (Debian 6.3.0-6)_ and _OpenSSL 1.1.0e  16 Feb 2017._.

**Comment by jorisvink** [comment]
Just a quick update, 1.1.0 support is coming.

**Comment by mondokm** [comment]
Any updates on this?

**Comment by jorisvink** [comment]
Not yet, other than it is planned and some diff exists. Haven't had time yet.

.joris

**Comment by jorisvink** [comment]
This has been fixed in latest 95daf3a62bef0b9c84101eecbb464fd474566f45 - please checkout master and try again.

**Comment by jorisvink** [comment]
Poke .. any one?

@Dusan-Krehel 
@mondokm

**Comment by jorisvink** [comment]
Fixed in master. Timeout from OP. Closing.
