### ISSUE TITLE
Preserve Host header/URI authority

### ISSUE THREAD

**Issue by strangepete** [jorisvink/kore#184]
The **Host** header is being removed from the request - in the process, the **port** number is stripped when copying to `req->host`.  As the port is a part of the URI Authority _(unless empty or the scheme default)_ it should remain in `req->host` _**or,**_ preserve the full header as-sent, with the remaining headers.

I think it makes the most sense to leave the host header intact, in addition, so it can be consumed like the other headers in a standard way, no?

References:
Host header: [rfc7230 section 5.4](https://tools.ietf.org/html/rfc7230#section-5.4) & [2.7.1->2.7.3](https://tools.ietf.org/html/rfc7230#section-2.7.1)
URI: [rfc3986 section 3.2](https://tools.ietf.org/html/rfc3986#section-3.2)  &  [3.2.3](https://tools.ietf.org/html/rfc3986#section-3.2.3)

**Comment by jorisvink** [comment]
Agreed the host header should be obtainable via http_request_header() in its original form.

I'll fix.

**Comment by strangepete** [comment]
Awesome, thanks! Will you leave `req->host` as-implemented, or will it match the header?

I've been playing with yubico's [libu2f-server](https://github.com/Yubico/libu2f-server) (thus need for the target origin) and so far it plays well with Kore, and blazingly fast; so thanks for that too!

**Comment by jorisvink** [comment]
req->host will match the header when the commit goes in.

**Comment by jorisvink** [comment]
@strangepete Give it a spin now.

**Comment by strangepete** [comment]
That does it, thanks!

**Comment by jorisvink** [comment]
Neat!
