### ISSUE TITLE
NoHttp and Http

### ISSUE THREAD

**Issue by AlexanderSheety** [jorisvink/kore#185]
Hello jorisvink !
Is it possible to use NoHttp and http together?
Nohttp will have port :8888
Http will have port:  443

Nohttp will be using for only applications , http for only some web services like analytics and ads ?

**Comment by jorisvink** [comment]
Hi,

You could two bind directives, one for each:

bind ip 8888 onconnect_callback
bind ip 443

and implement the onconnect_callback to setup the net reads and what not yourself, while for 443 kore will just use the http stack.

Doesn't require a special build.

.joris

**Comment by AlexanderSheety** [comment]
Great! Thanks!
