### ISSUE TITLE
some confusion about plug-in software in kore-project environment

### ISSUE THREAD

**Issue by xjZhan** [jorisvink/kore#187]
Dear Joris Vink:
       Thanks for your contributions. I am trying to use your project to complete a engine framework. But I meet some problems about "kore_pgsql_query_init" and "clock_gettime" when I compile a project of named "ayahesa" on your frame，so I suspect that PostgreSQL version can not be suitable for my install-environment.
       Before I compile the project, the environment is already installed successfully.

ayahesa: git clone https://github.com/yorickdewid/ayahesa.git

       So, I need you help me to confirm all important plug-in's version and I could complete this important task.
       such as openssl(OpenSSL 1.0.2k), python(3.6+), PostgreSQL(?), ......

       About could you give my some other useful advices and precautions?

THANKS VERY VERY MUCH!

**Comment by jorisvink** [comment]
Can you please provide the full output from kodev build?

.joris

**Comment by xjZhan** [comment]
ok, I uninstall the kore and clean all related files.Lastly, install it(python3 is not installed in my mac, so I use the command "make PGSQL=1 TASKS=1 DEBUG=1" )

>>cd kore
>>make PGSQL=1 TASKS=1 DEBUG=1 PYTHON=1
>>sudo make install

> >the following is printLog in iterm2:

vincenszhandeMacBook-Pro:kore xiaojie.zhan$ find / -name 'kore'
find: /System/Library/DirectoryServices/DefaultLocalDB/Default: Permission denied
find: /System/Library/User Template: Permission denied
/Users/xiaojie.zhan/Documents/kore-project-file/ayahesa/kore
/Users/xiaojie.zhan/Documents/kore-project-file/ayahesa/kore/kore
/Users/xiaojie.zhan/kore-project/kore
/Users/xiaojie.zhan/kore-project/kore/kore
/usr/local/include/kore
/usr/local/share/kore
find: /usr/sbin/authserver: Permission denied
vincenszhandeMacBook-Pro:kore xiaojie.zhan$ kodev clean
vincenszhandeMacBook-Pro:kore xiaojie.zhan$ make uninstall
rm -f /usr/local/bin/kore
rm -rf /usr/local/include/kore
rm: /usr/local/include/kore/http.h: Permission denied
rm: /usr/local/include/kore/jsonrpc.h: Permission denied
rm: /usr/local/include/kore/kore.h: Permission denied
rm: /usr/local/include/kore/pgsql.h: Permission denied
rm: /usr/local/include/kore/python_api.h: Permission denied
rm: /usr/local/include/kore/python_methods.h: Permission denied
rm: /usr/local/include/kore/tasks.h: Permission denied
rm: /usr/local/include/kore: Directory not empty
make: *** [uninstall] Error 1
vincenszhandeMacBook-Pro:kore xiaojie.zhan$ make clean
find . -type f -name \*.o -exec rm {} \;
rm -rf kore obj kore.features
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C kodev clean
find . -type f -name \*.o -exec rm {} \;
rm -rf kodev obj
vincenszhandeMacBook-Pro:kore xiaojie.zhan$ rm -rf /usr/local/include/kore /usr/local/share/kore
rm: /usr/local/include/kore/http.h: Permission denied
rm: /usr/local/include/kore/jsonrpc.h: Permission denied
rm: /usr/local/include/kore/kore.h: Permission denied
rm: /usr/local/include/kore/pgsql.h: Permission denied
rm: /usr/local/include/kore/python_api.h: Permission denied
rm: /usr/local/include/kore/python_methods.h: Permission denied
rm: /usr/local/include/kore/tasks.h: Permission denied
rm: /usr/local/include/kore: Directory not empty
rm: /usr/local/share/kore/features: Permission denied
rm: /usr/local/share/kore: Directory not empty
vincenszhandeMacBook-Pro:kore xiaojie.zhan$
vincenszhandeMacBook-Pro:kore xiaojie.zhan$
vincenszhandeMacBook-Pro:kore xiaojie.zhan$ make PGSQL=1 TASKS=1 DEBUG=1
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -DKORE_DEBUG -g -O0 -I/usr/local/Cellar/postgresql/9.6.2/include -DKORE_USE_PGSQL -DPGSQL_INCLUDE_PATH="\"/usr/local/Cellar/postgresql/9.6.2/include\"" -DKORE_USE_TASKS -I/opt/local/include/ -I/usr/local/opt/openssl/include -c src/kore.c -o obj/kore.o
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -DKORE_DEBUG -g -O0 -I/usr/local/Cellar/postgresql/9.6.2/include -DKORE_USE_PGSQL -DPGSQL_INCLUDE_PATH="\"/usr/local/Cellar/postgresql/9.6.2/include\"" -DKORE_USE_TASKS -I/opt/local/include/ -I/usr/local/opt/openssl/include -c src/buf.c -o obj/buf.o
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -DKORE_DEBUG -g -O0 -I/usr/local/Cellar/postgresql/9.6.2/include -DKORE_USE_PGSQL -DPGSQL_INCLUDE_PATH="\"/usr/local/Cellar/postgresql/9.6.2/include\"" -DKORE_USE_TASKS -I/opt/local/include/ -I/usr/local/opt/openssl/include -c src/config.c -o obj/config.o
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -DKORE_DEBUG -g -O0 -I/usr/local/Cellar/postgresql/9.6.2/include -DKORE_USE_PGSQL -DPGSQL_INCLUDE_PATH="\"/usr/local/Cellar/postgresql/9.6.2/include\"" -DKORE_USE_TASKS -I/opt/local/include/ -I/usr/local/opt/openssl/include -c src/connection.c -o obj/connection.o
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -DKORE_DEBUG -g -O0 -I/usr/local/Cellar/postgresql/9.6.2/include -DKORE_USE_PGSQL -DPGSQL_INCLUDE_PATH="\"/usr/local/Cellar/postgresql/9.6.2/include\"" -DKORE_USE_TASKS -I/opt/local/include/ -I/usr/local/opt/openssl/include -c src/domain.c -o obj/domain.o
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -DKORE_DEBUG -g -O0 -I/usr/local/Cellar/postgresql/9.6.2/include -DKORE_USE_PGSQL -DPGSQL_INCLUDE_PATH="\"/usr/local/Cellar/postgresql/9.6.2/include\"" -DKORE_USE_TASKS -I/opt/local/include/ -I/usr/local/opt/openssl/include -c src/mem.c -o obj/mem.o
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -DKORE_DEBUG -g -O0 -I/usr/local/Cellar/postgresql/9.6.2/include -DKORE_USE_PGSQL -DPGSQL_INCLUDE_PATH="\"/usr/local/Cellar/postgresql/9.6.2/include\"" -DKORE_USE_TASKS -I/opt/local/include/ -I/usr/local/opt/openssl/include -c src/msg.c -o obj/msg.o
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -DKORE_DEBUG -g -O0 -I/usr/local/Cellar/postgresql/9.6.2/include -DKORE_USE_PGSQL -DPGSQL_INCLUDE_PATH="\"/usr/local/Cellar/postgresql/9.6.2/include\"" -DKORE_USE_TASKS -I/opt/local/include/ -I/usr/local/opt/openssl/include -c src/module.c -o obj/module.o
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -DKORE_DEBUG -g -O0 -I/usr/local/Cellar/postgresql/9.6.2/include -DKORE_USE_PGSQL -DPGSQL_INCLUDE_PATH="\"/usr/local/Cellar/postgresql/9.6.2/include\"" -DKORE_USE_TASKS -I/opt/local/include/ -I/usr/local/opt/openssl/include -c src/net.c -o obj/net.o
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -DKORE_DEBUG -g -O0 -I/usr/local/Cellar/postgresql/9.6.2/include -DKORE_USE_PGSQL -DPGSQL_INCLUDE_PATH="\"/usr/local/Cellar/postgresql/9.6.2/include\"" -DKORE_USE_TASKS -I/opt/local/include/ -I/usr/local/opt/openssl/include -c src/pool.c -o obj/pool.o
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -DKORE_DEBUG -g -O0 -I/usr/local/Cellar/postgresql/9.6.2/include -DKORE_USE_PGSQL -DPGSQL_INCLUDE_PATH="\"/usr/local/Cellar/postgresql/9.6.2/include\"" -DKORE_USE_TASKS -I/opt/local/include/ -I/usr/local/opt/openssl/include -c src/runtime.c -o obj/runtime.o
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -DKORE_DEBUG -g -O0 -I/usr/local/Cellar/postgresql/9.6.2/include -DKORE_USE_PGSQL -DPGSQL_INCLUDE_PATH="\"/usr/local/Cellar/postgresql/9.6.2/include\"" -DKORE_USE_TASKS -I/opt/local/include/ -I/usr/local/opt/openssl/include -c src/timer.c -o obj/timer.o
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -DKORE_DEBUG -g -O0 -I/usr/local/Cellar/postgresql/9.6.2/include -DKORE_USE_PGSQL -DPGSQL_INCLUDE_PATH="\"/usr/local/Cellar/postgresql/9.6.2/include\"" -DKORE_USE_TASKS -I/opt/local/include/ -I/usr/local/opt/openssl/include -c src/utils.c -o obj/utils.o
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -DKORE_DEBUG -g -O0 -I/usr/local/Cellar/postgresql/9.6.2/include -DKORE_USE_PGSQL -DPGSQL_INCLUDE_PATH="\"/usr/local/Cellar/postgresql/9.6.2/include\"" -DKORE_USE_TASKS -I/opt/local/include/ -I/usr/local/opt/openssl/include -c src/worker.c -o obj/worker.o
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -DKORE_DEBUG -g -O0 -I/usr/local/Cellar/postgresql/9.6.2/include -DKORE_USE_PGSQL -DPGSQL_INCLUDE_PATH="\"/usr/local/Cellar/postgresql/9.6.2/include\"" -DKORE_USE_TASKS -I/opt/local/include/ -I/usr/local/opt/openssl/include -c src/keymgr.c -o obj/keymgr.o
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -DKORE_DEBUG -g -O0 -I/usr/local/Cellar/postgresql/9.6.2/include -DKORE_USE_PGSQL -DPGSQL_INCLUDE_PATH="\"/usr/local/Cellar/postgresql/9.6.2/include\"" -DKORE_USE_TASKS -I/opt/local/include/ -I/usr/local/opt/openssl/include -c src/auth.c -o obj/auth.o
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -DKORE_DEBUG -g -O0 -I/usr/local/Cellar/postgresql/9.6.2/include -DKORE_USE_PGSQL -DPGSQL_INCLUDE_PATH="\"/usr/local/Cellar/postgresql/9.6.2/include\"" -DKORE_USE_TASKS -I/opt/local/include/ -I/usr/local/opt/openssl/include -c src/accesslog.c -o obj/accesslog.o
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -DKORE_DEBUG -g -O0 -I/usr/local/Cellar/postgresql/9.6.2/include -DKORE_USE_PGSQL -DPGSQL_INCLUDE_PATH="\"/usr/local/Cellar/postgresql/9.6.2/include\"" -DKORE_USE_TASKS -I/opt/local/include/ -I/usr/local/opt/openssl/include -c src/http.c -o obj/http.o
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -DKORE_DEBUG -g -O0 -I/usr/local/Cellar/postgresql/9.6.2/include -DKORE_USE_PGSQL -DPGSQL_INCLUDE_PATH="\"/usr/local/Cellar/postgresql/9.6.2/include\"" -DKORE_USE_TASKS -I/opt/local/include/ -I/usr/local/opt/openssl/include -c src/validator.c -o obj/validator.o
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -DKORE_DEBUG -g -O0 -I/usr/local/Cellar/postgresql/9.6.2/include -DKORE_USE_PGSQL -DPGSQL_INCLUDE_PATH="\"/usr/local/Cellar/postgresql/9.6.2/include\"" -DKORE_USE_TASKS -I/opt/local/include/ -I/usr/local/opt/openssl/include -c src/websocket.c -o obj/websocket.o
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -DKORE_DEBUG -g -O0 -I/usr/local/Cellar/postgresql/9.6.2/include -DKORE_USE_PGSQL -DPGSQL_INCLUDE_PATH="\"/usr/local/Cellar/postgresql/9.6.2/include\"" -DKORE_USE_TASKS -I/opt/local/include/ -I/usr/local/opt/openssl/include -c src/pgsql.c -o obj/pgsql.o
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -DKORE_DEBUG -g -O0 -I/usr/local/Cellar/postgresql/9.6.2/include -DKORE_USE_PGSQL -DPGSQL_INCLUDE_PATH="\"/usr/local/Cellar/postgresql/9.6.2/include\"" -DKORE_USE_TASKS -I/opt/local/include/ -I/usr/local/opt/openssl/include -c src/tasks.c -o obj/tasks.o
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -DKORE_DEBUG -g -O0 -I/usr/local/Cellar/postgresql/9.6.2/include -DKORE_USE_PGSQL -DPGSQL_INCLUDE_PATH="\"/usr/local/Cellar/postgresql/9.6.2/include\"" -DKORE_USE_TASKS -I/opt/local/include/ -I/usr/local/opt/openssl/include -c src/bsd.c -o obj/bsd.o
cc obj/kore.o obj/buf.o obj/config.o obj/connection.o obj/domain.o obj/mem.o obj/msg.o obj/module.o obj/net.o obj/pool.o obj/runtime.o obj/timer.o obj/utils.o obj/worker.o obj/keymgr.o obj/auth.o obj/accesslog.o obj/http.o obj/validator.o obj/websocket.o obj/pgsql.o obj/tasks.o obj/bsd.o -rdynamic -lssl -lcrypto -L/usr/local/lib -lpq -lpthread -L/opt/local/lib -L/usr/local/opt/openssl/lib -o kore
ld: warning: directory not found for option '-L/opt/local/lib'
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C kodev
cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -O2 -I/opt/local/include/ -I/usr/local/opt/openssl/include -c ../src/cli.c -o obj/cli.o
cc obj/cli.o -lcrypto -L/opt/local/lib -L/usr/local/opt/openssl/lib -o kodev
ld: warning: directory not found for option '-L/opt/local/lib'
vincenszhandeMacBook-Pro:kore xiaojie.zhan$
vincenszhandeMacBook-Pro:kore xiaojie.zhan$ sudo make install
Password:
mkdir -p /usr/local/share/kore
mkdir -p /usr/local/include/kore
mkdir -p /usr/local/bin
install -m 555 kore /usr/local/bin/kore
install -m 644 kore.features /usr/local/share/kore/features
install -m 644 includes/*.h /usr/local/include/kore
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C kodev install
mkdir -p /usr/local/bin
install -m 555 kodev /usr/local/bin/kodev
vincenszhandeMacBook-Pro:kore xiaojie.zhan$

- 

Because I can not contact the author of project "ayahesa", but "ayahesa" is based on your frame to develop some functions, so I only ask for help to you.  -_- > ^_^

Thank you for your help!

**Comment by xjZhan** [comment]
HI joris:
        In addition, What is the condition when we use your frame? At present, I use mac and centOS to run the project "ayahesa" on your frame, but all are failed and the outputs print different err.

mac:
(OpenSSL 1.0.2k), PostgreSQL((PostgreSQL) 9.6.2)
>vincenszhandeMacBook-Pro:ayahesa xiaojie.zhan$ kodev build
>building ayahesa (dev)
>CFLAGS=-Wall -Wmissing-declarations -Wshadow -Wstrict-prototypes -Wmissing-prototypes ->Wpointer-arith -Wcast-qual -Wsign-compare -Werror -pedantic -std=c99 -Isrc/include -fPIC -Isrc ->Isrc/includes -I/usr/local/include -I/opt/local/include -I/usr/local/opt/openssl/include -DKORE_DEBUG ->DKORE_USE_PGSQL -DKORE_USE_TASKS -g -DOPT_ROUTES
>LDFLAGS=-dynamiclib -undefined suppress -flat_namespace
>building asset layout.html
>building asset report.html
>building asset static.html
>building asset status.html
>compiling principal.c
>src/model/principal.c:42:10: error: implicit declaration of function 'kore_pgsql_query_init' is invalid in >C99 [-Werror,-Wimplicit-function-declaration]
>    if (!kore_pgsql_query_init(&pgsql, NULL, "dbrw", KORE_PGSQL_SYNC)) {
>         ^
>1 error generated.
>kore build: subprocess trouble, check output
>vincenszhandeMacBook-Pro:ayahesa xiaojie.zhan$

centOS:
>[root@iZwz93ruwqpe81hzr2066pZ ayahesa]# kodev build
>building ayahesa (dev)
>CFLAGS=-Wall -Wmissing-declarations -Wshadow -Wstrict-prototypes -Wmissing-prototypes ->Wpointer-arith -Wcast-qual -Wsign-compare -Werror -pedantic -std=c99 -Isrc/include -fPIC -Isrc ->Isrc/includes -I/usr/local/include -DKORE_DEBUG -DKORE_USE_PGSQL -DKORE_USE_TASKS -g ->DOPT_ROUTES
>LDFLAGS=-shared
>building asset status.html
>building asset static.html
>building asset report.html
>building asset layout.html
>compiling quid.c
>src/vendor/quid/quid.c: In function 'get_tick_count':
>src/vendor/quid/quid.c:496:5: error: implicit declaration of function 'clock_gettime' [-Werror=implicit->function-declaration]
>     if (clock_gettime(CLOCK_MONOTONIC, &now))
>     ^
>cc1: all warnings being treated as errors
>kore build: subprocess trouble, check output
>[root@iZwz93ruwqpe81hzr2066pZ ayahesa]#

**Comment by mrwert** [comment]
Everything works well for the FreeBSD, Linux Mint and Ubuntu.

**Comment by mrwert** [comment]
xjZhan, you can delete this flag `-Werror`.
`-Werror` — make all warnings into errors.

**Comment by jorisvink** [comment]
I'm sorry but since kore compiles and installs properly on your system I don't see how this is a problem I should address.

If a project built with kore isn't building on your system you should probably contact the maintainer of that project.

Thanks.
