### ISSUE TITLE
Request for a more simple example of file streaming

### ISSUE THREAD

**Issue by bjornharrtell** [jorisvink/kore#188]
I'm trying to understand how to use kore as a thin file streaming server with a tiny bit of routing and rewrite logic (but more than a regexp can handle so normal web servers are out of the picture). Because I'm a novice at C I/O I find it hard to learn how to read and stream the data (I assume http_response_stream should be used). I think the example video_stream is a bit too complex and would love to see a more simple one.

**Comment by jorisvink** [comment]
Hi,

You are correct in assuming you should use http_response_stream(). It takes a handler that is called whenever the queued up chunk was sent. So you could once a chunk is completed read more data from some file descriptor and send it. The video example uses mmap() but it is not restricted to that. You will have to manage some state yourself.

I gotta be honest if you aren't all too familiar with C is this really a good choice?

.joris

**Comment by bjornharrtell** [comment]
Might be so but I'm willing to learn. :) And in the particular case I have the benefit of a small independent binary is important. I considered Rust but I have no experience at all with that language and I'm not a total beginner with C in general. Also, Kore looks nicely implemented and designed.

Anyway thanks for at least confirming that I'm looking at the correct API, I'll see if I can get anywhere and will contribute an example if it goes well.

**Comment by jorisvink** [comment]
> Anyway thanks for at least confirming that I'm looking at the correct API, I'll see if I can get anywhere and will contribute an example if it goes well.
> 

I'll gladly include that example in the tree once finished.

.joris

**Comment by stan1y** [comment]
Just a note, that kore's master has support for python runtime and most of the functionality is exposed. If you can trade one binary benefit for one binary and one script, then it might be an easier route to go.
