### ISSUE TITLE
Information request: Scheduling requests and connections

### ISSUE THREAD

**Issue by mankash** [jorisvink/kore#194]
Hello @jorisvink -

Big fan of Kore here! Thank you for your selfless contributions. 

Please comment on: 

1. Scheduling/routing connections to workers. 
2. Scheduling/routing requests to workers
3. Why do you need a lock mechanism for managing workers? Will a lock less FIFO per worker achieve the same functionality at lower computational overhead?
4. Is there any dependency on a particular worker for a particular connection? For example, if connection X started off on worker 1, do all subsequent requests from X need worker 1 or can any worker address them? 

Cheers.

**Comment by jorisvink** [comment]
> On 22 Jun 2017, at 03:17, Manohar Kashyap <notifications@github.com> wrote:
> Scheduling connections to workers.
> Scheduling requests to workers
> Why do you need a lock mechanism for managing workers? Will a lock less FIFO per worker achieve the same functionality at lower computational overhead?
Thundering herd problem. If you have tons of worker processes all sleeping on the same socket waiting for new connections you do not want your kernel to wake them all up. It's a waste of resources. The lock makes sure only one worker at a time is sleeping on the socket. Linux and epoll have addressed this (or will?) but Linux isn't the only platform Kore runs on.

> Is there any dependency on a particular worker for a particular connection? For example, if connection X started off on worker 1, do all subsequent requests from X need worker 1 or can any worker address them?
Once a connection is accepted by a worker, the worker owns it in full and is responsible for any requests coming from said connection.

.joris

**Comment by mankash** [comment]
Thanks. Will close this issue. 

On an unrelated note, [this](https://github.com/jorisvink/kore/wiki/Major-API-changes) link summarizes API changes. Is there another place that lists your upcoming features/modifications plan. 

Cheers

**Comment by jorisvink** [comment]
> Thanks. Will close this issue.
> 
> On an unrelated note, this link summarizes API changes. Is there another place that lists your upcoming features/modifications plan.
> 
I don't have a fixed roadmap. I usually end up adding things I need myself, or if others come with reasonable PRs I'll consider it.

I tend to cut a release whenever I feel comfortable with it, but in general master is always stable. Bug fixes or security critical fixes will always be a reason to cut a release asap.

.joris
