### ISSUE TITLE
Ability to specify the app name.

### ISSUE THREAD

**Issue by bweston92** [jorisvink/kore#196]
Given the following Dockerfile is built as `kore` when I do `docker run --rm -v $(pwd):/src kore build myapp` then change directory on the host machine into `myapp` work on the source and try to run with `docker run --rm -v $(pwd):/src kore run` I get "kore run: src doesn't appear to be a kore app" because the `pwd` is "/src". I need to be able to do something like `docker run --rm -v $(pwd):/src kore run --name=myapp` for it to locate `/src/conf/myapp.conf`

```
FROM ubuntu:14.04

ENV PGSQL=1
ENV NOTLS=1

RUN apt-get update %% apt-get install -y wget make gcc libpq-dev

RUN cd /tmp \
 && wget https://github.com/jorisvink/kore/releases/download/2.0.0-release/kore-2.0.0-release.tar.gz \
 && tar -xvf kore-2.0.0-release.tar.gz \
 && cd kore && \
 && make && make install \
 && mkdir /src

WORKDIR /src

ENTRYPOINT ["kore"]
```

**Comment by jorisvink** [comment]
Something like this would make sense, I've also ran into this myself and only got mildly annoyed by it.

I'll fix it.

**Comment by jorisvink** [comment]
Actually, doing kodev run in Docker images seems dumb.

Why not just run it like this:

kore -fc /src/conf/myapp.conf

starts kore in foreground mode and selects the myapp.conf as the configuration file to use.

**Comment by bweston92** [comment]
@jorisvink basically if my application uses various other libraries that I also have other projects using different versions of them libraries then it would be harder then having a container with the correct library versions.

**Comment by jorisvink** [comment]
Not sure how that related to starting kore with the flags rather then the commands.

kore run (kodev run in master) literally does: kore -frnc conf/appname.conf - thus starting kore manually running kore -fc conf/someconf.conf is helpful.
