### ISSUE TITLE
Deploy on Google Compute Engine

### ISSUE THREAD

**Issue by pescuu** [jorisvink/kore#198]
Hello, Can anybody help me on this. I am typing deploy kore on CentOS on Google Compute Engine.
I tried everything and I am out of ideas :)

I opened port 443 and run generic kore example. On my local machine everything works but when I am trying to do the same on Google Compute Engine I get `strict-transport-security: max-age=31536000; includeSubDomains`

For now it is only for tests so I use certificates in example. 

What happen when I curl:
```
$ curl -v -k https://<IP>
* About to connect() to <IP> port 443 (#0)
*   Trying <IP>...
* Connected to <IP> (<IP>) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=localhost,O=kore autogen: generic,C=SE
*       start date: Jul 09 19:52:31 2017 GMT
*       expire date: Sep 25 19:52:31 2025 GMT
*       common name: localhost
*       issuer: CN=localhost,O=kore autogen: generic,C=SE
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: <IP>
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< server: Server/0.1
< connection: close
< strict-transport-security: max-age=31536000; includeSubDomains
< content-length: 0
< 
* Closing connection 0
```

Thanks for help

**Comment by jorisvink** [comment]
Have you tried changing the domain directive to match the hostname you are trying to fetch it from.

I think it's set to 127.0.0.1 for the generic example.

Basically the hostname or ip argument given to the domain directive decides if kore will look into that block for page handlers.

It matches the Host header sent by the client.

That way in a single conf or app you can serve multiple domains.

Wildcards are also accepted.

Hope this helps!

.joris

**Comment by pescuu** [comment]
If I understand You correctly I should write IP address in the conf/generic.conf. Unfortunately I when I do that I get this.
```
building generic (dev)
CFLAGS=-Wall -Wmissing-declarations -Wshadow -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wsign-compare -fPIC -Isrc -Isrc/includes -I/usr/local/include  -g 
LDFLAGS=-shared 
nothing to be done!
[parent]: bind(): Cannot assign requested address
kore: configuration error on line 3
```

**Comment by jorisvink** [comment]
Well, you need to make sure you add the correct IP to the bind directive AND the correct hostname to the domain one.

If you are getting permission denied you don't have the rights to bind to the port that's been specified in the config.

I'm not familiar with the google thing but I'm sure they have instructions on which ip / port to bind your services too.

Revert your changes you made to the bind option and then change the "domain 127.0.0.1" to be "domain yourdomain.com" instead.

.joris

**Comment by pescuu** [comment]
THANK YOU! It stared to work :)

For the record. In Kore conf file you should have:
```
bind 0.0.0.0 443 
...
doman <YourExternalGoogleIP> {
...
```

**Comment by pescuu** [comment]
THANK YOU! It just started to work :)

For the record. In Kore conf file you should have:

```
bind 0.0.0.0 443 
...
domain <YourExternalGoogleIP> {
...
```
