### ISSUE TITLE
https://domain.com/@username

### ISSUE THREAD

**Issue by pescuu** [jorisvink/kore#199]
I have one question off the record. Is it possible in Kore to have urls like that `https://name.com/@username` ?

So the urls bellow would be valid.
```
https://name.com/@mike
https://name.com/@anna
https://name.com/@john
https://name.com/@username
```

**Comment by jorisvink** [comment]
Yes. Just make the page handler rules that you require.

e.g. dynamic ^/@[a-z]*$ handler

.joris

**Comment by pescuu** [comment]
Thank You vary much for Your respond. Thats really nice solution. It works, but I not quite sure how to get value form regex? It is neither get or post params. 

In other words. `https://name.com/@mike` how to get variable with _mike_ ?

**Comment by pescuu** [comment]
I will try that :)

**Comment by pescuu** [comment]
Last but not least :) (If there is obvious NO answer to the question please forget)

Is there a way to do similar thing with #. For example url `https://name.com/#apple` we would like to pull out everything after the hashtag. With @ everything works like You said. I can get everything what I want from req->path. But everything after # is invisible. I am conscious of the fact that it may be not even send to the server but I no sure so I decided to ask. 

greetings :)

**Comment by jorisvink** [comment]
# isn't sent to the server as part of the URI.

.joris

**Comment by jorisvink** [comment]
Everything after # I mean. It's local to the browser only.

.joris

**Comment by pescuu** [comment]
Thanks again. That's what I thought, no I am 100% sure. 

Best Regards
pescuu
