### ISSUE TITLE
includes/kore.h:32:25: fatal error: openssl/err.h: No such file or directory

### ISSUE THREAD

**Issue by jmukes97** [jorisvink/kore#200]
I cloned the repo and cd into the new folder. When i tried to run 'make' i got 

cc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -O2 -D_GNU_SOURCE=1 -c src/kore.c -o obj/kore.o
In file included from src/kore.c:27:0:
includes/kore.h:32:25: fatal error: openssl/err.h: No such file or directory
 #include <openssl/err.h>
                         ^
compilation terminated.
Makefile:143: recipe for target 'obj/kore.o' failed
make: *** [obj/kore.o] Error 1

I have openssl installed and I'm using debian linux Jessie. I was using this tutorial for installation. https://jorisvink.gitbooks.io/kore-doc/content/chapter1.html. Is there anything I'm doing wrong? From my untrained eye it looks like there is a header file missing.

**Comment by mrwert** [comment]
apt install libssl-dev

**Comment by jmukes97** [comment]
Thanks worked perfectly
