### ISSUE TITLE
Building and Securing REST API with Kore

### ISSUE THREAD

**Issue by bnlambert** [jorisvink/kore#201]
Greetings. I  appreciate the good work you have done. 
I wish to use Kore to build Rest APIs. After reading through the doc, I do not see any example on how to secure routes and authenticate requests (token authentication for example).
I wish to know if there are any possibilities of doing this.

Any clues on how to 
- Document Kore API with Swagger? (Share guides if any)
- load multiple files? (most examples load on single .so, how do we load or handle multiple .c in larger projects)
- Properly manage access levels and authorization?
- deploy Kore based apps in production environment?

Even if Kore does not support some of these features, clues/guides on how to work this around will highly appreciated.

Thanks

**Comment by jorisvink** [comment]
Hi,

Correct it seems the documentation on the web is missing the part about authentication blocks.
See https://github.com/jorisvink/kore/blob/master/conf/kore.conf.example (ctrl-f for authentication).

Basically authentication blocks allow you to define a preset method of how page handlers should be authenticated. The idea is that when you create a handler via static or dynamic you pass the authentication block that will be run *before* the handler is run.

Authentication blocks can look at headers, cookies, or can just the request. Kore however does not actually implement anything more then this, however using the authentication blocks you can implement most things yourself. Aka, load user data from a database/redis instance/whatever based on some cookie value, or some header value.

See the generic example (https://github.com/jorisvink/kore/blob/master/examples/generic/conf/generic.conf) and (https://github.com/jorisvink/kore/blob/master/examples/generic/src/example.c) on how the *auth_example* block is done.

**Comment by bnlambert** [comment]
Thank you very much for the info. 
Please share with a small example or clues on how to compose my routes(e.g. '/foo', '/bar/4') with different http methods (GET,PUT,DELETE) and return json. Please do.
Also I will like to contact you personally for mentor-ship.
Thanks

**Comment by jorisvink** [comment]
You can create "routes" (they're called page handlers in kore) using the static or dynamic keywords.

If you need to use regex in the handler paths use dynamic: dynamic ^/path/[a-z]*$ for example.

All methods are allowed in handlers, your code should limit this on its own by checking req->method for the appropriate expected verbs.

Drop by the IRC channel if you have more questions, please do not mail me for "mentorship". Only bugs and caveats should go to my inbox.

.joris

**Comment by bnlambert** [comment]
Ok, Thanks a lot.
