### ISSUE TITLE
PGSQL - no available connection

### ISSUE THREAD

**Issue by PauloMelo** [jorisvink/kore#202]
Hi Joris,

I'm getting pgsql error: no available connection.

I've set pgsql_conn_max at the config but I'm getting the error. I believe that it is because the counter is not initialized.
at kore_pgsql_register(const char *dbname, const char *connstring)
add pgsqldb->pgsql_conn_count = 0;

this as solved for me.
Regards,
Paulo Melo

**Comment by jorisvink** [comment]
Yup. Thanks for reminding me that this had to be fixed.

**Comment by jorisvink** [comment]
@PauloMelo Try with latest master https://github.com/jorisvink/kore/commit/4893a030a6819078d246646f50bfd46650d00620

**Comment by jorisvink** [comment]
poke?

**Comment by PauloMelo** [comment]
I'm sorry Joris for answering so late...
yes the latest master did the trick. 

Thank you very much.

**Comment by jorisvink** [comment]
Excellent!
