### ISSUE TITLE
KORE_DEBUG and memory question

### ISSUE THREAD

**Issue by AlexanderSheety** [jorisvink/kore#203]
Hello!

1. I did  this:

   TASKS=1 PGSQL=1 DEBUG=1 make 
   sudo make install
   kore create myproject 
   cd myproject
   kore build
   sudo kore run

   I had:
   pgsql built-in enabled
   tasks built-in enabled
   But i don't have debug. KORE_DEBUG isn't defined! What i did wrong ?

2. Kore has  11 memory blocks. Why do you use 11 blocks instead 1 large memory block ?

3. Documentation: You can skip chroot() and privdrops using -n and -r.
Can you explain how to do that ?

**Comment by jorisvink** [comment]
1) Once debug is builtin you have to enable it at runtime with the -d option.
2) One pool per power of 2 (starting at 8 bytes, ending at 8192).
3) Don't use kodev, but run kore directly (or the binary produced by kodev build if single binaries are enabled).

**Comment by AlexanderSheety** [comment]
-- 1.Once debug is builtin you have to enable it at runtime with the -d option.

I tried "kore -d run" but had only kore error. How to start runtime with the -d option?

**Comment by jorisvink** [comment]
$ kore -dfrnc conf/whatever.conf

The kodev helper does not take those arguments.

.joris

**Comment by AlexanderSheety** [comment]
Great Thanks Joris ! Debug is worked !

**Comment by jorisvink** [comment]
:)
