### ISSUE TITLE
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

### ISSUE THREAD

**Issue by karakasi** [jorisvink/kore#204]
Hi Joris, 
Congrats on your effort, it looks like an interesting library. 
I'm having this issue when trying to run the hello world example. I've reviewed the past issues and couldn't find something similar. I googled it but again no luck. My understanding on web stuff is anyway limited..Any clue would be much appreciated. 
I'm running on Debian 9. The configuration file is the default. The worker is running and I'm calling this: 
curl -k https://127.0.0.1:8888/
Best,
Kostas

**Comment by karakasi** [comment]
I just tried with Mozilla and by adding and exception for the certificate I can see the Hello World! in the browser. Is this a configuration issue?

**Comment by jorisvink** [comment]
No the certificates generated are self signed so having to add an exception is normal.

What happens when you run curl with -vk ?

.joris

**Comment by karakasi** [comment]
Thanks for the fast response. Here is the result: 
curl -vk https://127.0.0.1:8888/
*   Trying 172.25.1.1...
* TCP_NODELAY set
* Connected to (nil) (172.25.1.1) port 8080 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
* Curl_http_done: called premature == 0
* Closing connection 0
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

**Comment by jorisvink** [comment]
For whatever reason curl is not talking to the kore workers I believe. The fact the server hello fails to decode properly makes me think somehow you're talking over a plain connection rather then TLS.

.joris

**Comment by karakasi** [comment]
But TLS should be enabled if NOTLS is not defined at compile time, right?

**Comment by jorisvink** [comment]
Correct. I mean your Mozilla is connecting over TLS :-)

.joris

**Comment by karakasi** [comment]
OK I'll ignore curl for now then ;) Thanks!
