### ISSUE TITLE
sqlite3 mariadb support on the roadmap?

### ISSUE THREAD

**Issue by laoshaw** [jorisvink/kore#206]
this is interesting for embedded projects, where psql is too heavy, hopefully sqlite3 support will be added sometime.

**Comment by jorisvink** [comment]
Not really, sqlite3 is incredibly easy to stuff into your own applications so I don't see the benefit of kore scaffolding that into it's internals.

MariaDB, haven't considered it to be honest. Do they have an asynchronous API?

.joris

**Comment by jorisvink** [comment]
Closing, no feedback.
