### ISSUE TITLE
Does the SSE example still work?

### ISSUE THREAD

**Issue by nilesr** [jorisvink/kore#208]
I'm doing
```
git clone https://github.com/jorisvink/kore
cd kore/examples/sse
kodev run
```
and it builds properly and starts up, but then when I do `curl -kv https://localhost:8888/` I get

```
[ssl negotiation trimmed]
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
} [5 bytes data]
> GET / HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.55.1
> Accept: */*
> 
{ [5 bytes data]
< HTTP/1.1 404 Not Found
< server: kore (2.1.0-devel)
< connection: close
< strict-transport-security: max-age=31536000; includeSubDomains
< content-length: 0
< 

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
} [5 bytes data]
* TLSv1.2 (OUT), TLS alert, Client hello (1):
} [2 bytes data]
```

A 404 error.

My kore version is `2.0.0.release.r196.g2eab2f1-1`
I've tried building kore from the repo I just cloned giving version `2.1.0-devel` with the same behavior

**Comment by jorisvink** [comment]
Sure works, but note you're connecting towards localhost while the kore configuration for the domain specifies the ip 127.0.0.1. It matches the request using the Host header so it just throws a 404.

To be fair the example should have its domain set to '*' - but now you know why it is throwing a 404 :)

**Comment by jorisvink** [comment]
fyi i moved all examples to * for the domain directives now ... as they should've been.

**Comment by nilesr** [comment]
Thanks!
