### ISSUE TITLE
Where could I catch file request?

### ISSUE THREAD

**Issue by Globik** [jorisvink/kore#210]
I'd like kore server could resolve static files dynamically from some root directory. Now I struggle with it.
Where can I catch a file request from the browser? In a page function I added some printf to catch req->files and req->path. But files is nullable and path shows to me only the current path.

**Comment by Globik** [comment]
I think in the kore there is some global req->path that shows every single request from the browser or am I wrong about it? I am looking at video_stream example and wondering, why video.ogg exactly in the video folder but not in the assets? Why source src of this video container equal to simply video.ogg? But not video/video.ogg? And in the source code of video streaming I can't see any video path resolve not any req->path for this video??? What's a magic here?

**Comment by jorisvink** [comment]
The configuration has path directives that map which URI goes to which C function.

In the video example, there’s a regex that catches the URI and passes it to the video_stream function which looks on disk for the file under the videos directory.

The regex handler looks like this:

dynamic ^/[a-z]*.[a-z0-9]{3}$	video_stream

So any request like /video.ogg or /movie.avi for example all go to the same C function.

.joris

**Comment by Globik** [comment]
Aha, I see. And what TAILQ_ENTRY(video)	list; does it mean? Is it iteration list for all kinds of video under those dynamic url? Does it can also for the photos could be?

**Comment by jorisvink** [comment]
Euh no. That’s just specific to the video example. It’s just a list of files that are open via mmap.

.joris

**Comment by Globik** [comment]
Ah I see the magic. Here it is:
if (!kore_snprintf(fpath, sizeof(fpath), NULL, "videos%s", req->path))
It joins a  file name to the word "videos" which is a folder.

**Comment by jorisvink** [comment]
Glad you figured it out. Closing this issue now.
