### ISSUE TITLE
Structure Packing (alignment )

### ISSUE THREAD

**Issue by AlexanderSheety** [jorisvink/kore#211]
Hello Joris !
What do you think about [Structure Packing](http://www.catb.org/esr/structure-packing/) ?
Can you optimize your structures like "struct connection" for 64 bit machines ?

**Comment by jorisvink** [comment]
Unless you provide me with proof that the packing of the struct is negatively affecting your environment in a way of memory consumption *or* performance I don’t really see why.

Feel free to make a PR though if you think it’ll solve whatever problem you are having :-)

.joris

**Comment by AlexanderSheety** [comment]
I don't have problem with kore today. Kore is Great framework!
It will just add little more speed. You have more experience with servers. 
What's your opinion about "structure packing" (alignment) ?

**Comment by jorisvink** [comment]
Closing, not related to kore.
