### ISSUE TITLE
Linking errors when building single binary

### ISSUE THREAD

**Issue by milancurcic** [jorisvink/kore#212]
Hi Joris,

I really appreciate what you did with kore, thank you!

I am trying to build a single binary with the default app from kore-2.0.0 release.

```
kore create app
cd app
```

edit `conf/build`.conf for these settings:

```
single_binary=yes
kore_source=/home/milan/kore
```

and then type `kore build >& kore_build.log`, but get many linking errors (log attached).

Should LDFLAGS be set for this to work? What should I set it to? I don't see the place where the kore dynamic library is being built in this process.
[kore_build.log](https://github.com/jorisvink/kore/files/1471363/kore_build.log)

**Comment by jorisvink** [comment]
Do you have libssl-dev in your machine?

I recommend you use the latest master from github.

The release is old and doesn’t even support latest OpenSSL builds.

**Comment by milancurcic** [comment]
Thanks! I had libssl-dev. I switched to latest master and can build an executable now.

However, the executable cannot find the library, and it looks for it in the same directory:

```
$ ./app 
app: stat(./app.so): No such file or directory
```

Build log is:

```
building kore (/home/milan/kore)
building app (dev)
CFLAGS=-Wall -Wmissing-declarations -Wshadow -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wsign-compare -fPIC -Isrc -Isrc/includes -I/usr/local/include -g  -DKORE_SINGLE_BINARY  
LDFLAGS=-rdynamic -lssl -lcrypto -ldl 
adding config conf/app.conf
building asset builtin_kore.conf
compiling app.c
compiling builtin_kore.conf
app built successfully!
```

**Comment by jorisvink** [comment]
Edit the conf/app.conf and remove the load app.so directive and rebuild :-)

.joris

**Comment by milancurcic** [comment]
Fantastic, that does it, thank you!
