### ISSUE TITLE
How to make multi route ?

### ISSUE THREAD

**Issue by lagmanzaza** [jorisvink/kore#213]

**Comment by jorisvink** [comment]
What do you mean?

A single route that catches multiple uri’s?

dynamic ^/path/[a-z]*$ handler

.joris

**Comment by lagmanzaza** [comment]
I can fix it.
Now I have a quick question that is " How to response Data like Json" .

**Comment by jorisvink** [comment]
I’m sorry, I’m not going to help you figure out how to create JSON responses.

If you know how to send data back with Kore you should be able to figure out that part.

Hint, the kore_buf stuff can help you build responses.

.joris

**Comment by jorisvink** [comment]
Closing, no more response.
