### ISSUE TITLE
Gdb tutorial anybody?

### ISSUE THREAD

**Issue by micpes** [jorisvink/kore#214]
Hey,

I need some help in set up debugging environment. Unfortunately I failed to do it myself so I hope somebody would share his approach. I would like to run kore with gdb and have the possibility to use breakpoints. 

I think I got stuck in process debugging. 

What I do:
1. My conf looks like that
```
single_binary=yes
kore_source=/home/my/c/kore
kore_flavor=DEBUG=1
```
2. Build like that
```
kodev build
```
3. Run like that
```
gdb --args ./mysite -dnrf
```
4. I have my gdb running, now I make breakpoints at function named **page**
```
>>> b page
```
5. Gdb sees my function because I get 
**Breakpoint 1 at 0x407ce0: file src/mysite.c, line 13.**
6. Then I run kore inside gdb
```
>>> run
```
7. I reload site and expect to stop at breakpoint.

I also tried to **set follow-exec-mode child** but nothing change.

Does anybody can give me some advice what is wrong with this approach? And why when I load site in the browser I do not stop at breakpoint.

**Comment by jorisvink** [comment]
Use follow-fork-mode child instead :-)

.joris

**Comment by micpes** [comment]
I tried **follow-fork-mode child** but no success.

**Comment by jorisvink** [comment]
Are you sure your page handler is being hit then?

You getting the correct response from the call to the URI or are you getting 404?

.joris

**Comment by micpes** [comment]
I get correct response.
My **page** function looks like that, and when I refresh page number of second is updating.
```
int
page(struct http_request *req)
{
	char str[50];
	time_t t = time(NULL);
	struct tm tm = *localtime(&t);
	sprintf(str, "%d", tm.tm_sec);

	http_response(req, 200, str, strlen(str));
	return (KORE_RESULT_OK);
}
```

**Comment by micpes** [comment]
Ok I think I figure it out (partially).

When app is run like that:
```
./mysite -dnrf
```
Check process PID:
```
ps aux | grep myapp
```
Actually there would be three process related to myapp. Connect gdb to last process.
```
gdb myapp 13662
```
Now breakpoint in gdb works :)

ps.I still do not know why **follow-fork-mode child** apprache does not work.

**Comment by jorisvink** [comment]
How many worker processes do you spawn? My guess is that you have more then one worker and your initial connections hit the first worker while gdb is attached to the last one.

.joris

**Comment by micpes** [comment]
I don't have any workers section in my build.conf
Should I set workers to 1?

**Comment by jorisvink** [comment]
No that would be in your app conf,  not build conf.

.joris

**Comment by jorisvink** [comment]
Actually I realize now that running gdb like this will most likely attach to the keymgr process rather then your worker. Hence why you don’t see your breakpoint being hit :)

So just attaching to the correct process after starting it is your best bet. Unless you run with NOTLS since the keymgr wouldn’t exist then.

.joris

**Comment by AlexanderSheety** [comment]
Quick start tutorial with Netbeans IDE:
Netbeans IDE can debug dynamic libary
1.Install netbeans ide 8.2 c/c++ version and update components.
2.Run your project with flags -dfnrc and you must set 1 worker
3. Run netbeans with command - sudo ~/netbeans-8.2/bin/netbeans
4. Click menu: Debug->Attach Debugger 
5. you must type "kore" in the filter field.
6. you must choose last pid in the list.
7.Choose "create project" in the project field then click OK button.
8. you must add include files and source files to your project and save your project.
9. Add any breakpoints to your functions then send requests to your ip or host. Netbeans hooks automatically all breakpoints

You must only choose your pid and click ok button in the next time. Don't create project twice.

You can put this tutorial in your documentation joris. I think it helps.

**Comment by jorisvink** [comment]
Closing, no more discussion happening.

Thanks for the quick guide there @AlexanderSheety.
