### ISSUE TITLE
How to integrate third party lib?

### ISSUE THREAD

**Issue by traw** [jorisvink/kore#215]
How can we integrate third party lib specifically `cisco/libsrtp`, That support secure rtp protocol for media streaming?

**Comment by jorisvink** [comment]
You could link your kore app with it by adding the correct linker flags to ldflags under your app its conf/build.conf

.joris

**Comment by traw** [comment]
Thanks, I want to stream live webcam, which will use rtp protocol for transmission,  I know libsrtp does provide that functionality, but I don't know how to go about it because with secure transmission

**Comment by jorisvink** [comment]
Closing issue, not really any questions left here.
