### ISSUE TITLE
Example using kore_pgsql_query_params()

### ISSUE THREAD

**Issue by bbblitz** [jorisvink/kore#218]
It was really difficult to even find this function, since there's absolutely not documentation on it.
I'm also really nervous using it since it would be justifiable to remove it and say "wasn't documented, you shouldn't have used it".

I'd be willing to write one if need be.

**Comment by jorisvink** [comment]
Hi Alexander,

You are absolutely right. Documentation wise I’ve not spent nearly enough time on it.

I’ll gladly accept new documentation for core API functions.

.joris

**Comment by jorisvink** [comment]
Closing, no response in 4 months.
