### ISSUE TITLE
Can't run example task

### ISSUE THREAD

**Issue by Globik** [jorisvink/kore#222]
tasks.so undefined symbol : kore_task_bind_request
I've compiled kore with NOTLS=1
What for is NOHTTP? Why simbol is undefined if I have not defined those nohttp option?

**Comment by jorisvink** [comment]
Build with TASKS=1.

.joris

**Comment by Globik** [comment]
Ach soooo! Yes exactly it is!!! ldd kore.so shows that whate are in there. Thank you!)
