### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by shivshankardayal** [jorisvink/kore#224]
Please make a new release for stability reasons else it feels like it has not been active. Although history is there. I am using this to make applications with SPA frameworks and CockroachDB.

Mighty grateful for a nice small framework.

**Comment by jorisvink** [comment]
A new release will eventually happen.

Just not immediately now.

.joris

**Comment by Globik** [comment]
Not only a new release, but a kore's cookbook too.

**Comment by jorisvink** [comment]
Feel free to contribute.

I mostly hack on Kore for myself, the few examples available serve as the only real reference points for others.

.joris
