### ISSUE TITLE
Kore_task at exit gracefully workaround

### ISSUE THREAD

**Issue by Globik** [jorisvink/kore#227]
Hi, I'm trying to implement a gmain_loop from glib.h in to the kore_task.
It's ok though for now, but I'm wondering, how to properly to let the kore_task(is it a parent process? And gmain_loop is a child process?) to know that the loop is finished after ctrl + C?
So far I give a KORE_RESULT_OK where in a normal way is exit(0) or exit(1) if there is some error occured by initialization. Is there some way to send KORE_RESULT_NOT_OK?

**Comment by Globik** [comment]
There it is my experiment
https://github.com/Globik/kore.io_websocket/blob/master/websocket_6/src/websocket_6.c
Is there a way to cancel a kore_task?

**Comment by Globik** [comment]
Also I noticed that if I write like this in init function:
if(worker->id !=1) return (KORE_RESULT_OK);
The worker does not work. I have defined one worker in a config file. But what does it actually mean? Why the worker will not work?
If I'm comenting this line the worker with gmain_loop works like a charm.

**Comment by jorisvink** [comment]
I never used glib* stuff so I can't help you, sorry.

In general kore tasks are scheduled on pthreads and are *not* cancellable. A kore task needs to return KORE_RESULT_OK or KORE_RESULT_ERROR when completed.

**Comment by Globik** [comment]
Ah yeah, aha, kore_result_error. Thank you for reply.
