### ISSUE TITLE
Is it possible to use pkg-config in build.conf?

### ISSUE THREAD

**Issue by handicraftsman** [jorisvink/kore#228]

**Comment by jorisvink** [comment]
No the build.conf file does not allow forking out to the shell to grab output, this is beyond the scope of kodev’s abilities.

If you want this kind of flexibility you could just implement the build procedure yourself using plain Makefiles or whatever build system you prefer.

In you are building a dso it should be pretty straight forward to figure out how to do that if you are familiar with posix systems. Just add the relevant Kore build options to cflags as well.

If you are building a standalone binary, please look at Kore’s Makefile, there is a obj target and an environment variable that dictates where built objects go under. This is how kodev does it as well, it builds all Kore objects into a local directory and finally links everything together. For standalone you’d want the KORE_SINGLE_BINARY define to be present.



.joris

**Comment by handicraftsman** [comment]
Thanks
