### ISSUE TITLE
Event driven (epoll/kqueue) architecture with per CPU worker processes

### ISSUE THREAD

**Issue by Globik** [jorisvink/kore#229]
In a websocket example, in a conf file worker = 4
I'd like to increment an integer global_count every time when a new connection arrived.
In websocket_connection I do like so global_count++, but in a log I can see only that every worker uses those global variable on your own. As if I have four global_count with the same name.
Is there a way to bring the workers to synchronisation? I have tried the mutexes to use by incrementing but the same.
When worker = 1 then all works as expected.
I opened 10 websocket connections but global_count shows to me only 4 or 6 connections. Any hint how to solve this issue?

**Comment by jorisvink** [comment]
Each worker process is a real Unix process so yeah they don’t see each other’s address space :)

You could solve this by using the built in messaging framework to send messages from one worker to the other saying “hey I got one more connection” or “hey I lost a connection”.

Another way is to use shared memory and use atomic operations on it to increment or decrement a counter living in that memory.

.joris

**Comment by Globik** [comment]
Is there the way to catch the current worker id in messaging framework?
Let's say, here a new websocket connection came and I know that application uses total 4 workers, but I don't know which exactly of 4 workers is current that holds a newly connection. It can be randomly: or 0 or 1 or 2 or 3.

**Comment by Globik** [comment]
Is this that what I think of?
msg->src ?

**Comment by jorisvink** [comment]
Yup, the src member is the id of the worker who sent it :)

.joris

**Comment by Globik** [comment]
I'm wondering which worker is a parent process? Should I determinate a parent process on init stage?
In order to semaphore init and then semaphore destroy.

**Comment by jorisvink** [comment]
You could implement the ‘void kore_parent_configure(void)’ function which is run on the first process (which is ... the parent).

All worker processes spawn from this parent process and will inherit whatever you setup when they fork().

.joris

**Comment by Globik** [comment]
Is this what is for example in generic.conf file?
load		./generic.so		example_load
"example_load" is symbol for kore_parent_configure?

**Comment by jorisvink** [comment]
No. That’s just a callback for the workers when the module is loaded.

I meant kore_parent_configure() just add that function to your code and kore will call it when the parent starts.

.joris

**Comment by Globik** [comment]
I am looking into the kore.h 
Does it mean that this kind of functions are custom functions?
kore_msg_init(void);
void		kore_msg_worker_init(void);
void		kore_msg_parent_init(void);
void	kore_parent_configure(void);
void	kore_worker_configure(void);
void kore_worker_configure(){
printf("Halloooo! Am I a parent process?");
}
kore_parent_configure()
I must try it.

**Comment by jorisvink** [comment]
Just kore_parent_configure() and kore_worker_configure()

.joris

**Comment by Globik** [comment]
Aha, I see, I see. Need just to write this function. And kore engine make a call for you. Excellent.
Is there an antipod? kore_parent_deinit()? Or let's say other: is kore providing a signal termination? Or any status that process is about finishing?

**Comment by jorisvink** [comment]
There is no cleanup function, but it seems reasonable. I’ll see what I can do about.

.joris

**Comment by Globik** [comment]
I added shared object and semaphores into the websocket sample. Also added atexit handler to the kore_parent_configure(). What I have noticed that workers also inherit shared object(mmap). Their count are also 4 : )
The concept works though. So far. Opened 10 connections and the shared object count shows exactly 10.
https://github.com/Globik/kore.io_websocket/blob/master/websocket_1/src/websocket_1.c
