### ISSUE TITLE
I have 2 cores processor on board, but total workers are 4. Why?

### ISSUE THREAD

**Issue by Globik** [jorisvink/kore#231]
Using built in kore message system.
Sometimes kore_send_msg sends to websockets messages and then status 139 segmentation faults.
Worker 1 holds a task, also a websocket connections. Worker 1 send msg != worker 1.
I got a feel as if worker id 0 and worker id 1 sharing the same memory address. And as a result I have two the same messages on websocket frontend, and then worker 1 restarts with a task together...

**Comment by jorisvink** [comment]
You either configured your Kore app to spawn 4 workers or something else is messed up.

Regarding your segmentation faults, I glanced at your code and honestly it’s such a mess I’m completely not surprised you are crashing.

I think you are fully misunderstanding how Kore is designed and works and you are trying to shove multithreading down it’s throat for some reason, even with the Kore tasks available.

Worker processes won’t ever share connections or memory unless you changed that.

.joris

**Comment by Globik** [comment]
Is there the  way to check if message's system successfully initialized?
This kore_msg_worker from:
kore_msg_send(KORE_MSG_WORKER_ALL,KORE_MSG_WEBSOCKET, frame->data, frame->offset);
sends no message it equal to current worker id process(I have worker id=1). But what if at the moment worker id=0 is not initialized?
The problem actually when I press ctrl+C and then again start the kore, I do not refrech a browser tab. So segmentation fault as a result. 
```
building websocket_8 (dev)
CFLAGS=-Wall -Wmissing-declarations -Wshadow -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wsign-compare  -fno-strict-aliasing -fPIC -Isrc -Isrc/includes -I/usr/local/include -DKORE_NO_TLS -DKORE_USE_TASKS -g   -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include -I./src -I./plugin 
LDFLAGS=-shared -L/usr/lib/i386-linux-gnu -lglib-2.0  -ljansson  -ldl 
nothing to be done!
[parent]: running on http://127.0.0.1:8888
ignoring "tls_dhparam" on line 6
ignoring "certfile" on line 16
ignoring "certkey" on line 17
[parent]: kore is starting up
[parent]: tasks built-in enabled
[wrk 1]: worker 1 started (cpu#1)
[wrk 1]: kore_worker_configure()
Entering init.
[wrk 1]: Worker ID 1 : 0xb77c8028
after state.
 Setup Glib 
Plugins folder: /home/globik/kore.io_websocket/websocket_8/plugin
LOADING PLUGIN libecho.so
Created!
Echo Plugin Initialized!
sess watchdog started
[wrk 0]: worker 0 started (cpu#0)
[wrk 0]: kore_worker_configure()
Entering init.
[wrk 0]: Worker ID 0 : 0xb77c8008
[wrk 1]: some path /connect
[wrk 1]: 0xb77b6090: http_request
[wrk 1]: 0xb7073f70: connected, by name alice: 
creating plugin result...
[wrk 1]: J_PLUGIN_OK_WAIT: i'm taking my time

j_plugin_res_destroy
[wrk 1]: TRANSACTION: FUCKER_Fucker_AS_ANSWER_FROM_ECHO_PLUGIN

[wrk 1]: worker memory 1 : 0xb77c8028
[wrk 1]: worker->active_hdlr is NULL! id: 1
[wrk 1]: some src in broadcast : alice
[parent]: worker 1 (3249)-> status 139
[parent]: worker 1 (pid: 3249) (hdlr: none) gone
[parent]: restarting worker 1
[wrk 1]: worker 1 started (cpu#1)
[wrk 1]: kore_worker_configure()
Entering init.
[wrk 1]: Worker ID 1 : 0xb77c8028
after state.
 Setup Glib 
Plugins folder: /home/globik/kore.io_websocket/websocket_8/plugin
LOADING PLUGIN libecho.so
Created!
Echo Plugin Initialized!
sess watchdog started
^CStopping gateway, please wait...
[wrk 0]: parent gone, shutting down
ending watchdog loop
[parent]: server shutting down
[parent]: waiting for workers to drain and shutdown
[wrk 0]: at exit worker 1 occured
ENTERING plugin_message_free
leaving thread from PLUGIN_HANDLER
Destroyd
Bye!
Stopping gateway, please wait...
[wrk 1]: TTTTTTTTTTTTTTTTTTTTTTTTTTTTTask msg: mama
[wrk 1]: Task finished.
at exit handler occured.
[wrk 1]: at exit worker 1 occured
[parent]: worker 0 (3248)-> status 0
[parent]: worker 1 (3267)-> status 0
[parent]: goodbye

```

**Comment by Globik** [comment]
Yup, with one worker(worker 1 in conf file), it is working as expected.
If two and more workers so beginns the problems.
Exactly so that I call only one call of kore_send_msg from worker one to worker null, but it gives two calls.
Worker null becomes two messages from worker one althou I sending exactly one in my code. It occures from time to time not always and only if I longly the browser tab not refreshing. 

*****
Sorry for my messy C code. I know you are in shock. But I am a newcomer in C and in kore.c
Any way I am falling in love with kore.c
Thank you so much for your opensource kore.c

**Comment by Globik** [comment]
"I think you are fully misunderstanding how Kore is designed and works "
Yup. Kore.c is not express.js, is not koa.js, is not symphony.php they all having a lot of tutorials and "receptions" in internet.
Kore is unique.

**Comment by jorisvink** [comment]
If it occurs with two workers my guess is still that you somehow messed up your multithreading code.

I recommend you take a good hard look at your code and figure out if somehow two threads are doing things with the same objects at the same time.

.joris

**Comment by Globik** [comment]
I'm giving up for now. I will play with one worker. Just from interest. For the study. 
Thank you about two threads. Later I ll take a look.

**Comment by Globik** [comment]
I'll be back.
