### ISSUE TITLE
Could you please explain conditions in http.c

### ISSUE THREAD

**Issue by Houdini** [jorisvink/kore#233]
Hi, could you please explain more about http.c, method http_argument_add.
It contains these lines:

```
		if (p->method != req->method)
			continue;
		if (strcmp(p->name, name))
			continue;
```

Why do we relly need this?

Thanks

**Comment by jorisvink** [comment]
Why do you think we don’t?

Without those kore wouldn’t be able to match the parameter against a configured params block option.

.joris

**Comment by Houdini** [comment]
Ough, it's from config. Thanks a lot!
