### ISSUE TITLE
A parser for a build.conf file is buggy

### ISSUE THREAD

**Issue by Globik** [jorisvink/kore#234]
Some way is buggy. 
If build.conf file fresh default from your repo all is ok.
When I start intensivly edit my build.conf - adding the new needed includes directories to the cflags sections - all is breaks. In a console output it shows ok but can't find a needed directory with a needed header file. Randomly every time after editing the build.conf it gives me the random error output that compiler can't find a header file. Every time cant find a different header file. 
1. Can't find for example glib.h
OK may be I missed some way to add a directory for glib.h in build.conf. OK I edited build.conf. Though I am NOT missed it!
2. Again can't find agent.h. Again hacking build.conf, though i'm not missed agent.h
3. Again can't find glib.h What the f? In the 1. step I checked it out!
Though I know it is in place.
Is there a way standartly to write cflags? I mean what I can and what I cannot? Can I plus? cflags+=-I/blabla.h ? Can I tabulize, can I copypasting?
Today I am tired. 5 houers takes me to understand that something wrong with the parser that parses those build.confs!
In my code there are a tones of headers. No chance for using pkg-config, soooo I manually or by copypasting a tones of headers paths to the build.conf and as a result something breaks.

**Comment by Globik** [comment]
What does it mean?
char			*args[32 + CFLAGS_MAX]; ??
32 letters in line?

**Comment by jorisvink** [comment]
Stop.

You're obviously not getting how this build.conf works.

First off the cflag directives are explained INSIDE the build.conf file and how they work and should be used. As I mentioned before you cannot use external commands inside of the build.conf file. If you need more flexiblity write a Makefile that does all that for you and build your own module.

> What does it mean?
> char *args[32 + CFLAGS_MAX]; ??
> 32 letters in line?

You shouldn't write C.
