### ISSUE TITLE
lock files between workers

### ISSUE THREAD

**Issue by AlexanderSheety** [jorisvink/kore#235]
Example:
I have 2 workers:

First: Read file
Second: Remove file 

What is the best method to provide race condition ? Link and Unlink files ? Can you provide some short code example Joris?

**Comment by jorisvink** [comment]
Your system isn’t going to unlink a file until all file descriptors are closed. Which means even if worker 2 unlinks the file it’ll be readable on worker 1 if it already had it open.

This is inherit to all posix systems, what problem are you trying to solve?

.joris

**Comment by AlexanderSheety** [comment]
Thanks joris !
I have kore server who stored files and removed files by requests.
Is it dangerous to use "remove(const char* __filename)" with multiple workers ?

**Comment by jorisvink** [comment]
> Is it dangerous to use "remove(const char* __filename)" with multiple workers ?
> 

No, but if you are using files I’d just call unlink instead of remove(), as remove() can be called on files or directories. Just to be explicit your intent is to unlink a file.

**Comment by AlexanderSheety** [comment]
> No, but if you are using files I’d just call unlink instead of remove(), as remove() can be called on files or directories. Just to be explicit your intent is to unlink a file.

Great thanks Joris!
