### ISSUE TITLE
Connecting kore to kore

### ISSUE THREAD

**Issue by Dutch1337** [jorisvink/kore#239]
load		./microrouter.so
bind	 192.168.178.200 8889 cluster_peer_auth

While exploring Kore I found this feature using config variable bind where Kore can (almost) accept non-http ssl connections.

Currently I did not found an easy method to Kore to another Kore. This feature would mean Kore applications could easily connect to eachother for fail-over, cluster and distributed computing purposes. 

Possible API addition for kore-kore connections:
int kore_connection_connect(struct connection *c, char *ip46port );
void net_send_queue will send a length to create a boundary in a kore-kore raw streams, so entire raw messages will be received in a single callback by the application running in another kore instance.
   send data format: <32bit len><x byte data>

This simple format could also be used to accept connections from other programs or even languages.
I am trying to build a microservice router so this feature would ease the pain :)

What are your toughts on kore-kore connections?

Kind regards,
Sebastiaan

**Comment by jorisvink** [comment]
I've done this before.

I don't think a new API would be needed for this as it's pretty straight forward. You just setup a socket, connect it to somewhere and wrap it in a connection data structure and hand that over to the worker.

Then you can use net_recv_queue() to setup the callback for when X amount of bytes come in.

Take a look at the tls-proxy example (examples/tls-proxy/src/proxy.c), it will use a connection callback for each incoming connection and does basically what you described.

**Comment by Dutch1337** [comment]
Thanks! I'll have a look :)

**Comment by Globik** [comment]
Hi, @Dutch1337  are you lucky to bind any loop lib from third party  with kore?

**Comment by jorisvink** [comment]
On Mon, May 07, 2018 at 06:25:07PM +0000, Globik wrote:
> Hi, @Dutch1337  are you lucky to bind any loop lib from third party  with kore?

Why on earth would you want to use an external i/o loop when kore
provides this stuff?

.joris
