### ISSUE TITLE
No OpenSSL in /opt

### ISSUE THREAD

**Issue by apfohl** [jorisvink/kore#24]
I haven't installed my OpenSSL to ```/opt```, due to the fact that I've installed OpenSSL through ```brew```. I also tend to not install anything into /opt, because I think that software that is not shipped with the OS should not be installed to ```/opt```. Instead it should be installed to ```/usr/local```. That is for example the place where FreeBSD installs all it's ports.

What do you think, could a rework on this topic be reasonable?

**Comment by jorisvink** [comment]
/opt/local is included in the Makefile for OSX for macports reasons, I remember now.

So keeping that as is and closing this issue, if you do come up with a reasonable solution please open a new issue or pull request =)
