### ISSUE TITLE
How are assets supposed to be handled?

### ISSUE THREAD

**Issue by BrettRToomey** [jorisvink/kore#240]
I'm running into a lot of issues when trying to serve files. I'm hitting a lot of inconsistencies between the examples on master, `homebrew` version, the latest release and master branch. As far as I can tell, master is the only one that still "works."

What're the differences between `kore` and `kodev`? Previously I was using `kore run`, but now I'm getting the warning: `kore: did you mean to run `kodev´ instead?` Is the `kore` utility now deprecated? I couldn't seem to find documentation on any of this.

With a build from the master branch, I managed to get the following assets building and serving:
```
  7 domain * {
  8     certfile    cert/server.crt
  9     certkey     cert/server.key
 10 
 11     static  /   asset_serve_index_html
 12     static  /js/vue-2.5.16/vue.js asset_serve_vue_js
 13 }
```
Which leads to my next question: if I were to have many js files is there a way for me to nicely add them or am I going to need to add them 1-by-1/use nginx?

I'm really excited to try the project out in depth and look forward to contributing and fixing/updating any docs as necessary!

**Comment by jorisvink** [comment]
> I'm running into a lot of issues when trying to serve files. I'm hitting a lot of inconsistencies between the examples on master, homebrew version, the latest release and master branch. As far as I can tell, master is the only one that still "works."

Yup, the documentation is outdated. Some of the examples are still using the old way. I hope to get around updating everything before I push out a new tagged release.

> What're the differences between kore and kodev? Previously I was using kore run, but now I'm getting the warning: kore: did you mean to runkodev´ instead?Is thekore` utility now deprecated?

Correct, the kodev utility completely replaces the old kore create etc. It made sense splitting up the build utility from the actual webserver binary. The kodev utility can do so much more these days as well so it was the right choice.

> With a build from the master branch, I managed to get the following assets building and serving

For normal static assets that do not need any meddling that is approach I will be promoting. In combination with the mime_types from the build.conf it allows for an easy approach to static files.

> Which leads to my next question: if I were to have many js files is there a way for me to nicely add them or am I going to need to add them 1-by-1/use nginx?

Not currently. I have an idea in the pipeline to make this easier as I've been bitten by it myself multiple times :)

**Comment by BrettRToomey** [comment]
Alright! Thanks for the quick response! I've been playing with it some more, and kind of figured out each of these answers, but it's really nice to get my suspicions confirmed. As for contributing, are there any tasks for a newcomer to dive into? I'd be happy to help!

**Comment by jorisvink** [comment]
> As for contributing, are there any tasks for a newcomer to dive into?

Honestly? Pick something you'd like to see in Kore and just start hacking :)

**Comment by BrettRToomey** [comment]
Will do! Thanks for all the help!
