### ISSUE TITLE
Validator custom error page

### ISSUE THREAD

**Issue by LarsGardien** [jorisvink/kore#247]
I want to be able to use a regex validator, but instead of giving me a "Secure Connection Failed" error, I want to be able to use a custom error page.

Does Kore have any way of achieving this?

**Comment by jorisvink** [comment]
How is a validation failing giving you a connection error?

Show me your setup.

**Comment by LarsGardien** [comment]
I've already figured it out. I was under the impression that a route function would not be called if the parameter validators failed, but this is not the case. Closing the issue.
