### ISSUE TITLE
No response (Docker)

### ISSUE THREAD

**Issue by sigod** [jorisvink/kore#248]
I use this Dockerfile:

```
FROM gcc:8.1

ADD kore-master /kore

WORKDIR /kore
RUN make NOTLS=1
RUN make install

WORKDIR /kore/examples/headers

EXPOSE 8888

CMD ["kodev", "run"]
```

When I try to open localhost:4000 (I use `-p 4000:8888`) it says "localhost didn’t send any data". I tried skipping `NOTLS`, https url and ubuntu:18.04 as parent docker image. Results always the same.

kore-master is the latest master at this moment.

I'm new to Docker and kore. So, I might've misunderstood something.

**Comment by sigod** [comment]
kodev run doesn't output anything.

**Comment by jorisvink** [comment]
It sure does when running it in a non docker environment. I don’t know how docker redirects the apps stdout however.

.joris

**Comment by sigod** [comment]
`CMD ["kore", "-frnc", "./conf/headers.conf"]`

It stays silent if both `r` and `n` are provided. Otherwise, it outputs:
`[parent]: running on https://127.0.0.1:8888`

And `kore: missing a chroot path` or `kore: missing runas user, use -r to skip it`. It depends on which option I omit.

Providing `runas root` in the config instead of `r` doesn't help the situation.

**Comment by jorisvink** [comment]
So kodev run or kore -frnc config will definitely output things on stdout.

If you omit the -f (foreground) flag kore will use staling instead.

Again I don’t know docker, but something sure seems fishy there.

.joris

**Comment by jorisvink** [comment]
syslog, not staling :)

**Comment by sigod** [comment]
I found the cause. It's because config was telling Kore to listen on 127.0.0.1, I changed it to 0.0.0.0 and it started working. Debug build helped a lot.

So, none of the examples are Docker friendly.

**Comment by sigod** [comment]
I'm not talking about pleasing Docker. I'm talking about being friendly with users. In this case, those who choose to use Docker.

Listening not on localhost would be weird in examples though. And I'm not sure how obvious this problem is for experienced Docker users. I did ask a bunch of people and no one could figure out the problem. So, maybe mention it in the documentation? Or this issue could be enough.

**Comment by jorisvink** [comment]
That’s exactly the point I was trying to make :)

For the examples anything other than local host is bad. On the other hand, why not add a specific example using Docker?

Then any quirks to get it to run under Docker can be documented there.

**Comment by jorisvink** [comment]
Closing, no further responses and I don’t really care about Docker.

If someone adds a Docker example I’ll merge it in.
