### ISSUE TITLE
Benchmarks on TFB

### ISSUE THREAD

**Issue by sigod** [jorisvink/kore#249]
As you wrote in #57:
> There are literally a dozen ways of creating benchmarks which show at most a base line of what something is capable of.

I agree. But having Kore in something like https://github.com/TechEmpower/FrameworkBenchmarks would've been nice. Users can see more or less fair comparison without a need to make their own benchmarks. It also acts as an advertisement.

**Comment by jorisvink** [comment]
I’m not convinced on the value of those benchmarks except giving skewed views of the tested servers / frameworks.

So I personally won’t be spending time on writing those.

**Comment by jorisvink** [comment]
Closing, no further response from author after 2 weeks.
