### ISSUE TITLE
On FreeBSD: cli_spawn_proc: No such file or directory

### ISSUE THREAD

**Issue by mkastner** [jorisvink/kore#28]
I've got a problem running a skeleton app on FreeBSD. It works fine on OSX, though.

I've installed kore 1.2.1-release on FreeBSD(10.0).
Then I did
$ kore create test
Then
$ kore run

And this is, what I get as a result:

compiling test.c
kore run: cli_spawn_proc: No such file or directory
kore run: subprocess trouble, check output

BTW: Which output should be checked?

**Comment by jorisvink** [comment]
Hey,

On FreeBSD 10 clang is the default compiler while Kore expects gcc.

This should be properly mentioned in the documentation, which I will update once I get back from holiday.

You can do this however to make Kore use clang:

# kore clean
# CC=clang kore run

// Joris

**Comment by apfohl** [comment]
I also tried on FreeBSD 10.1-RELEASE and got:

    $ env CC="clang" kore run
    compiling kore.c
    kore built succesfully!
    [parent]: running on https://127.0.0.1:8888
    [parent]: kore is starting up
    [parent]: tasks built-in enabled
    kore: kore_worker_init(): shmget() Function not implemented

I compiled with ```task``` support.

**Comment by apfohl** [comment]
Sorry my fault. I am trying to run Kore in a jail. So the jail needs to have ```allow.sysvipc=1```. Works now.

**Comment by mkastner** [comment]
Ok, I see. So clang has needs to be assigned to CC on FreeBSD. Sorry, I didn't notice that. Builds like a charm now.
