### ISSUE TITLE
brew: /opt/local

### ISSUE THREAD

**Issue by thorduri** [jorisvink/kore#29]
Using brew 0.9.5, it's installing everything into /usr/local, there are no /opt/ directories, resulting in:
ld: warning: directory not found for option '-L/opt/local/lib'

Not harmful but annoying. What versions of brew are using those and are they being targeted for support?

**Comment by jorisvink** [comment]
If I remember correctly /opt/local/ is used by macports, and it's included for that reasoning.

**Comment by thorduri** [comment]
@jorisvink you are correct. Closing, thanks.
