### ISSUE TITLE
`kore run` gives error: missing a username to run as

### ISSUE THREAD

**Issue by olleharstedt** [jorisvink/kore#31]
[parent]: running on https://127.0.0.1:8888
kore: missing a username to run as

Solution to this?
This is from the generic example.

**Comment by jorisvink** [comment]
Hey,

Is this under Linux (if so what distro), any of the BSD's or OSX?

**Comment by olleharstedt** [comment]
Yeah, Ubuntu.
But solved by entering `runas myuser` in config.

**Comment by jorisvink** [comment]
Yeah, however Kore is suppose to figure out the user you are running as itself if not specified in the configuration.

Somehow getlogin() is failing, is there anything special about your setup in which you attempted to run the example?

**Comment by olleharstedt** [comment]
Ah! It works without config if I run it from the usual Ubuntu terminal. Before I run it from ConqueTerm within Vim.

**Comment by jorisvink** [comment]
Ah yeah, that would explain it as probably isn't a controlling terminal causing it to return ENXIO most likely.

I'll close this issue.
