### ISSUE TITLE
Caching support?

### ISSUE THREAD

**Issue by alexreg** [jorisvink/kore#32]
I was wondering if you plan to implement caching of requests. Even a simple feature like a function to spit out the cached response (within a page handler) would be very useful. Thoughts?

**Comment by jorisvink** [comment]
Hey,

That idea has crossed my mind yes. I was essentially thinking of adding something in the way of:

```
if (http_response_cached(req))
    return (KORE_RESULT_OK);
```

Which would basically take look at the entire request in req, and if cached it would return that one immediately.

Adding something to the cache could be something in terms of:

```
http_response_cache(req, status, data, len, timeout);
```

Which would have similar semantics to http_response(...) as in that it also responds to the client besides entering it in the cache with the given timeout.

The biggest issue at hand is that I would like the see the cache shared between worker processes instead of per worker process.

**Comment by alexreg** [comment]
Hey,

Thanks for the reply. It's great to see you're actively working on this project – right now it seems like the best solution to writing clean web applications/servers in C! (I'm only just getting going with it, but it looks well-structured I'm please to say.)

Regarding the mechanism for caching, that seems quite sensible. However, in terms of deciding when to use the cache, it might be a good idea to support more fine-grained control. For example, even when the request data is exactly identical to a cached version, and the requester IP address is also the same, one may not wish to use the cached response. Of course, timeouts or something similar would help (as you hint above), but it may also be helpful to do a quick server-side (perhaps database-related) check, to decide whether to return the cache or reprocess everything. Hence I was thinking some pattern/maxim like the following might be ideal.

```
if (some_condition_is_satisfied && http_response_cached(req))
    return (KORE_RESULT_USE_CACHE);
else
{
    // process the request manually...
    return (KORE_RESULT_OK);
}
```

How does this sound to you?

**Comment by jorisvink** [comment]
I agree with the approach of letting a developer return something like KORE_RESULT_USE_CACHE so they themselves can decide on wether or not to use it if available.

I might poke at a first implementation of caching in the near future as soon as real life allows some time.

**Comment by alexreg** [comment]
Okay, excellent. Might there also be a possibility of having some sort of key/value store for the latest cache of the page (if it exists)? Then the page handler could compare this to current values from the database. Might be handy.

Cheers! Let me know how that goes... I'm happy to provide any input, or test even.

**Comment by alexreg** [comment]
Hi Joris. Any progress on this yet, by chance? :)

**Comment by jorisvink** [comment]
Yups. Should be hitting the tree next week.

.joris

**Comment by alexreg** [comment]
Excellent; glad to hear. :)

**Comment by jorisvink** [comment]
Little update, cache support coming next week due to real life commitments this once sadly.

Hang in there :)

**Comment by alexreg** [comment]
No worries… thanks for the update!

**Comment by alexreg** [comment]
Hi Joris, how is progress on the caching functionality? :)

**Comment by jorisvink** [comment]
Hi.

As you might have guessed, slow. Keeping this issue open so I don't forget it.

**Comment by alexreg** [comment]
Okay, sure!

**Comment by denji** [comment]
I think we need an ETag-HTTP as an alternative to DateTime Stumping

**Comment by alexreg** [comment]
ETag-HTTP is for client-side cacheing. We're talking about server-side cacheing here.

**Comment by jorisvink** [comment]
Correct, server side caching is a whole other ballpark.

@alexreg apologies for dragging this one out quite long, but you'll see this in 1.3.0 which is the next release after 1.2.3.

**Comment by alexreg** [comment]
@jorisvink No worries. I’ll look forward to it in the 1.3.0 releas!

**Comment by jorisvink** [comment]
Something like this will finally hit Kore for the 2.0.0 release. Apologies for the very long stretch and empty promises =)

**Comment by jorisvink** [comment]
Nope, after some more consideration this won't happen. This just doesn't feel right to add to Kore as its easily doable by developers themselves in their modules.
