### ISSUE TITLE
Support for static assets

### ISSUE THREAD

**Issue by apfohl** [jorisvink/kore#35]
I already discovered the possibility to compile assets into the application, but wouldn't it be nice if one could serve static assets like JavaScript libraries or CSS from a folder?

**Comment by jorisvink** [comment]
Hey,

Nothing stops you from doing that from a module, however the core part of Kore won't have any support for reading files from disk itself.

.joris

**Comment by jorisvink** [comment]
Is there btw a specific reasoning why you would need that in base?

**Comment by apfohl** [comment]
No, it makes absolutely sense to put this into a module. I just did not thought of.
