### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by james2doyle** [jorisvink/kore#36]
Just curious when the next release is. There have been [some nice commits](https://github.com/jorisvink/kore/compare/1.2.1-release...master) since the last release. I installed kore via brew.

**Comment by jorisvink** [comment]
Hi,

1.2.2 should hit next month or so after cache support and http2 has gone in.

.joris

**Comment by jorisvink** [comment]
FYI,

Will be making preparations for 1.2.3 today, cache support and http2 is delayed due to real life unfortunately.

(also closing this issue)

.joris
