### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by james2doyle** [jorisvink/kore#38]
Looks like there have been a [few commits to master](https://github.com/jorisvink/kore/compare/1.2.1-release...master), but the latest version is still 1.2.1. When is the next expected release?

**Comment by jorisvink** [comment]
Soon.

Version is currently bumped to 1.2.2-rc1 in preparation for 1.2.2. Tagging and actual release next few days while I am traveling.

**Comment by james2doyle** [comment]
ok cool, thanks

**Comment by jorisvink** [comment]
1.2.2 has been released.

Closing this issue.

**Comment by james2doyle** [comment]
Thanks
