### ISSUE TITLE
Issues finding files to compile under Ubuntu 14.04 + Vagrant

### ISSUE THREAD

**Issue by Geenz** [jorisvink/kore#39]
It seems that Kore has a hard time finding all of the files it needs to compile on Ubuntu 14.04.  If you keep everything in the ```src``` directory, everything seems fine.  But if you have any sub-directories to src, it doesn't seem to be capable of recursing into them and finding the correct files to compile.

The above seemingly works fine under OS X and FreeBSD from my tests, but not Ubuntu for whatever reason.  I haven't tested under any other OSes.

**Comment by jorisvink** [comment]
Hmm. Will look at it as soon as I can.

In the mean time, does it spew out anything at all or just not use the files in subdirs?

**Comment by Geenz** [comment]
It doesn't spew anything, ```cli_find_files``` simply doesn't recurse into sub directories beyond the directory it's initially given.  I initially noticed something odd was going on when I was getting linker errors for one of my modules.

After tinkering with stat, it seems as if it's counting everything in src as a file, so instead of ```src/myDir/``` being seen as a directory, it's instead counted as a file and ```cli_find_files``` doesn't recurse any further.

I'm not entirely sure what's going on here.  It could be a bug in Ubuntu, it could be a bug in Vagrant, or it could be a bug in VirtualBox that may be causing this.

**Comment by jorisvink** [comment]
Interesting. I'm not behind a laptop right now, will look as soon as possible.

Is this perhaps something SElinux related?

**Comment by Geenz** [comment]
That I couldn't tell you.  If I have time later today I'm going to hack around, see if I can find a work around that works on the platforms that Kore supports.

**Comment by jorisvink** [comment]
I cannot reproduce this on Ubuntu 14.04 server release, not running under Vagrant however.

Are you using VirtualBox as your vagrant vm thing?

**Comment by Geenz** [comment]
Yes.

**Comment by jorisvink** [comment]
Ok, will try it out later.

If your code is located under a vagrant share, what happens if you try compiling it on something non virtualboxfs-ish like ext4fs on the ubuntu box?

**Comment by Geenz** [comment]
Thanks, this seems to have fixed it.  Would have responded sooner, been fairly busy.

**Comment by jorisvink** [comment]
> Thanks, this seems to have fixed it.

:+1:
