### ISSUE TITLE
Get Client IP Address

### ISSUE THREAD

**Issue by dallbee** [jorisvink/kore#41]
It would be nice to be able to get information about a client that is not included in the HTTP headers, such as an IP address.

**Comment by jorisvink** [comment]
That can already be done. The connection data structure holds this.
In a page handler this is available under the http_request as the 'owner' member.

```
switch (req->owner->addrtype) {
case AF_INET:
    /* IP is under connection->addr.ipv4 */
    break;
case AF_INET6:
    /* IP is under connection->addr.ipv6 */
    break;
}
```

**Comment by dallbee** [comment]
Don't know how I missed that. Spent about 30 minutes looking for it.

Thanks!
