### ISSUE TITLE
Pool Exhausted

### ISSUE THREAD

**Issue by byzhang** [jorisvink/kore#43]
I'm running the hello world example (w/o SSL). When I test it with 
```
weighttp -n 2000000 -t 8 -c 1024 -k http://127.0.0.1:11111
```
Some messages are printed:
```
[wrk 0]: worker 0 started (cpu#0)
[wrk 0]: pool http_request_pool is exhausted (25/25)
[wrk 0]: pool http_host_pool is exhausted (25/25)
[wrk 0]: pool http_path_pool is exhausted (25/25)
[wrk 0]: pool http_request_pool is exhausted (50/50)
[wrk 0]: pool http_host_pool is exhausted (50/50)
[wrk 0]: pool http_path_pool is exhausted (50/50)
[wrk 0]: pool http_request_pool is exhausted (100/100)
[wrk 0]: pool http_host_pool is exhausted (100/100)
[wrk 0]: pool http_path_pool is exhausted (100/100)
[wrk 0]: pool http_request_pool is exhausted (200/200)
[wrk 0]: pool http_host_pool is exhausted (200/200)
[wrk 0]: pool http_path_pool is exhausted (200/200)
[wrk 0]: pool http_header_pool is exhausted (625/625)
[wrk 0]: pool http_request_pool is exhausted (400/400)
[wrk 0]: pool http_host_pool is exhausted (400/400)
[wrk 0]: pool http_path_pool is exhausted (400/400)
```
Is there something can be tuned through conf?
And the QPS for 1024 connections (8 threads) is roughly same with 8 connection (2 threads):
```
weighttp -n 2000000 -t 2 -c 8 -k http://127.0.0.1:11111
```
However on the same machine, I can see 2x-3x boost for lwan or nxweb by increasing client connections.

**Comment by jorisvink** [comment]
The pool messages aren't harmfull. Kore preallocates a set number of items based on your config and grows them automatically if needed. This cannot be set in the configuration file.



> However on the same machine, I can see 2x-3x boost for lwan or nxweb by increasing client connections.

What does your Kore configuration look like and how many cpus are found in your machine you are testing on?

**Comment by byzhang** [comment]
The conf is
```
# Placeholder configuration

bind            0.0.0.0 11111
load            ./cpp.so
ssl_dhparam     dh2048.pem

domain 192.168.1.98 {
        certfile        cert/server.crt
        certkey         cert/server.key
        static  /       page
}
domain 127.0.0.1 {
        certfile        cert/server.crt
        certkey         cert/server.key
        static  /       page
}
```
The machine has 16 logical cores (8 physical). 
Can you show me where to change the configuration of Kore?
(The purpose of benchmark is to get some idea on the throughput of a REST service scenario)
Thanks!

**Comment by jorisvink** [comment]
You can take a peek at https://github.com/jorisvink/kore/blob/master/conf/kore.conf.example to get a view of available configuration options and what they all do.

You'll notice that Kore its capability scales quite well with more worker processes.

**Comment by mankash** [comment]
Hello @byzhang  and @jorisvink - 

Were you able to demonstrate increased performance with any conf parametr tuning? 

I notice from the log that worker 0 is bound to CPU 0. Maybe you can spawn as many workers as phyical cores and disable CPU affinity in the application conf file with 

worker_set_affinity 0

Please let me know if this increases performance

Thanks
