### ISSUE TITLE
Kore fails at starting workers if old shared memory segment exists

### ISSUE THREAD

**Issue by apfohl** [jorisvink/kore#44]
kore: kore_worker_init(): shmget() Invalid argument

Running ```ipcs``` reveals the lost shared segment:

    $ ipcs -p                                      
    IPC status from <running system> as of Mon Apr 27 23:32:41 CEST 2015
    T     ID     KEY        MODE       OWNER    GROUP  CPID  LPID
    Shared Memory:
    m  65536 0x00003a98 --rw-------  andreas    staff  60399  60399

```ipcrm -m 65536``` solved the problem, but Kore should take care about this.

**Comment by jorisvink** [comment]
Did you have any reproducable test case for this? As so far I have not been able to trigger this.

**Comment by apfohl** [comment]
No, it happened only once.

**Comment by jorisvink** [comment]
Ok was able to trigger it now under osx.

Run Kore with N number of workers, kill them all forcefully. Change worker count and start kore.

Changing workers will change the size of the shared memory segment causing it under osx to fail even though we strictly gave it IPC_CREAT.

Manual page for reference
```
[EINVAL] No shared memory segment is to be created, and a shared memory segment exists for key,
but the size of the segment associated with it is less than size, which is non-zero.
```

**Comment by jorisvink** [comment]
I actually think the shmget() code can be simplified by instead of attempting to find a key that doesn't exist simply passing IPC_PRIVATE.

The worker processes fork off from the parent anyway so that should be ok.

**Comment by apfohl** [comment]
Yes that could have happened here. I started kore with:

    $ kore -c conf/benchmark.conf -n

That I had to stop Kore with ```killall```. Maybe that caused the problem.

**Comment by jorisvink** [comment]
You can send SIGQUIT to the parent process as well if you want to gracefully stop Kore running in the background.

**Comment by apfohl** [comment]
Nice, thanks.
