### ISSUE TITLE
handler dispatching is O(n)

### ISSUE THREAD

**Issue by chergert** [jorisvink/kore#54]
https://github.com/jorisvink/kore/blob/master/src/module.c#L199

Took a brief look over things as I tend to do when it they get posted to HN. Nice work, I like what you've done here. I too have had to write various servers in C and I know the amount of time you must have spent on this.

I have some code that might be useful, albeit requires glib/libsoup and so you'd want to make it more generic. But the idea might be useful.

https://github.com/chergert/postal/blob/master/src/cut-n-paste/url-router.c
https://github.com/chergert/postal/blob/master/src/cut-n-paste/url-router.h

It uses a tree to dispatch workers and can do simple wildcards as you dive down. For situations where you don't need obscure regex's, I find it quite useful. Every byte looked at results in forward progress. The extracted params are then available in a hashtable to the caller. I think it would be neat if it did type validation too. It would be as if all of your urls were compiled into one automata.

Anyway, my 2¢ and good luck! If you decide to take any of that code, you have my permission to choose an alternate BSD license to match your code with attribution.

**Comment by jorisvink** [comment]
Hi.

Yup I am aware of this and I might change this in the future if there is a strong argument for it being a real bottleneck.

**Comment by nickdesaulniers** [comment]
O(N) yes, but for small enough N, the overall time for finding something in a list vs in something like an O(1) HashMap can actually be less!  The hard part is knowing for what value of N should you switch from using a List to using a HashMap.

**Comment by chergert** [comment]
A hashmap is not suitable for this purpose unless you can guarantee static paths. In which case a sorted array of pre-hashed paths would be significantly less compares and cacheline friendly. (No pointer chasing and no strcmp, just fast aligned integer compares with `bsearch()`.

**Comment by jorisvink** [comment]
I am closing this issue.

Unless someone comes up with a reasonable amount of proof that the handler lookup is a bottleneck I will not update that code.
