### ISSUE TITLE
Is it possible to embed Lua engine into kore?

### ISSUE THREAD

**Issue by heibor** [jorisvink/kore#55]
My C skill is poor, I don't know is there a plan to embed lua engine into kore? So we can dev by  kore more easy, and we will not lose the performance in the same time.

**Comment by jorisvink** [comment]
I am certain that shouldn't be too hard.

I do not have any immediate plans to incorporate something like that in the base source tree however.

**Comment by warmwaffles** [comment]
I'm fairly certain someone could make an extension to this library to enable a Lua engine

**Comment by Geenz** [comment]
It actually shouldn't be too difficult to do so as a loadable module for Kore.  The catch is you'd need to make sure the bindings are setup for each endpoint in the configuration file.

**Comment by jorisvink** [comment]
The bindings for the end points could be done in such a way that you just have a single callback for every page.

Then you setup your lua glue and let lua do the routing / magic for you instead.

A dynamic ^.*$ rule would work fine for this.

**Comment by jorisvink** [comment]
I'll be adding an example of using lua from a module in the near future.

**Comment by heibor** [comment]
Oh, that will be a great help to me!

**Comment by ivopivo** [comment]
++1 for lua joris :)

**Comment by 0xae** [comment]
++1 for lua joris [2]

**Comment by jorisvink** [comment]
I hear ya.

**Comment by jorisvink** [comment]
Still planning on having a sensible lua example in the tree for the 2.0.0 release.
