### ISSUE TITLE
Problem installing using brew on OS X

### ISSUE THREAD

**Issue by dhoerl** [jorisvink/kore#59]
$ brew install kore --with-postgresql
Error: No available formula for kore 
Searching formulae...
Searching taps...

**Comment by jorisvink** [comment]
Hmm.

Does a brew update help anything?

**Comment by dhoerl** [comment]
Hah - my error - update of brew fixed it. It didn't seem all that long ago that I installed brew, but guess it was longer than I thought. Thanks!

**Comment by jorisvink** [comment]
Excellent, will close this then :)

Have fun!
