### ISSUE TITLE
can the web application be distributed as a standalone executable?

### ISSUE THREAD

**Issue by JoePython1** [jorisvink/kore#69]
The documentation mentions, the application should be run as:
----< command line >-------
$ kore run
----< command line end >-----------

That means distributing the kore middleware libraries along with the application.
Can the web application be distributed as a single binary which statically links to the kore libraries?

**Comment by jorisvink** [comment]
Nope.

Although the thought has crossed my mind of allowing this it goes against the principle of how Kore was designed and currently I have no plans to implement this.
