### ISSUE TITLE
CFLAGS not working properly with external libs

### ISSUE THREAD

**Issue by phinfonet** [jorisvink/kore#75]
I'm trying to use mongoc header but the headers are not loaded when I try to run a "Kore Build"
```
  make teste.o                                                                                                                                                         
  gcc    -c -o teste.o teste.c
  teste.c:1:20: fatal error: mongoc.h: No such file or directory
  compilation terminated.
  <builtin>: recipe for target 'teste.o' failed
  make: *** [teste.o] Error 1
```
```
  CFLAGS="-I/usr/local/include/libmongoc-1.0 -I/usr/local/include/libbson-1.0" make teste.o                                                                            
  gcc -I/usr/local/include/libmongoc-1.0 -I/usr/local/include/libbson-1.0   -c -o teste.o teste.c
```

```
  env CFLAGS="-I/usr/local/include/libmongoc-1.0 -I/usr/local/include/libbson-1.0" kore build```                                                                          
  compiling myapp.c
  ./src/myapp.c:3:20: fatal error: mongoc.h: No such file or directory
  compilation terminated.
  kore build: subprocess trouble, check output
```

**Comment by jorisvink** [comment]
Are you sure mongoc.h resides under /usr/local/include/libmongoc-1.0 because CFLAGS should definitely be picked up.

**Comment by phinfonet** [comment]
It's all okay, and works without Kore. just when I try to use that with
Kore it's not found.

Em seg, 31 de ago de 2015 às 03:25, Joris Vink <notifications@github.com>
escreveu:

**Comment by jorisvink** [comment]
What version are you using?

**Comment by phinfonet** [comment]
kore 1.2.3-release

Em ter, 1 de set de 2015 às 16:29, Joris Vink <notifications@github.com>
escreveu:

**Comment by jorisvink** [comment]
Ah. There lies the problem.

Kore picking up CFLAGS was fixed after 1.2.3 release. Clone the latest code from github, build it, install it and see if the issue still persists. It should fix it.

**Comment by jorisvink** [comment]
Did you try with the latest code base?

**Comment by phinfonet** [comment]
Oh yeah, I tried and it worked as well =D thanks a lot for the support.

Em qui, 17 de set de 2015 às 04:03, Joris Vink <notifications@github.com>
escreveu:

**Comment by jorisvink** [comment]
Super.

I'll close this issue then.
