### ISSUE TITLE
Dont include openssl header files from kore.h when NOTLS=1

### ISSUE THREAD

**Issue by toddwong** [jorisvink/kore#76]
guard the inclusions with a macro maybe?

**Comment by jorisvink** [comment]
Considering the NOTLS option doesn't compile away tons of OpenSSL specific things right now that would break things.

The correct solution is to properly sprinkle KORE_NO_TLS throughout the code base where appropriate to kill anything libssl specific.

**Comment by apfohl** [comment]
@jorisvink could you shortly explain, which kind of functionality would be compromised by having TLS excluded? I think it is at least SPDY, right?

**Comment by jorisvink** [comment]
Yup correct.

SPDY right now, http2 soon as I am only adding support for that over TLS.

**Comment by apfohl** [comment]
Ok, I'm working on a patch for this issue right now. Would you agree to deactivate SPDY and HTTP2 when used without TLS? I wouldn't even compile them into Kore.

**Comment by apfohl** [comment]
Don't merge the PR yet, it's not finished right now. But you can observe the progress.

**Comment by jorisvink** [comment]
Yes, if NOTLS is specified don't even bother building things that are not relevant.

> But you can observe the progress.

Neat :)

**Comment by jorisvink** [comment]
I am closing this issue. If apfohl continues this endavour the PR is still open for it.
