### ISSUE TITLE
brew install kore throws error

### ISSUE THREAD

**Issue by philippnagel** [jorisvink/kore#79]
Hi,

installing via brew throws this error:

```
==> Downloading https://kore.io/release/kore-1.2.3-release.tgz
######################################################################## 100,0%
==> make PREFIX=/usr/local/Cellar/kore/1.2.3 TASKS=1
Last 15 lines from /Users/philippnagel/Library/Logs/Homebrew/kore/01.make:
#include <sys/socket.h>
         ^#include <sys/types.h>
#include <sys/types.h>
         ^

         ^
111 error1 error generated.
 error generated.
 error generated.
 generated.
make: *** [src/buf.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [src/auth.o] Error 1
make: *** [src/accesslog.o] Error 1
make: *** [src/kore.o] Error 1
```

I am running brew on MacOS X 10.11.

Any hints?

**Comment by apfohl** [comment]
Hello, could you paste the command line that produces this output?

**Comment by philippnagel** [comment]
Sorry, I thought this would have been more obvious.

It was simply ``brew install kore``.

**Comment by jorisvink** [comment]
Haven't tried the homebrew stuff on 10.11 yet, will do so tonight.

In the meantime, what happens when you clone the repo and type make? Same errors I would imaging, perhaps a little bit more verbose though.

**Comment by philippnagel** [comment]
Cloning and installing via make seems to work. 
Really weird.

Generally speaking, installing other projects via Homebrew works just fine.

**Comment by apfohl** [comment]
I tried it right now and it worked perfectly. Maybe there's something wrong with you Homebrew installation. Is your Homebrew located at `/usr/local`?

Another thing that is interesting, is the fact that `brew` is not using the pre build bottles from the brew formula. I will investigate what's going on there.

Till then, you should check if your Homebrew is working properly. Use `brew doctor` to get more information.

**Comment by apfohl** [comment]
@jorisvink I figured out what's going on with the pre build bottles. The last release of Kore was on 10.10. So there is no bottle for El Capitan right now. But with the next release an appropriate bottle will be created.

**Comment by philippnagel** [comment]
Alright, thanks for the heads up then!

**Comment by jorisvink** [comment]
@apfohl Ok. Any clues as to why the actual building would fail though via homebrew?

**Comment by apfohl** [comment]
It's not failing on my machine. Works great so far.

**Comment by apfohl** [comment]
@philippnagel Please report back, if you can find something that causes the problem at your side.

**Comment by jorisvink** [comment]
@apfohl Ok

**Comment by apfohl** [comment]
@jorisvink any plans for a new release?

**Comment by jorisvink** [comment]
@apfohl Not the right forum for that question perhaps but yes, soonish :)

**Comment by apfohl** [comment]
I ask, because this would perhaps solve @philippnagel's problem.

**Comment by jorisvink** [comment]
Ah right =)

1.2.3 should work out of the box though on 10.11.

**Comment by philippnagel** [comment]
Updating Xcode seemed to somewhat resolve the issue since I was able to install it successfully through brew.

However building through ``kore build`` or ``kore run`` fails:

```
/usr/local/Cellar/kore/1.2.3/include/kore/kore.h:30:10: fatal error: 'openssl/err.h' file not found
#include <openssl/err.h>
         ^
1 error generated.
kore build: subprocess trouble, check output
```

OpenSSL is symlinked.

I am trying a clean install of Mac OS later today.

**Comment by philippnagel** [comment]
Can be closed. After solving some issues with OpenSSL and 10.11 (this issue was of great help: https://github.com/phusion/passenger/issues/1630) everything seems to work.
