### ISSUE TITLE
kore doesn't pass hardening-check completely.

### ISSUE THREAD

**Issue by fourdollars** [jorisvink/kore#80]
hardening-check is a command line tool to check binaries for security hardening features.
It is included in the package of hardening-includes in Debian and Ubuntu.
You can follow the steps below to get the similar result.
```sh
$ sudo apt-get install git dpkg-dev hardening-includes build-essential
$ git clone https://github.com/jorisvink/kore.git
$ cd kore
$ export DEB_BUILD_MAINT_OPTIONS=hardening=+all
$ export CPPFLAGS="$(dpkg-buildflags --get CPPFLAGS)"
$ export CFLAGS="$(dpkg-buildflags --get CFLAGS)"
$ export CXXFLAGS="$(dpkg-buildflags --get CXXFLAGS)"
$ export LDFLAGS="$(dpkg-buildflags --get LDFLAGS)"
$ make clean
$ make
$ hardening-check -v ./kore
./kore:
 Position Independent Executable: yes
 Stack protected: yes
 Fortify Source functions: yes (some protected functions found)
	unprotected: memcpy
	unprotected: read
	unprotected: fgets
	unprotected: memset
	unprotected: getcwd
	protected: fprintf
	protected: vasprintf
	protected: snprintf
	protected: printf
	protected: asprintf
	protected: syslog
	protected: vsnprintf
 Read-only relocations: yes
 Immediate binding: yes
```
https://wiki.debian.org/HardeningWalkthrough
https://wiki.debian.org/Hardening

**Comment by jorisvink** [comment]
I'll gladly take diffs for this :)

**Comment by oneswig** [comment]
From the hardening-check manpage:

> When an executable was built such that the fortified versions of the glibc
> functions are not useful (e.g. use is verified as safe at compile time, or
> use cannot be verified at runtime), this check will lead to false alarms.  In
> an effort to mitigate this, the check will pass if any fortified function is
> found, and will fail if only unfortified functions are found. Uncheckable
> conditions also pass (e.g. no functions that could be fortified are found, or
> not linked against glibc).

From a visual inspection I didn't see any issues with the usage of the 5 functions cited in the output of hardening-check, and many usages are obviously correct without requiring in-depth analysis.

Is this a case of a false alarm from the tool?  Can you demonstrate that it is not?  Thanks.

**Comment by fourdollars** [comment]
To be honest, I don't know how to tell if this is a false alarm from the tool so far.

**Comment by jorisvink** [comment]
These tools generally just check for occurrences of said function calls in the code and spew out a warning without any real substance.

I am very tempted to close this issue as there is no substantial proof here there is anything wrong.
