### ISSUE TITLE
Makefile build example

### ISSUE THREAD

**Issue by warmwaffles** [jorisvink/kore#81]
I'd rather use CMake or Makefile to build kore. It is mentioned in the documentation that it is possible but no examples or how to is provided.

**Comment by jorisvink** [comment]
> I'd rather use CMake or Makefile to build kore.

You are of course talking about the modules Kore uses, am I correct?

There is no real examples considering the modules Kore uses are nothing more than dynamic libraries.
I figured anyone willing to build these via their own Makefiles would be familiar on said subject.

**Comment by warmwaffles** [comment]
> There is no real examples considering the modules Kore uses are nothing more than dynamic libraries. I figured anyone willing to build these via their own Makefiles would be familiar on said subject.

When I last tried this (like 3 months ago) I didn't understand make or cmake well. I should give this another shot sometime and maybe add it to the examples.

**Comment by jorisvink** [comment]
I'll gladly put a clean and simple Makefile example in the documentation if it pops up!

**Comment by matthew-dailey** [comment]
I actually just tried building a kore app with a Makefile, but was unable to link to kore because (if I'm not mistaken) kore's build does not produce a library.

I got around the problem by [changing kore's Makefile](https://github.com/matthew-dailey/kore/blob/bbbd8f0fcf7141b1deb601511b6472d525d74389/Makefile) to produce a static library which I could then link against.

Assuming I went about this the right way, I planned on contributing back the library creation code.

**Comment by warmwaffles** [comment]
I actually have included core by source and I have to pick apart the main that is defined. I'd rather be in charge of the setup and tear down. I'll see where this leads me and contribute back if I make anything of it.

**Comment by jorisvink** [comment]
Don't forget using Kore as a library makes you lose the ability to reload your app (module) on the fly.

**Comment by warmwaffles** [comment]
Yea, the app would be in a docker container anyways so reloading on the fly is not really a concern.

**Comment by jorisvink** [comment]
Gotcha.

Somewhere on my TODO was a bullet point about making it more clear about how Kore could be used as a library. Especially in regards how to setup domains, page handlers and the likes programmatically. It just never got done.

The best way to see how this works is to just poke at config.c and the dozen calls it does per configuration directive. If that can be cleaned up a bit it might be worth including it in the main repo and adding an additional make target for the static library people can link with.

**Comment by warmwaffles** [comment]
Yea I was hoping I could run this as a library alone and set up the calls pragmatically as well as set the routing up in a programmable way. I'm finding some of the methods are static and not defined in the `kore.h`. 

Unfortunately because I am a narcissistic C dev, I went through and replaced a lot of the tabs with spaces. If I can distill the changes that I made easily, I'll make a proper PR in the existing format. No promises though.

**Comment by matthew-dailey** [comment]
> Don't forget using Kore as a library makes you lose the ability to reload your app (module) on the fly.

I went ahead and tested this, and I found I was able to reload using the `kill -HUP $pid` syntax against my running app that was built against the `libkore.a` I built from my fork.

I probably don't have a full understanding of what else my library method is missing, but at least that one problem doesn't seem to be an issue.

**Comment by jorisvink** [comment]
> Unfortunately because I am a narcissistic C dev, I went through and replaced a lot of the tabs with spaces.

Yeah you'll want to fix that if you want this to be considered for merging :)

**Comment by jorisvink** [comment]
> I went ahead and tested this, and I found I was able to reload using the kill -HUP $pid syntax against my running app that was built against the libkore.a I built from my fork.

It probably didn't do anything. The SIGHUP signal makes Kore reopen its loaded .so files in order. If you've linked against libkore.a and you've done the heavy lifting programmatically - unless you are still loading .so files somehow - I don't see how it would've done anything useful.

**Comment by warmwaffles** [comment]
> Yeah you'll want to fix that

just curious, what are you using for your tab width? Mine is at 4 and it things don't line up nicely. I bumped it up to 8 and it just became unreadable.

**Comment by jorisvink** [comment]
> just curious, what are you using for your tab width? Mine is at 4 and it things don't line up nicely. I bumped it up to 8 and it just became unreadable.

It's 8, default nvi stuff.
