### ISSUE TITLE
There is a lack of PGP/GPG signature.

### ISSUE THREAD

**Issue by fourdollars** [jorisvink/kore#83]
Hi,

I am a Debian Maintainer. I start to maintain this program in Debian official archive recently.

There is some problem for debian-watch-may-check-gpg-signature.
Please see https://lintian.debian.org/full/fourdollars@gmail.com.html#kore_1.2.3-3 for details.

Please consider to use PGP/GPG signature on your future releases.

**Comment by jorisvink** [comment]
New releases will be properly signed.
