### ISSUE TITLE
Hello World example returns 404

### ISSUE THREAD

**Issue by MrDunne** [jorisvink/kore#84]
Was sent a link to kore and thought it would be worth having a look at a month or so ago, and had this issue. Thought I would look at it again now but the issue repeated itself.

The hello-world example (as per kore.io, without any changes) returns 404 on all requests. Clean project created using standard kore tool, with the hello world code.

Known issue?

**Comment by jorisvink** [comment]
Not known at all.

What does your configuration look like?

**Comment by MrDunne** [comment]
Sorry about the delay, experimenting when time is available.
I have just the default conf, so thats probably the case..

bind		127.0.0.1 8888
load		./koretest.so
tls_dhparam	dh2048.pem

domain 127.0.0.1 {
	certfile	cert/server.crt
	certkey		cert/server.key
	static	/	page
}

**Comment by jorisvink** [comment]
In this case it should work however, as the example code on the front page is using the same function callback "page" as the default configuration. So you should get a hello world response on https://127.0.0.1:8888.

Unless you attempted to connect to https://localhost:8888 ? In which case the domain directive is incorrect.

.joris

**Comment by MrDunne** [comment]
I feel amazingly stupid. Yeah, you called it.
