### ISSUE TITLE
kore_buf empty

### ISSUE THREAD

**Issue by PauloMelo** [jorisvink/kore#86]
would you consider an empty function for kore_buf? This could reuse a buffer without free + new malloc.

Something like this...
```
void
kore_buf_empty(struct kore_buf *buf) 
{
        buf->offset = 0;
}
```

**Comment by jorisvink** [comment]
Yup, although I would probably call it kore_buf_reset().

**Comment by PauloMelo** [comment]
Yes I agree

**Comment by jorisvink** [comment]
I was expecting a pull request for this ... :-)
