### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by kainlite** [jorisvink/kore#88]
Hey,

How are you?, I've a few questions that came to my mind and didn't find a better place to ask.

How are you using kore today (In real life)?

Have you tried to use kore with mongodb (and what were your results/thoughts)?

And last but not least:

Are you using any template engine (which one?, thoughts)?

How are you sending emails? (I'm using tasks, the example really worked this for me)

---------------------------------------------------------------------------------------------------------------

To be fair with my questions, i will answer all 4 of them:

I'm doing a chat api, more like a toy project, having some fun basically.

https://github.com/kainlite/chapi

I've tried to get mongodb into kore, no success (at least in a good/decent way), I'm just starting with c.

I'm using libflate, not like a big lib, but it gets the job done.
http://flate.dead-inside.org/

For email I'm using libcurl, and kore threads (TASKS).

Thanks.

**Comment by jorisvink** [comment]
Hi,

> How are you using kore today (In real life)?

Mostly for any and all web based things I run both personally and professionally.

> Have you tried to use kore with mongodb

I have not no, I only have experience dealing with postgresql. If mongodb offers a sane C API however it should integrate nicely with Kore in one way or the other I guess, but I have no idea :-)

> Are you using any template engine

Again the answer is no, I tend to not do a lot of things that require a template engine of sorts. The one you linked seems interesting.

> I'm doing a chat api, more like a toy project, having some fun basically.

I'm glad to see people using Kore in any shape or form and that the examples are of some use :-)

.joris

**Comment by jorisvink** [comment]
Closing this one.
