### ISSUE TITLE
What do you think about flex/bison for parsing config file?

### ISSUE THREAD

**Issue by Houdini** [jorisvink/kore#90]
I'd like to practice with flex/bison and I could change parsing.
Should I handle that?

**Comment by jorisvink** [comment]
Depending how it looks like when done I might merge it in, however there are no promises as I'm quite comfortable with the way the config is parsed *right now*.

But yes, if you provide diffs I might change my mind because while I am comfortable it is a bit of a mess.

.joris

**Comment by Houdini** [comment]
Ok, I try.
Close this issue for now

**Comment by apfohl** [comment]
@Houdini You should consider [Lemon](http://www.hwaci.com/sw/lemon/) instead of Bison as the parser generator. It is much less error prone than Bison. Here is a little example: https://github.com/compiler-dept/calculator.

**Comment by Houdini** [comment]
@apfohl Thanks! I definitly will check it.
It looks simplier, than bison.
