### ISSUE TITLE
Tasks read/write

### ISSUE THREAD

**Issue by kainlite** [jorisvink/kore#91]
Hi Joris,

How are you ?

I've been testing "tasks" and I think I've found a bug, it's easy to reproduce:

Go to tasks example, compile, run: 

https://github.com/jorisvink/kore/tree/master/examples/tasks

And visit the url like 5 or 6 times:

https://127.0.0.1:8888/?user=abcdefghijklmno

I noticed this problem while working on my app, turns out that it adds some random characters at the end, I was looking at the source and trying to figure it out, but with no success so far.

I've addded a few logging lines:
```c
91                kore_log(LOG_NOTICE, "Before writing to the channel: %s", user);
192               kore_log(LOG_NOTICE, "Read from the channel: %s", user);
```
The output turns to this:
```c
[wrk 0]: Before writing to the channel: pepepepepepepepe
[wrk 0]: Read from the channel: pepepepepepepepe
[wrk 0]: Before writing to the channel: pepepepepepepepe
[wrk 0]: Read from the channel: pepepepepepepepe
[wrk 0]: Before writing to the channel: pepepepepepepepe
[wrk 0]: Read from the channel: pepepepepepepepe
[wrk 0]: Before writing to the channel: pepepepepepepepe
[wrk 0]: Read from the channel: pepepepepepepepe!QQ
```

Thanks.

**Comment by jorisvink** [comment]
Hi,

Is this -release or pulled from github? Also what os is this under? OSX, Linux, *BSD?

.joris

**Comment by jorisvink** [comment]
I think this is actually a misunderstanding in your handling of the received data.

You are treating it as a C string, however it is not NUL terminated when it comes over the task socket as it is just normal data.

**Comment by kainlite** [comment]
This is pulled from github, running on linux x64.

Oh I see, so how should i treat that data coming from the socket? to maintain sanity.

Thanks.

**Comment by jorisvink** [comment]
As normal arbitrary data? You get a bunch of bytes and the length.

**Comment by kainlite** [comment]
So I ended up doing something like this:

```c
#define MAX_LENGTH 64
char            to[MAX_LENGTH];
char            dst[MAX_LENGTH];

len = kore_task_channel_read(t, dst, sizeof(dst));
if (len > sizeof(dst))
        return (KORE_RESULT_ERROR);

kore_snprintf(to, (len+1), NULL, "%s", dst); 
```

And now everything is ok.

**Comment by jorisvink** [comment]
Or you could do the right thing by specifying a width to your format string (look up %.*s).

What you did is a horrible idiom.

**Comment by kainlite** [comment]
I just need to get the string as a normal c string \0 terminated from the kore_task_channel_read method, the only way to get the real length is using len returned by it plus one for the \0 char. I can't really see the difference between:

```c
 kore_snprintf(to, (len+1), NULL, "%s", dst); 
```

And:

```c
 kore_snprintf(to, (len+1), NULL, "%.*s", dst); 
```

I don't know the length of the string coming from the channel, so how could I use %.*s here? 

Or how should it look a good solution?

Thanks.

**Comment by jorisvink** [comment]
You could always just do dst[len] = '\0' to properly NUL terminate it. Which is fine to do as you already checked len < sizeof(dst).

As for the width specifier you use it as:

snprintf(buf, sizeof(buf), "%.*s", len, dst);

Not as the way you described it yourself.

**Comment by jorisvink** [comment]
This stuff is really beyond the scope of using Kore however, it's basic C.

**Comment by kainlite** [comment]
Yeah, I know, sorry about that, I'm starting with c, and it was my bad when i assumed that the read method would give me a null terminated string.

**Comment by jorisvink** [comment]
No worries.

> i assumed that the read method would give me a null terminated string.

Don't make assumptions, always read the documentation :-) (which in Kore its case should improve ;))
