### ISSUE TITLE
Archlinux Package!

### ISSUE THREAD

**Issue by jgmdev** [jorisvink/kore#93]
Just writing to let you know that I found this project interesting and wrote a [PKGBUILD](https://aur.archlinux.org/packages/kore-git) for archlinux that fetches latest git code, kore source is small enough to compile in the blink of an eye, fantastic! Again, really interesting project, there aren't much alternatives for C web frameworks on the wild.

**Comment by jorisvink** [comment]
Hi,

This is great, thank you for your work!

.joris
