### ISSUE TITLE
kore_auth_cookie problem

### ISSUE THREAD

**Issue by PauloMelo** [jorisvink/kore#94]
Hi Joris,
with the last change on auth.c regarding correct usage of http_request_header() the sent cookies are thrown away because of the kore_split_string on the original value of the header instead of a copy.
With this action other values sent on the cookie are discarded.
I propose to copy the result of http_request_header to another variable and work on this variable keeping the original values untouched...

Do you need any help on this? Would you suggest another way?

**Comment by jorisvink** [comment]
I'm aware of this problem yeah, it will be fixed this week.

Good catch :-)

**Comment by jorisvink** [comment]
@PauloMelo This should be fixed now since https://github.com/jorisvink/kore/commit/519c3c16d42127884f4802832c8439adc8e2feb5 , give it a spin and let me know if solves your issues.

.joris

**Comment by PauloMelo** [comment]
perfectly. Thanks.

Paulo
