### ISSUE TITLE
PGSQL

### ISSUE THREAD

**Issue by PauloMelo** [jorisvink/kore#95]
Joris, 

Is the PGSQL implementation only working with async connections? Aren't there situations where the process needs to run inside a closed loop, like for instance a database authentication scheme? 
How to proceed and use the connection pool for direct PGSQL connections?

**Comment by jorisvink** [comment]
Hi.

The pgsql backend only uses the libpq async stuff yeah. Nothing stops you from using libpq directly though if you want to send synchronous SQL to it.

.joris

**Comment by PauloMelo** [comment]
Hi Joris,
OK. So just to check if my understanding is correct.
You create the connections to the database and store them in the connection pool. When a database connection is needed you take one from the pool, use it, and after being used you store them back.
Am I right? So the cost of connecting to a database is reduced using a pool connection.
How can I use this pool? I can see the pgsql_conn_release but it is not open...
So would it be possible to extend the pgsql with a int kore_pgsql_query_sync(struct kore_pgsql *, struct http_request *, const char *); ?
it could be implemented very similar to the kore_pgsql_query in a way that after the call to get the connection it would call PQexec and the PGresult set on the kore_pgsql. So after returning success we can use the kore_pgsql_ntuples and kore_pgsql_getvalue the resolve what is needed. Finally we make the call to kore_pgsql_cleanup to release memory and connections as usual. 

What do you think? I can make this for you if you agree...

Regards,
Paulo

**Comment by jorisvink** [comment]
Correct, it spreads out work over different connections. The pgsql_prepare() function automatically finds an available connection or spawns a new one if it has not reached maximum configured connections.

If you want to build a synchronous interface you should be able to do so in the way your described yes, and I certainly would like to add that to the Kore pgsql backend :-)

So go for it and hit up my mail or this issue in case you have more questions about implementing this.

.joris

**Comment by PauloMelo** [comment]
Ok i'll take that into my care, I will create the synchronous connection, and share the code.

I have another question to get your ideas. What about multiple databases? How would you think on taking care of multiple connections to multiple databases?

Regards,
Paulo

On 20/12/2015, at 10:10, Joris Vink <notifications@github.com> wrote:

Correct, it spreads out work over different connections. The pgsql_prepare() function automatically finds an available connection or spawns a new one if it has not reached maximum configured connections.

If you want to build a synchronous interface you should be able to do so in the way your described yes, and I certainly would like to add that to the Kore pgsql backend :-)

So go for it and hit up my mail or this issue in case you have more questions about implementing this.

.joris

**Comment by jorisvink** [comment]
>  What about multiple databases? How would you think on taking care of multiple connections to multiple databases?

I haven't given that any thoughts yet. Possibly splitting up the pgsql connections based upon a new dbname parameter of sorts, not sure.

.joris
